### ISSUE TITLE
Add continuos integration

### ISSUE THREAD

**Issue by chrisfilo** [nipy/heudiconv#10]

**Comment by hanke** [comment]
and add at least a single test ;-)

**Comment by satra** [comment]
is there a realistic dicom dataset available for use? if so, we can add tests, demos, documentation, etc.,.

**Comment by yarikoptic** [comment]
yesterday I have got some lame phantom dataset (coarse resolution, just 1 anat, 1 dwi, 2 runs, fieldmap per run, 2 tasks): http://datasets.datalad.org/test/dartmouth-siemens/PHANTOM1_3/  but it is not as small as I think we would need for a test (139MB).  but smth to start with? ;)  I could probably try to reduce its size even further

**Comment by satra** [comment]
thanks @yarikoptic!

**Comment by satra** [comment]
@yarikoptic - did you group those dicoms, or did they come out of the scanner that way?

**Comment by yarikoptic** [comment]
They are exactly how scanner exported then to USB flash drive. I did nothing to them yet ;-)

**Comment by mgxd** [comment]
closing this - feel free to reopen
