### ISSUE TITLE
bring back an assert for correctness of regex-tuned json for the paranoid Yarik

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#104]
In 12e94ea8533d3b49c2c733a313f6baf507ce42e8 it was commented out.

@satra , was the issue that some floating point number changed its value/json serialization somehow?  do you happen to remember where/how did it happen, since I think it should've not happened (at least never happened to me).

that assert is kinda critical to have in one form or another to guarantee that ugly regex tuning of output didn't backfire

**Comment by satra** [comment]
@yarikoptic - when you do not use minmeta there are many floating point numbers. so ideally the assert should do a proper check (a hierarchical check with np.close/allclose. a simple string check is not quite correct.
