### ISSUE TITLE
.heudiconv & bids-validator

### ISSUE THREAD

**Issue by bkraft4257** [nipy/heudiconv#106]
I have been using heudiconv for a couple of months now. It is a wonderful piece of software that does it's job very well.   Thank you for providing this tool as open source.  

I would like to provide some constructive feedback from an end user with the possibility of improving the tool.  My typical workflow is as follows 

1) Run heudiconv to convert my DICOM files to NIFTI in a BIDS directory structure.
2) Run bids-validator on the tools to verify that the BIDS directory structure is still maintained.  
3) Fix any problems that have been revealed by bids-validator

This workflow works very well for me except the bids-validator will always produce a 1-NOT_INCLUDED warning (excerpt at end of this message) due to the .heudiconv folder. 

I can delete this directory and the bids-validator will pass with no problems.  However, the .heudiconv file contains valuable information that I want to maintain.   I would like to recommend that the .heudiconv directory be moved outside the bids output directory since it doesn't adhere to the BIDS requirements. 

I have modified my copy of heudiconv line 1292 from 

    idir = os.path.join( outdir, '.heudiconv', sid)  

to

    idir = os.path.join( outdir[:-1] + '.heudiconv', sid)  

This will append the .heudiconv to the output directory instead of creating the hidden directory within the BIDS output directory.  For example, before the change the idir for my conversion was 

/gandg/hfpef/bids/.heudiconv

after my change the idir was

/gandg/hfpef/bids.heudiconv

So far my testing hasn't revealed any problems with this change.  However, I would be the first to admit that my testing is limited to just a few cases.  I realize that this suggestion isn't as clean as having a hidden directory  within the BIDS directory but it serves the purpose of maintaining the information in the heudiconv while adhering to the BIDS requirements. 

I hope this feedback from a user will be helpful and be used to improve this great tool.  

Bob

 ➜  bids bids-validator .
	1: This file is not part of the BIDS specification, make sure it isn't included in the dataset by accident. Data derivatives (processed data) should be placed in /derivatives folder. (code: 1 - NOT_INCLUDED)
		./.heudiconv/hfs070/ses-1/info/dicominfo_ses-1.tsv
			Evidence: dicominfo_ses-1.tsv
		./.heudiconv/hfs070/ses-1/info/filegroup_ses-1.json
			Evidence: filegroup_ses-1.json
		./.heudiconv/hfs070/ses-1/info/hfpef_protocol.py
			Evidence: hfpef_protocol.py

**Comment by yarikoptic** [comment]
Note that you can provide a config file to the validator which would tell to ignore some paths. See eg
https://github.com/nipy/heudiconv/blob/master/heuristics/dbic_bids_validator.cfg

**Comment by chrisfilo** [comment]
Just to reiterate that this is a warning not an error and thus it could be ignored. The command line version of the validator does not do a grate job distinguishing the errors from warnings (we will improve this: https://github.com/INCF/bids-validator/issues/347).

Additionally BIDS does include a place for storing such conversion information - the `/code` folder (see [section 8.2](http://bids.neuroimaging.io/bids_spec1.0.2.pdf)). This folder is ignored by the validator and storing those files there will not raise a warning. Maybe heudiconv should default to using that?

**Comment by satra** [comment]
@chrisfilo -  as @yarikoptic pointed out through his configuration link that there are multiple folders that are created at the top level of a dataset. for those other tools to function they need to remain at the top level.

**Comment by mgxd** [comment]
@chrisfilo I like the suggestion of using the `/code` folder going forward, as it will make things more obvious to the users instead of dealing with hidden folders.

@satra @yarikoptic what do you guys think?

**Comment by satra** [comment]
@mgxd - see my response above.

git, git annex, and datalad will not work with those folders sitting inside `/code`.

**Comment by mgxd** [comment]
ah I see - perhaps then we can generate a config automatically if the BIDS flag is used, and briefly mention in the documentation?

**Comment by mgxd** [comment]
closed in INCF/bids-validator#368
