### ISSUE TITLE
Multiple session handling

### ISSUE THREAD

**Issue by gregorymichelet** [nipy/heudiconv#107]
Hi,

I was trying this tool today (good work!). I was wondering if heudiconv can handle multiple sessions ? I have seen that the -ss flag can't take multiple session ID

**Comment by yarikoptic** [comment]
you could have a look at a (somewhat "elaborate") https://github.com/nipy/heudiconv/blob/master/heuristics/dbic_bids.py heuristic -- at DBIC we specify session within the scout sequence name and it is picked up in `infotoids`.  Sample DICOMs could be found within our QAs: http://datasets.datalad.org/?dir=/dbic/QA (already in BIDS, but original dicoms in tarballs under sourcedata).  If decide to make your own heuristic, you might benefit from using `{bids_subject_session_dir}` in your templates

hope this helps

**Comment by gregorymichelet** [comment]
Thank you for the answer!

I'll go with my own heuristic and DICOMs but your solution is definitely helping
