### ISSUE TITLE
Make it pip installable

### ISSUE THREAD

**Issue by chrisfilo** [nipy/heudiconv#11]

**Comment by yarikoptic** [comment]
I wonder if that implies establishing setup.py and RFing into a proper python module, or there was some explicit decision to keep it as a self sufficient script

**Comment by hanke** [comment]
TBH I have seen it as a feature to not have/require the python install thingie. If #6 is fully addressed, we could have a deployment by copying a single file. OTOH, stuff like dcmstack brings in lots of dependencies -- so it may not be worth it.

**Comment by satra** [comment]
we have to decide on dependency on nipype - happy to strip out, but then we will replicate internal functionality for efficiency, not just the interfaces. please comment in #6.

in terms of dependencies, i don't think we can get around pydicom and dcmstack, which means numpy as well. from that perspective having an installable python package would be good. also it would allow us to create scanner specific code.

**Comment by mih** [comment]
Give that I did this multiple times today, I think it is OK to close this ;-)
