### ISSUE TITLE
Embedding failed: name 'sys' is not defined

### ISSUE THREAD

**Issue by mainux** [nipy/heudiconv#114]
Hi, I get this error in some dcm images when running heudiconv.

My command: 
```
heudiconv -d /home/mtermenon/EXPERIMENTS/BIDS/DICOMdir2/{subject}/"CRANEO_FUNCIONAL - 1"/*/*.dcm -s $sub -f /home/mtermenon/EXPERIMENTS/BIDS/HeuDiConv/heudiconv/heuristics/convertall.py -o /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir
```

The error:
```
INFO: Executing node embedder in dir: /tmp/heudiconvdcmd5rxjy_1/embedder
ERROR: Embedding failed: name 'sys' is not defined
Interface Function failed to run. 
INFO: PROCESSING DONE: {'subject': 'sub08', 'outdir': '/home/mtermenon/EXPERIMENTS/BIDS/BIDSdir/', 'session': None}
```
Thanks in advance for the help!

**Comment by mainux** [comment]
Hi, thanks for your answer. I rerun it and this is why I get:

My command:
heudiconv -d /home/mtermenon/EXPERIMENTS/BIDS/DICOMdir3/{subject}/"CRANEO_FUNCIONAL - 1"/*/*.dcm -s $sub --bids -f /home/mtermenon/EXPERIMENTS/BIDS/HeuDiConv/heudiconv/heuristics/convertall.py -o /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir

The error:
INFO: Converting /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir/run079 (1 DICOMs) -> /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: Executing node convert in dir: /tmp/heudiconvdcml_r703af/convert
INFO: Running: dcm2niix -b y -z i -x n -t n -m n -f BIDSdir -o /tmp/heudiconvdcml_r703af/convert -s n -v n /tmp/heudiconvdcml_r703af/convert/IM-0043-0001.dcm
WARNING: Failed to detect fullfilled BIDS layout.  No scans.tsv file(s) will be produced for /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir/run079.json
INFO: Executing node embedder in dir: /tmp/heudiconvdcml_r703af/embedder
ERROR: Embedding failed: name 'sys' is not defined
Interface Function failed to run. 
INFO: Post-treating /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir/run079.json file

Other warnings:
INFO: Converting /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir/run078 (3 DICOMs) -> /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: Executing node convert in dir: /tmp/heudiconvdcml_r703af/convert
INFO: Running: dcm2niix -b y -z i -x n -t n -m n -f BIDSdir -o /tmp/heudiconvdcml_r703af/convert -s n -v n /tmp/heudiconvdcml_r703af/convert/IM-0049-0001-0002.dcm
WARNING: Following series files likely have multiple (3) volumes (orientations?) generated: /home/mtermenon/EXPERIMENTS/BIDS/DICOMdir3/sub08/CRANEO_FUNCIONAL - 1/Localizers_1/IM-0049-0001-0002.dcm ...
WARNING: Failed to detect fullfilled BIDS layout.  No scans.tsv file(s) will be produced for /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir/run078-1.json, /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir/run078-2.json, /home/mtermenon/EXPERIMENTS/BIDS/BIDSdir/run078-3.json
WARNING: For now not embedding BIDS and info generated .nii.gz itself since sequence produced multiple files

Thanks!

**Comment by mgxd** [comment]
@mainux hmm okay, let's get to the bottom of this.

we recently updated this package - could you try this out with our latest codebase?
```
pip install -U https://github.com/nipy/heudiconv/archive/master.zip
```
thanks!

**Comment by mgxd** [comment]
@mainux is this issue still present with the latest master branch?

**Comment by mainux** [comment]
Hi, sorry for my late answer, but I don't have admin permission and things take long...

I tried today and yes, it is still happening, see below for an example:
171205-12:40:08,765 workflow INFO:
	 Executing node convert in dir: /tmp/dcm2niixfjyqngje/convert
171205-12:40:08,768 workflow INFO:
	 Running node "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z i -x n -t n -m n -f dwi -o /tmp/dcm2niixfjyqngje/convert -s n -v n /tmp/dcm2niixfjyqngje/convert/IM-0035-0001.dcm.
171205-12:40:08,851 interface INFO:
	 stdout 2017-12-05T12:40:08.851293:Compression will be faster with /usr/local/bin/pigz
171205-12:40:08,851 interface INFO:
	 stdout 2017-12-05T12:40:08.851293:Chris Rorden's dcm2niiX version v1.0.20170724 GCC4.4.7 (64-bit Linux)
171205-12:40:08,851 interface INFO:
	 stdout 2017-12-05T12:40:08.851293:Found 1 DICOM image(s)
171205-12:40:08,851 interface INFO:
	 stdout 2017-12-05T12:40:08.851293:Note: rare 16-bit UNSIGNED integer image. Older tools may require 32-bit conversion
171205-12:40:08,851 interface INFO:
	 stdout 2017-12-05T12:40:08.851293:Convert 1 DICOM as /tmp/dcm2niixfjyqngje/convert/dwi (104x104x72x1)
171205-12:40:08,932 interface INFO:
	 stdout 2017-12-05T12:40:08.932830:Conversion required 0.125918 seconds (0.080000 for core code).
171205-12:40:09,74 workflow INFO:
	 Executing node embedder in dir: /tmp/embedmeta8t4uut5a/embedder
171205-12:40:09,78 workflow INFO:
	 Running node "embedder" ("nipype.interfaces.utility.wrappers.Function").
171205-12:40:09,83 heudiconv.dicoms ERROR:
	 Embedding failed: name 'sys' is not defined

Anyway, the conversion to nifti and the BIDS validator is fine, but I'd like to understand this error if possible. Maybe I'm doing something wrong, my script looks as follows:

subj=('03' '08')

for sub in ${subj[@]}
do
/opt/anaconda3/bin/heudiconv -d /home/EXPERIMENTS/BIDS/DICOMdir/{subject}/"CRANEO_FUNCIONAL - 1"/*/*.dcm -s $sub -c dcm2niix -f /home/EXPERIMENTS/BIDS/cmrr_heuristics_mine.py -b -o /home/EXPERIMENTS/BIDS/BIDSdir/
done

Thank you for your support

**Comment by mgxd** [comment]
@mainux Could you paste the contents of your heuristic `/home/EXPERIMENTS/BIDS/cmrr_heuristics_mine.py`?

**Comment by mainux** [comment]
Hey, here it is!

Best,

Maite

import os

def create_key(template, outtype=('nii.gz','dicom'), annotation_classes=None):
    if template is None or not template:
        raise ValueError('Template must be a valid format string')
    return (template, outtype, annotation_classes)


def infotodict(seqinfo):
    """Heuristic evaluator for determining which runs belong where

    allowed template fields - follow python string module:

    item: index within category
    subject: participant id
    seqitem: run number during scanning
    subindex: sub index within group
    """
    t1 = create_key('sub-{subject}/anat/sub-{subject}_T1w')
    t2 = create_key('sub-{subject}/anat/sub-{subject}_T2w')
    flair = create_key('sub-{subject}/anat/sub-{subject}_FLAIR')
    flairNorm = create_key('sub-{subject}/anat/sub-{subject}_acq-norm_FLAIR')
    rest = create_key('sub-{subject}/func/sub-{subject}_task-rest_run-{item:02d}_bold')
    restPhase = create_key('sub-{subject}/func/sub-{subject}_task-restPhase_run-{item:02d}_bold')
    restAP = create_key('sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-{item:02d}_bold')
    restPA = create_key('sub-{subject}/func/sub-{subject}_task-rest_acq-PA_run-{item:02d}_bold')
    restSbref = create_key('sub-{subject}/func/sub-{subject}_task-rest_run-{item:02d}_sbref')
    restAPSbref = create_key('sub-{subject}/func/sub-{subject}_task-rest_acq-AP_run-{item:02d}_sbref')
    restPASbref = create_key('sub-{subject}/func/sub-{subject}_task-rest_acq-PA_run-{item:02d}_sbref')
    petit = create_key('sub-{subject}/func/sub-{subject}_task-petit_run-{item:02d}_bold')
    petitPhase = create_key('sub-{subject}/func/sub-{subject}_task-petitPhase_run-{item:02d}_bold')
    petitAP = create_key('sub-{subject}/func/sub-{subject}_task-petit_acq-AP_run-{item:02d}_bold')
    petitPA = create_key('sub-{subject}/func/sub-{subject}_task-petit_acq-PA_run-{item:02d}_bold')
    petitSbref = create_key('sub-{subject}/func/sub-{subject}_task-petit_run-{item:02d}_sbref')
    petitAPSbref = create_key('sub-{subject}/func/sub-{subject}_task-petit_acq-AP_run-{item:02d}_sbref')
    petitPASbref = create_key('sub-{subject}/func/sub-{subject}_task-petit_acq-PA_run-{item:02d}_sbref')
    pinel = create_key('sub-{subject}/func/sub-{subject}_task-pinel_run-{item:02d}_bold')
    pinelAP = create_key('sub-{subject}/func/sub-{subject}_task-pinel_acq-AP_run-{item:02d}_bold')
    pinelPA = create_key('sub-{subject}/func/sub-{subject}_task-pinel_acq-PA_run-{item:02d}_bold')
    pinelSbref = create_key('sub-{subject}/func/sub-{subject}_task-pinel_run-{item:02d}_sbref')
    pinelAPSbref = create_key('sub-{subject}/func/sub-{subject}_task-pinel_acq-AP_run-{item:02d}_sbref')
    pinelPASbref = create_key('sub-{subject}/func/sub-{subject}_task-pinel_acq-PA_run-{item:02d}_sbref')
    dwi = create_key('sub-{subject}/dwi/sub-{subject}_dwi')
    dwiSbref = create_key('sub-{subject}/dwi/sub-{subject}_sbref')
    dwiPA = create_key('sub-{subject}/dwi/sub-{subject}_acq-PA')
    dwiPASbref = create_key('sub-{subject}/dwi/sub-{subject}_acq-PA_sbref')

    
    info = {t1:[], t2:[], flair:[], flairNorm:[], rest:[], restPhase:[], restSbref:[], restAP:[], restPA:[], restAPSbref:[],restPASbref:[], petit:[], petitPhase:[], petitSbref:[], petitAP:[], petitPA:[], petitAPSbref:[], petitPASbref:[], pinel:[], pinelSbref:[], pinelAP:[], pinelPA:[], pinelAPSbref:[],pinelPASbref:[], dwi:[], dwiSbref:[], dwiPA:[], dwiPASbref:[]}

    for idx, s in enumerate(seqinfo):
        if (s.dim3 == 176) and (s.dim4 == 1) and ('t1_mprage' in s.protocol_name):
            info[t1] = [s.series_id]
        if (s.dim3 == 176) and (s.dim4 == 1) and ('t2_space' in s.protocol_name):
            info[t2] = [s.series_id]
        if (s.dim3 == 176) and ('t2_flair' in s.protocol_name):
            if (len(s.image_type) == 5) and (s.image_type[4] == 'NORM'):
                info[flairNorm] = [s.series_id]
            else:
                info[flair] = [s.series_id]
        if (s.dim4 == 105) and ('diff_cmrr' in s.protocol_name):
            info[dwi] = [s.series_id]
        if (s.dim4 == 1) and ('diff_cmrr' in s.protocol_name):
            info[dwiSbref] = [s.series_id]
        if (s.dim4 == 7) and ('diff_PA' in s.protocol_name):
            info[dwiPA] = [s.series_id]
        if (s.dim4 == 1) and ('diff_PA' in s.protocol_name):
            info[dwiPASbref] = [s.series_id]
        if (s.dim4 == 1058) and ('RS_fMRI_AP' in s.protocol_name):
            if s.image_type[2] == 'P':
                info[restPhase].append({'item': s.series_id})
        if (s.dim4 == 1058) and ('RS_fMRI_AP' in s.protocol_name):
            if s.image_type[2] == 'M':
                info[rest].append({'item': s.series_id})
        if (s.dim4 == 2) and ('RS_fMRI_AP' in s.protocol_name):
            info[restSbref].append({'item': s.series_id})
        if (s.dim4 == 6) and ('RS_fMRI' in s.protocol_name):
            if ('AP' in s.protocol_name):
                info[restAP].append({'item': s.series_id})
            elif ('PA' in s.protocol_name):
                info[restPA].append({'item': s.series_id})
        if (s.dim4 == 1) and ('RS_fMRI' in s.protocol_name):
            if ('AP' in s.protocol_name):
                info[restAPSbref].append({'item': s.series_id})
            elif ('PA' in s.protocol_name):
                info[restPASbref].append({'item': s.series_id})
        if (s.dim4 == 452) and ('petit_nicolas' in s.protocol_name):
            if s.image_type[2] == 'P':
                info[petitPhase].append({'item': s.series_id})
        if (s.dim4 == 452) and ('petit_nicolas' in s.protocol_name):
            if s.image_type[2] == 'M':
                info[petit].append({'item': s.series_id})
        if (s.dim4 == 2) and ('petit_nicolas' in s.protocol_name):
            info[petitSbref].append({'item': s.series_id})
        if (s.dim4 == 6) and ('petit_nicolas' in s.protocol_name):
            if ('AP' in s.protocol_name):
                info[petitAP].append({'item': s.series_id})
            elif ('PA' in s.protocol_name):
                info[petitPA].append({'item': s.series_id})
        if (s.dim4 == 1) and ('petit_nicolas' in s.protocol_name):
            if ('AP' in s.protocol_name):
                info[petitAPSbref].append({'item': s.series_id})
            elif ('PA' in s.protocol_name):
                info[petitPASbref].append({'item': s.series_id})
        if (s.dim4 == 406) and ('mapa_pinel' in s.protocol_name):
            info[pinel].append({'item': s.series_id})
        if (s.dim4 == 2) and ('mapa_pinel' in s.protocol_name):
            info[pinelSbref].append({'item': s.series_id})
        if (s.dim4 == 6) and ('mapa_pinel_' in s.protocol_name): 
            if ('AP' in s.protocol_name):
                info[pinelAP].append({'item': s.series_id})
            elif ('PA' in s.protocol_name):
                info[pinelPA].append({'item': s.series_id})
        if (s.dim4 == 1) and ('mapa_pinel_' in s.protocol_name): 
            if ('AP' in s.protocol_name):
                info[pinelAPSbref].append({'item': s.series_id})
            elif ('PA' in s.protocol_name):
                info[pinelPASbref].append({'item': s.series_id})         
                
    return info

**Comment by mainux** [comment]
Any news about this issue @mgxd ?

Thanks you for your answers and your time!

**Comment by mgxd** [comment]
@mainux are you able to share `IM-0035-0001.dcm`? If so, I could take a look.

If not, please rerun again (sorry for all these runs) with --minmeta and --dbg flags

**Comment by mainux** [comment]
Hi @mgxd!
I update again to the latest master branch, and the error just disappear, so thank you again!
