### ISSUE TITLE
IOError: json_ = json.load(open(json_phasediffname))

### ISSUE THREAD

**Issue by NikkiBytes** [nipy/heudiconv#122]
`IOError: [Errno 2] No such file or directory: '/test/output/eric_test/sub-07/fmap/sub-07_phasediff.json'
()
> /usr/local/bin/heudiconv(1169)tuneup_bids_json_files()
-> json_ = json.load(open(json_phasediffname))
`

Hey if someone could help me please, I see it is because my files are marked with a numeric...

`Singularity heudiconv.simg:/test/output/eric_test/sub-07> ls fmap
sub-07_magnitude.json	 sub-07_phasediff1.json    sub-07_phasediff2.json
sub-07_magnitude.nii.gz  sub-07_phasediff1.nii.gz  sub-07_phasediff2.nii.gz`

How do I specify this in the converter OR the command? Thank you. 

`def infotodict(seqinfo):
    # create directories
    # anat/
    t1 = create_key('anat/sub-' + subject+ '_T1w')

    # fmap/
    fmap_phase = create_key('fmap/sub-' + subject + '_phasediff')
    fmap_magnitude = create_key('fmap/sub-' + subject + '_magnitude')

    # func/
    milk = create_key('func/sub-' + subject + '_task-milkshake_B')

    noGo = create_key('func/sub-' + subject + '_task-Go_NoGo')

    info = {t1: [], fmap_phase: [], fmap_magnitude: [], milk: [], noGo: [] }

    for s in seqinfo:
        print(s)
        if (s.dim1 == 256) and ('t1' in s.protocol_name):
            info[t1].append(s.series_id)  ## append if multiple series meet criteria
        if (s.dim4 == 475 and s.is_motion_corrected == False ) and ('milkshake' in s.protocol_name):
            info[milk].append(s.series_id)  ## append if multiple series meet criteria
        if (s.dim4 == 195 and s.is_motion_corrected == False) and ('Go' in s.protocol_name):
            info[noGo].append(s.series_id)  ## append if multiple series meet criteria
        if (s.dim3 == 27) and ('field' in s.protocol_name):
            info[fmap_magnitude].append(s.series_id)  ## append if multiple series meet criteria
        if (s.dim3 == 54) and ('field' in s.protocol_name):
            info[fmap_phase].append(s.series_id)  ## append if multiple series meet criteria

    return info`

Here is what my command looks like.....

`heudiconv -b --dbg -ss 1 --overwrite -d /lab_data/{subject}/dicoms/wave1/dicoms/007/*.dcm -s eric_data -f /test/NIBL/ericdata_converter.py -c dcm2niix -b  -o /test/output/eric_test/sub-07`

**Comment by mgxd** [comment]
@NikkiBytes did you resolve this issue?

**Comment by NikkiBytes** [comment]
Hey @mgxd yes, it was a simple value error mixing up my magnitude and phasediff! Thank you!
