### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by mainux** [nipy/heudiconv#126]
Dear all, 

I'm running heudiconv on several subjects and it is running quite nice, but with one subject i got the following error:

INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': '09HBP0932S2', 'outdir': '/home/mtermenon/public/HBP_MaiteCesar/BIDS/', 'session': None}
INFO: Processing 9047 dicoms
INFO: Analyzing 9047 dicoms
Traceback (most recent call last):
  File "/opt/anaconda3/bin/heudiconv", line 2197, in <module>
    main()
  File "/opt/anaconda3/bin/heudiconv", line 2189, in main
    return _main(args)
  File "/opt/anaconda3/bin/heudiconv", line 2052, in _main
    min_meta=args.minmeta)
  File "/opt/anaconda3/bin/heudiconv", line 1364, in convert_dicoms
    grouping=None,  # no groupping
  File "/opt/anaconda3/bin/heudiconv", line 425, in group_dicoms_into_seqinfos
    assert studyUID == file_studyUID
AssertionError

Any idea?

Thanks in advance,

Maite

**Comment by mgxd** [comment]
@mainux sorry for the cryptic error - after #119 this was made more explicit. Heudiconv is finding 2 or more different sessions for that subject. You can work around this by specifying the session ([here's an example](https://github.com/nipy/heudiconv/issues/78#issuecomment-349709596))

**Comment by mainux** [comment]
Thank you for your answer @mgxd , but that is strange because there is only one session per subject in this experiment, so it is not possible that it is finding 2 or more.

**Comment by mgxd** [comment]
@mainux could you update your heudiconv version and rerun? The new error message will explicitly tell you which dicoms are conflicting

**Comment by mainux** [comment]
Hi @mgxd,

I've just followed the instructions of the website, I think it is in the latest version, and it shows exactly the same message, nothing new:
    
    [root@brodmann45 bin]# ./pip install
    https://github.com/nipy/heudiconv/archive/master.zip
    Collecting https://github.com/nipy/heudiconv/archive/master.zip
      Downloading https://github.com/nipy/heudiconv/archive/master.zip
         \ 102kB 294kB/s
      Requirement already satisfied (use --upgrade to upgrade):
    heudiconv==0.4 from
    https://github.com/nipy/heudiconv/archive/master.zs
    Requirement already satisfied: nibabel in
    /opt/anaconda3/lib/python3.6/site-packages (from heudiconv==0.4)
    Requirement already satisfied: pydicom in
    /opt/anaconda3/lib/python3.6/site-packages (from heudiconv==0.4)
    Requirement already satisfied: nipype in
    /opt/anaconda3/lib/python3.6/site-packages (from heudiconv==0.4)
    Requirement already satisfied: pathlib in
    /opt/anaconda3/lib/python3.6/site-packages (from heudiconv==0.4)
    Requirement already satisfied: scipy>=0.14 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: numpy>=1.9.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: networkx>=1.9 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: traits>=4.6 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: simplejson>=3.8.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: configparser in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: prov==1.5.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: future>=0.16.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: click>=6.6.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: packaging in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: pydot>=1.2.3 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: pydotplus in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: pytest>=3.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: mock in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: python-dateutil>=2.2 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: funcsigs in
    /opt/anaconda3/lib/python3.6/site-packages (from
    nipype->heudiconv==0.4)
    Requirement already satisfied: decorator>=4.1.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    networkx>=1.9->nipype->heudico)
    Requirement already satisfied: six>=1.9.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    prov==1.5.0->nipype->heudiconv==0.4)
    Requirement already satisfied: rdflib>=4.2.1 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    prov==1.5.0->nipype->heudiconv==0)
    Requirement already satisfied: lxml in
    /opt/anaconda3/lib/python3.6/site-packages (from
    prov==1.5.0->nipype->heudiconv==0.4)
    Requirement already satisfied: pyparsing in
    /opt/anaconda3/lib/python3.6/site-packages (from
    packaging->nipype->heudiconv==0.4)
    Requirement already satisfied: setuptools in
    /opt/anaconda3/lib/python3.6/site-packages (from
    pytest>=3.0->nipype->heudiconv==0.4)
    Requirement already satisfied: attrs>=17.2.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    pytest>=3.0->nipype->heudiconv==0)
    Requirement already satisfied: py>=1.5.0 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    pytest>=3.0->nipype->heudiconv==0.4)
    Requirement already satisfied: pluggy<0.7,>=0.5 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    pytest>=3.0->nipype->heudiconv)
    Requirement already satisfied: pbr>=0.11 in
    /opt/anaconda3/lib/python3.6/site-packages (from
    mock->nipype->heudiconv==0.4)
    Requirement already satisfied: isodate in
    /opt/anaconda3/lib/python3.6/site-packages (from
    rdflib>=4.2.1->prov==1.5.0->nipype->heu)
    [root@brodmann45 bin]#

**Comment by mgxd** [comment]
you'll have to do `pip install --upgrade https://github.com/nipy/heudiconv/archive/master.zip`

**Comment by yarikoptic** [comment]
@mainux success?

**Comment by mgxd** [comment]
closing - feel free to reopen

**Comment by yarikoptic** [comment]
if you had the same accession number specified, you could use `-g accession_number` to bring them together by accession number

**Comment by sjburwell** [comment]
Greetings, 

I have a similar issue to the above whereby heudiconv (docker implementation, 0.5.dev1) throws a conflicting study error (see below). For this participant/session, there was a system error and the console needed to be rebooted midway through the session. Thus, the scanning took place on the same day (and proximal in time, i.e., the same "session"), but the dicoms have different study identifiers. The accession_number for all dicoms is blank (i.e., ''), and when I tried using the above suggestion ("-g accession_number") it still seemed to be looking for "StudyInstanceUID". Any thoughts on whether I can 'trick' heudiconv into thinking this data comes from the same session?

Best,
Scott

Error::
Conflicting study identifiers found [1.3.12.2.1107.5.2.43.67010.30000015061717133439900000013, 1.3.12.2.1107.5.2.43.67010.30000015061722134788600000001]

**Comment by hcp4715** [comment]
I have the same problem as @thomshaw92 , 
`
AssertionError: Conflicting study identifiers found [1.2.276.0.38.1.1.1.5691.20180625154719.153078980, 1.3.12.2.1107.5.2.32.35333.30000018062607273992600000010].
`

Below is the folder structure of that day's data, still can not identify the two scans that conflict. Any suggestions? Thanks in advance.

![Screenshot from 2019-04-09 22-54-26](https://user-images.githubusercontent.com/7300419/55834546-7b742f80-5b1a-11e9-892c-61b2e2068e22.png)

**Comment by laurenbreithaupt** [comment]
@yarikoptic - I am looking for a workaround with multiple accession numbers (subjects break and come back). Can I group by multiple accession numbers using -g accesion_number?
