### ISSUE TITLE
Dockerimage Throwing Error Message

### ISSUE THREAD

**Issue by tjhendrickson** [nipy/heudiconv#127]
Hello,

I have been learning about heudiconv as I have interest in converting my dicom data into BIDS format. I'm able to convert my data just fine with the local heudiconv command line utility that I downloaded, however, the heudiconv docker image does not work. It will only convert the first image even though dicominfo.tsv, auto and edit text files generate all of the images. Additionally, while the docker image is running an error message is thrown relating to the docker image dcm2niix distribution: **Could not get linked libraries for "dcm2niix".** 

Any thoughts on this?

-Tim

**Comment by mgxd** [comment]
@tjhendrickson could you share a log of the command you ran/heudiconv's output?

re: linked libraries - this is a misleading warning that shouldn't affect things (this was fixed in nipy/nipype#2322 and will be gone once the next nipype release is out)

**Comment by mgxd** [comment]
closing this for now - feel free to reopen
