### ISSUE TITLE
IntendedFor field in json files

### ISSUE THREAD

**Issue by mainux** [nipy/heudiconv#138]
Hi! 
I am not able to find the IntendedFor field to specify in the fmaps  which run is intended to be used with which functional or diffusion scan.
Should it be added by hand?

Our case corresponds to the Case 4: Multiple phase encoded directions (topup) specified in the BIDS_spec.

Below I paste an example of the Json file of the fieldmaps corresponding to a task fMRI file.

Best,

Maite

```
{
  "AcquisitionNumber": 1,
  "AcquisitionTime": "14:40:22.670000",
  "BandwidthPerPixelPhaseEncode": 22.282,
  "BodyPartExamined": "BRAIN",
  "ConversionSoftware": "dcm2niix",
  "ConversionSoftwareVersion": "v1.0.20170724 GCC4.4.7",
  "DeviceSerialNumber": "167004",
  "EchoTime": 0.035,
  "EchoTrainLength": 88,
  "EffectiveEchoSpacing": 0.000509992,
  "FlipAngle": 56,
  "ImageType": [
    "ORIGINAL",
    "PRIMARY",
    "M",
    "MB",
    "ND",
    "MOSAIC"
],
  "InstitutionAddress": "Mikeletegi_69_San_Sebastian_District_ES_20009",
  "InstitutionName": "BCBL",
  "MagneticFieldStrength": 3,
  "Manufacturer": "Siemens",
  "ManufacturersModelName": "Prisma_fit",
  "PhaseEncodingDirection": "j-",
  "PhaseEncodingLines": 88,
  "ProcedureStepDescription": "CRANEO_FUNCIONAL",
  "ProtocolName": "petit_nicolas_1_AP",
  "RepetitionTime": 0.85,
  "ScanningSequence": "EP",
  "SequenceName": "epfid2d1_88",
  "SequenceVariant": "SK_SS",
  "SeriesDescription": "petit_nicolas_1_AP",
  "SliceTiming": [0, 0.4525, 0.075, 0.5275, 0.15, 0.6025, 0.225, 0.6775, 0.3025, 0.755, 0.3775, 0, 0.4525, 0.075, 0.5275, 0.15, 0.6025, 0.225, 0.6775, 0.3025, 0.755, 0.3775, 0, 0.4525, 0.075, 0.5275, 0.15, 0.6025, 0.225, 0.6775, 0.3025, 0.755, 0.3775, 0, 0.4525, 0.075, 0.5275, 0.15, 0.6025, 0.225, 0.6775, 0.3025, 0.755, 0.3775, 0, 0.4525, 0.075, 0.5275, 0.15, 0.6025, 0.225, 0.6775, 0.3025, 0.755, 0.3775, 0, 0.4525, 0.075, 0.5275, 0.15, 0.6025, 0.225, 0.6775, 0.3025, 0.755, 0.3775],
  "SoftwareVersions": "syngo_MR_E11",
  "TaskName": "petit",
  "TotalReadoutTime": 0.0443693}
```

**Comment by mgxd** [comment]
Hi @mainux - currently you'll have to add the `IntendedFor` entry yourself, although we plan on autogenerating this in the future

**Comment by mainux** [comment]
Ok thanks, no problem! 

It was driving me crazy ;) 

Maite Termenon 
Postdoctoral Researcher at BCBL 
Neurobiology of language group 
www.bcbl.eu 

Legal disclaimer/Aviso legal/Lege-oharra: www.bcbl.eu/legal-disclaimer

**Comment by oesteban** [comment]
hi @mgxd, any updates on this?

**Comment by mgxd** [comment]
@oesteban - I'm hoping to take a look at this next week, *in theory* it should doable (at least with Siemens)  - related to #148

**Comment by ChristianNSchmitz** [comment]
Hey @mgxd, is there any update on this feature? Thanks a lot!

**Comment by mirestrepo** [comment]
In case it's helpful, [this](https://github.com/brown-bnc/xnat-tools/blob/39d9bd2d9a2788df3305dd3d91d08c5101cf979d/xnat_tools/bids_utils.py#L14) is our work around, we do it as a post processing step
