### ISSUE TITLE
Unreliable performance with Philips data

### ISSUE THREAD

**Issue by mih** [nipy/heudiconv#14]
At this point, this is primarily a note for people coming here after having faced trouble.

Right now, dcmstack is not very reliable with Philips data. Dcmstack is used to sift through DICOMs and sort them into series. Especially with single image (no mosiac) DICOM it has trouble figuring out the dimensionality of volumetric images. Sometimes DICOMs get sorted wrongly so that dcm2nii subsequently refuses conversion.

This needs some attention.

**Comment by satra** [comment]
this is also true in some cases of siemens data. i haven't had the time to sort through the issues yet.

**Comment by moloney** [comment]
Could you guys provide examples when you get a chance?

**Comment by yarikoptic** [comment]
don't you all have a stash of QA DICOMs somewhere, @hanke, @satra ? ;)

I could provide from our old Philips, but they aren't very structured -- just some BOLD sequences while I was troubleshooting an artifact (unfortunately QA runs weren't dumped as DICOMs)

**Comment by chrisfilo** [comment]
This might help: https://www.nitrc.org/projects/rosetta/

**Comment by nicholsn** [comment]
Could also take a look at the Philips and Siemens phantoms on xnat central:
https://central.xnat.org/data/projects/DCMPHANTOM

**Comment by satra** [comment]
i'm not sure an entire protocol was scanned with those phantoms. they will definitely be useful for simply testing the conversion, but probably don't have enough diversity to test bids - perhaps those are two separate issues.

**Comment by neurolabusc** [comment]
@moloney you can find some recent samples here
 https://www.nitrc.org/plugins/mwiki/index.php/dcm2nii:MainPage#Diffusion_Tensor_Imaging
and historical samples here
 http://www.cabiatl.com/mricro/mricron/dcm2nii.html
I submitted them to Rosetta, so perhaps redundant with @chrisfilo

**Comment by mgxd** [comment]
https://neurostars.org/t/heudiconv-no-extraction-of-slice-timing-data-based-on-philips-dicoms/2201

**Comment by yarikoptic** [comment]
I think there were  a number of reports on successful conversion of philips data. Needless to say that most likely issues remain and should be addressed. But we would need more specific issues for them. And echoing last comment of @mgxd - I think there remains no slice timing data in Philips DICOMS to date, nothing heudiconv could do really (may be only recover the order)... in any case -- would need to be a separate issue(s).
