### ISSUE TITLE
File Ownership of Docker Outputs

### ISSUE THREAD

**Issue by tjhendrickson** [nipy/heudiconv#152]
Hello,

When I use the heudiconv docker image to convert my data to BIDS I get back files that are owned by root. This is a big problem considering I work on a cluster and do not have root user privileges. How do I change/prevent this?

Thanks!

**Comment by yarikoptic** [comment]
they allow you to run docker on the cluster? yikes
ask them to install singularity, then you would be able to use it on the cluster and avoid 
There will come a dedicated singularity image soon for https://github.com/repronim/reproin but meanwhile you could either compose one based on that Singularity file or just use shub://neurodebian generic one for starters -- should largely have everything I believe

**Comment by tjhendrickson** [comment]
I ended up just downloading and implementing the image in udocker. This resulted in the intended file ownership behavior. 

Thanks for your help!
