### ISSUE TITLE
Question about different echo time for one serie

### ISSUE THREAD

**Issue by gregblt** [nipy/heudiconv#158]
Hi, 

I am curious about the behavior of heudiconv and your position concerning the following situation:

I have a situation where I got two different echo times for a single DICOM serie. This happened with the siemens fieldmap sequence fm2d2r which produces two series : one whit the two magnitude scans - one for each echo time - and one with the phase difference.

First I tried to use the echo time to get my two nifti files with the proper magnitude1 and magnitude2 key but it was not working as heudiconv was offering me only one echo time for the whole serie.

I have been able to deal with this in order to get my dataset in the BIDS format. However I was wondering how heudiconv deals with this kind of case ? For example in the dicominfo.tsv, I see that there is only one line for this serie, showing me only one echo time.

I was wondering if it could be better to have two lines, one for each echo time. Or one line for each parameter diverging in the serie in a more general way.

And thank you for this great tool!

Best,

Grégory Bliault

**Comment by rmarkello** [comment]
I just wanted to +1 this as I recently encountered a similar problem with both joint PD-T2 and dual-echo T2 scans! `dcm2niix` defaults to creating multiple niftis for the different acquisition parameter sequences in a scan/series, but `heudiconv` simply labels those as {bids_prefix}1.nii.gz and {bids_prefix}2.nii.gz. I agree it would be great to be able to differentiate them in the heuristic based on TE/TR!

**Comment by pvelasco** [comment]
The heuristics only classifies the different series into the corresponding categories.  So if the scanner saves the two echoes as a single series (as `dicominfo.tsv` reveals), that DICOM series will be classified as one category (e.g., `fmap_gre_magnitude`).  Then, when the conversion into NIfTI happens, `dcm2niix` splits it into two different NIfTI files, because they have different echoes.  The naming of those two echoes are handled by the function `save_converted_files`, in `convert.py`.
If you want to modify the naming of the NIfTI files (and corresponding `.json`) you will have to do it in the function `save_converted_files`.

For example, for the magnitude images in the field map (@gregblt), if you wanted to name them `...magnitude_echo-1` and `...magnitude_echo-2` (I know: they will not be BIDS compliant, but it's just an example):

```
        for fl, suffix, bids_file in zip(res_files, suffixes, bids_files):
            # Instert the following:    -----
            if ( bids and ('fmap/' in prefix) and ('magnitude' in prefix) ):
                outname = "%s_echo-%s.%s" % (prefix, suffix, outtype)
            else:
                outname = "%s%s.%s" % (prefix, suffix, outtype)
            # -------
            safe_copyfile(fl, outname, overwrite)
```

Another example, for the PD-T2 scans (@rmarkello), if your heuristics puts the series into a category with name `..._PDT2`, and you want to add `_mod-PD` and `_mod-T2` before `_PDT2`, assuming the first image is the PD and the second the T2, you could do:

```
        for fl, suffix, bids_file in zip(res_files, suffixes, bids_files):
            # Instert the following:    -----
            if ( bids and (prefix[-5:] == '_PDT2') ):
                if   (suffix == '1'):
                    outname = "%s_mod-%s%s.%s" % (prefix[:-5], 'PD', '_PDT2', outtype)
                if   (suffix == '2'):
                    outname = "%s_mod-%s%s.%s" % (prefix[:-5], 'T2', '_PDT2', outtype)
                else:
                    outname = "%s_mod-%s%s.%s" % (prefix[:-5], 'Unknown', '_PDT2', outtype)
            else:
                outname = "%s%s.%s" % (prefix, suffix, outtype)
            # -------
            safe_copyfile(fl, outname, overwrite)
```


(Note: you could modify your heuristics to include your FM_mag into two different categories (e.g., `fmap_gre_magnitude1` and `fmap_gre_magnitude2`).  But then `dcm2niix` will spit out two NIfTI files in each of the categories, which is not what you want.)

**Comment by gregblt** [comment]
Thank you @pvelasco for this solution, this will work for this use case and provide me a way of dealing with different nifti for one dicom series in the future

Behind this multiple echo time problematic I was also concern about the grouping and compression of the DICOM files. We are working on the study import functionality of our virtual laboratory and while discussing with a collegue he told me that it would be better to not split the DICOMs by series but by the number of nifti files produced (ideally, one group of DICOM files = one nifti file + one json file). That is why I was interested into a dicominfo.tsv files showing if necessary more than one line for a single DICOM series if parameters are changing. But I guess there is situations where you want to keep the series grouped in one chunk because even if there have differents parameters they are somehow related, being in the same series.

So I could go with your solution and then make some post processing on the DICOM .tgz provided by heudiconv using the diverging echo time shown in the .JSON files to split the content of the tarball

**Comment by rmarkello** [comment]
Indeed, thanks @pvelasco! I decided to co-opt `custom_callable()` in the heuristics file to sanitize my outputs, so as to avoid editing the codebase directly. 

Would you be open to a PR to add some documentation on this? It seems like there are a lot of options for the heuristic file that might be nice to document somewhere!

**Comment by emdupre** [comment]
I just also wanted to jump in here and +1 these questions. I do have a bit of a more direct issue, though&mdash; there are BIDS-compliant multi-echo fMRI data sets for which we would expect to see an `_echo-` field but are instead getting clobbered into runs; e.g., https://openfmri.org/dataset/ds000258/. It looks like these data sets were previously supported (https://github.com/nipy/heudiconv/pull/40), but don't seem to be any longer. 

Should I open a new issue to start considering heudiconv support for multi-echo fMRI?

**Comment by satra** [comment]
@emdupre - a new issue would be great. more importantly, if a small phantom dataset could be made available, that would help a lot. we should perhaps have mutli echo,  multi flip angle, multi inversion pulse. i'll ask folks here to see if we can generate something of that nature.

**Comment by yarikoptic** [comment]
A phantom dataset would indeed be very much appreciated! If you could also name sequences using reproin heuristic convention, would be double awesome!

**Comment by emdupre** [comment]
Thanks ! I opened #162 to continue this conversation. I'm not immediately able to access a multi-echo phantom but I'll ask around and see what I can do !

**Comment by mgxd** [comment]
@emdupre if you have access to any multi-echo sequences, we would love to have some more testing on #293 if you're willing to give it a chance :smile:

**Comment by yarikoptic** [comment]
yes, please @emdupre , without your blessing this functionality will miss the next point release! ;)

**Comment by emdupre** [comment]
I don't have access to those dicoms, unfortunately, but I asked @handwerkerd, and he's looking into it !
