### ISSUE TITLE
Support for multi-echo fMRI

### ISSUE THREAD

**Issue by emdupre** [nipy/heudiconv#162]
In the current BIDS spec, we have support for multi-echo fMRI data sets, like https://openfmri.org/dataset/ds000258/.  However, heudiconv seems to be outputting the different echoes as individual runs, rather than recognizing that all echoes belong to the same run. This will make interfacing with downstream multi-echo tools like https://github.com/poldracklab/fmriprep/pull/891 problematic.

Is there a preferred path for tackling this issue? I don't have a multi-echo phantom, but am happy to contribute code.

**Comment by yarikoptic** [comment]
checked with our physicist, he believes we do not have EPI multi-echo sequences, but we have some other double-echo one.  He will collect a sample phantom dataset on monday, but still would be neat to get proper (but minimlistic -- the smallest matrix, # of volumes, etc) EPI multi-echo phantom data ;)

**Comment by yarikoptic** [comment]
here is a sample of multi-echo (non-EPI) sequence which collects both PD and T2w in one shot
http://datasets.datalad.org/?dir=/dicoms/dartmouth-phantoms/bids_test6-PD+T2w/ . You can get it via `datalad install ///dicoms/dartmouth-phantoms/bids_test6-PD+T2w/`
(note that I am only about to fix us not url unquoting that + in the url, so you might get "%2B" in the resultant directory name)

**Comment by emdupre** [comment]
Pinging @rmarkello here who has been working on a solution for this use case.

**Comment by rmarkello** [comment]
Thanks for providing an open test set, @yarikoptic! A couple of questions about implementation:

1. Would it be reasonable to provide individuals with information in the `dicominfo.tsv` files noting that the sequence is multi-echo (e.g., making the TE entry a list if multiple echo times exist)?
2. Is it fair to simply inject the `echo-<index>` key-value pair into the `template` provided in the heuristic file if a given sequence is multi-echo (and BIDS output is desired), or should an additional template field be provided for use in the heuristic under the assumption that users will specify it if they want it differentiated?

**Comment by leej3** [comment]
Just wondering has anyone done anything further on this? I was hoping to use this functionality. Happy to help try and implement it.
If i run heudiconv on multi-echo scans from siemens i get the behaviour as described above (" heudiconv seems to be outputting the different echoes as individual runs"). If those numbers were incorporated in the template that would be sufficient. I don't know if they are guaranteed to correspond though. I haven't spotted how they are generated. 
From what I can tell the echo would have to be extracted differently across vendors. In siemens it is encoded in the directory name eg "mr002-e04" for the fourth echo. GE's contain  the info in a dicom tag. Would I be correct in assuming that this should be added to seqinfo in the group_dicoms_into_seqinfos function somewhere around line 160 and that is where I should focus my efforts?

**Comment by yarikoptic** [comment]
FTR (for myself), the bible (BIDS 1.1.0) says about multi echo
```
Multi echo data MUST be split into one file per echo. Each file shares the same name with the exception
of the _echo-<index> key/value. For example:

sub-01/
func/
sub-01_task-cuedSGT_run-1_echo-1_bold.nii.gz
sub-01_task-cuedSGT_run-1_echo-1_bold.json
sub-01_task-cuedSGT_run-1_echo-2_bold.nii.gz
sub-01_task-cuedSGT_run-1_echo-2_bold.json
sub-01_task-cuedSGT_run-1_echo-3_bold.nii.gz
sub-01_task-cuedSGT_run-1_echo-3_bold.json

Please note that the <index> denotes the number/index (in a form of an integer) of the echo not the echo 
time value which needs to be stored in a separate JSON file (see below).
```

For Siemens `dcm2niix` already provides a field within (second) side-car .json about having the second/different EchoTime:

```shell
(git-annex)hopa:…mouth-phantoms/bids_test6-PD+T2w[master]005-anat-PD+T2w_acq-tse-tra-3mm
$> dcm2niix -bids .
Chris Rorden's dcm2niiX version v1.0.20171215 (OpenJPEG build) GCC7.2.0 (64-bit Linux)
Error: Unknown command line argument: '-bids'
Found 70 DICOM image(s)
slices not stacked: echo varies (TE 9.4, 94; echo 1, 2). Use 'merge 2D slices' option to force stacking
Convert 35 DICOM as ./func (640x640x35x1)
compress: "/usr/bin/pigz" -n -f -6 "./func.nii"
slices not stacked: echo varies (TE 94, 9.4; echo 2, 1). Use 'merge 2D slices' option to force stacking
Convert 35 DICOM as ./func_e2 (640x640x35x1)
compress: "/usr/bin/pigz" -n -f -6 "./func_e2.nii"
Conversion required 2.235244 seconds (0.122623 for core code).
dcm2niix -bids .  5.90s user 0.18s system 271% cpu 2.244 total
(dev3) 1 17216.....................................:Mon 30 Apr 2018 11:02:16 AM EDT:.
(git-annex)hopa:…mouth-phantoms/bids_test6-PD+T2w[master]005-anat-PD+T2w_acq-tse-tra-3mm
$> lst
total 20236
-rw------- 1 yoh yoh 10058801 Apr 30 11:02 func_e2.nii.gz
-rw------- 1 yoh yoh     1774 Apr 30 11:02 func_e2.json
-rw------- 1 yoh yoh 10357716 Apr 30 11:02 func.nii.gz
-rw------- 1 yoh yoh     1757 Apr 30 11:02 func.json
lrwxrwxrwx 1 yoh yoh      129 Apr 30 11:00 000051.dcm -> ../.git/annex/objects/0G/3G/MD5E-s957320--6b7aa43ebbed98d08bc2c5632ff7a4ac.dcm/MD5E-s957320--6b7aa43ebbed98d08bc2c5632ff7a4ac.dcm
lrwxrwxrwx 1 yoh yoh      129 Apr 30 11:00 000052.dcm -> ../.git/annex/objects/p2/Wq/MD5E-s957316--091e3dac2ab9198670cadf89d182d988.dcm/MD5E-s957316--091e3dac2ab9198670cadf89d182d988.dcm
lrwxrwxrwx 1 yoh yoh      129 Apr 30 11:00 000053.dcm -> ../.git/annex/objects/x4/v1/MD5E-s957318--3c6cc1e73977c03ba2b252ccc64e1b28.dcm/MD5E-s957318--3c6cc1e73977c03ba2b252ccc64e1b28.dcm
lrwxrwxrwx 1 yoh yoh      129 Apr 30 11:00 000054.dcm -> ../.git/annex/objects/4w/5f/MD5E-s957318--988c4097e62794aed20ced49082d0f6e.dcm/MD5E-s957318--988c4097e62794aed20ced49082d0f6e.dcm
lrwxrwxrwx 1 yoh yoh      129 Apr 30 11:00 000055.dcm -> ../.git/annex/objects/m9/gq/MD5E-s957316--0809b00a3f87cb7150ba0d3625baf0ce.dcm/MD5E-s957316--0809b00a3f87cb7150ba0d3625baf0ce.dcm
(dev3) 1 17217.....................................:Mon 30 Apr 2018 11:02:18 AM EDT:.
(git-annex)hopa:…mouth-phantoms/bids_test6-PD+T2w[master]005-anat-PD+T2w_acq-tse-tra-3mm
$> diff func.json func_e2.json 
23c23
< 	"AcquisitionTime": "09:32:3.255000",
---
> 	"AcquisitionTime": "09:32:3.302500",
28c28,29
< 	"EchoTime": 0.0094,
---
> 	"EchoNumber": 2,
> 	"EchoTime": 0.094,
```
so it should be sufficient for heudiconv to load those to deduce that the sequence is multiecho and add suffix accordingly.  @leej3 - how does dcm2niix behaves for you?  any chance to get some dummy/phantom scans?  would be great to contribute to dcm2niix' dcm_qa: https://github.com/neurolabusc/dcm_qa/issues/8

**Comment by leej3** [comment]
I'll try get my hands on a phantom scan and upload it.

A recent version of dcm2niix (v1.0.20180325 GCC6.3.0) gets the echo number correctly.

When you add suffix accordingly you mean changing sub-01_task-cuedSGT_run-1_bold.nii.gz to sub-01_task-cuedSGT_run-1_echo-1_bold.nii.gz yes?

That's a little confusing for the user who has likely specified something like:

**Comment by smoia** [comment]
Hello,
I tried to use the latest pip version of heudiconv (0.5.4.dev1, after #293 had been merged) to convert a Multi-Echo dataset that I'm acquiring now from DICOMs to BIDS format.
I used the following command:
`heudiconv -d /experiment/{subject}/acq/*/* -s 001 -c none -o MEBIDS -f bids_ME -b --minmeta --overwrite`

Each each folder (one per run) in "acq" contains all the DICOMS from all the echoes of a run. The DICOMS are collected with a Siemens Prisma.
I think I'm making a mistake, because the heuristic file doesn't contain one file per echo time per run, but just one file per run, with dim4 equal to the number of echoes * the number of TRs.

Am I forgetting a flag, or a file to input? I didn't see anything in the `--help` or in the documentation here on GitHub.

Thank you!

**Comment by mgxd** [comment]
@smoia we haven't pushed a new release yet, so you will have to install directly from the master branch:
`pip install -U  https://github.com/nipy/heudiconv/archive/master.zip`

FYI, I would recommend making your own heuristic instead of using the `bids_ME` premade heuristic - it is tailored to some specific data and probably will not work with yours. And also specifying `-c none` will only group the DICOMs, but not convert to NIfTI.

**Comment by smoia** [comment]
Thank you @mgxd,
To update, I actually used the command:
`pip install https://github.com/nipy/heudiconv/archive/master.zip --upgrade`
I know that `-c none` doesn't do the actual conversion, but I thought that I could modify the heuristic file after seeing the content of `.heudiconv/{subject}/info/dicominfo.tsv`. which is what I was trying tot create with my line of code.
Sorry for not having been clear enough in the previous post.

**Comment by mgxd** [comment]
Ah, okay! Yes, currently the dicominfo will show one row across a ME acquisition, with dim4 as being number of echoes * volumes like you said. 

What #293 did is if the `--bids` option is specified, it will automatically add the `_echo-<>` field to your heuristic key across all echoes. So you wouldn't have to specify <echo> directly (see the [bids_ME heuristic](https://github.com/nipy/heudiconv/blob/master/heudiconv/heuristics/bids_ME.py) for an example). We haven't extensively tested this due to lack of ME data, so it'd be nice to hear how it works on your data!

**Comment by smoia** [comment]
I see! Ok, then I'll try to continue with the test. By the way, I can provide some ME fMRI data if somebody else wants to test it too.

Thank you again!

**Comment by mgxd** [comment]
@smoia did you manage to test the ME support on your data?

**Comment by yarikoptic** [comment]
I think multi-echo is supported by heudiconv 0.6.0 now, thus closing.  Please reopen if I am wrong.
