### ISSUE TITLE
Docker app can't mount local folder?

### ISSUE THREAD

**Issue by hcp4715** [nipy/heudiconv#175]
Dear developers,

I am a beginner of python, and try to use heudiconv to convert my row data to BIDS. It seems that there is something wrong when I try to mount the local folder when running the docker image:

Below is the code:
> PS C:\WINDOWS\system32> docker run -it --rm -v G:\Data\coiltest\analysis:/home/data nipy/heudiconv:latest

When I first run this code, there was a dialogue requires me to input password, though I've no idea which password it meant to. So I tried a few, and then the window disappeared. then comes  the following information:
> INFO: Running heudiconv version 0.5.dev1
> Traceback (most recent call last):
>   File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
>     load_entry_point('heudiconv==0.5.dev1', 'console_scripts', 'heudiconv')()
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 120, in main
>     process_args(args)
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 240, in process_args
>     heuristic = load_heuristic(args.heuristic)
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/utils.py", line 274, in load_heuristic
>     if os.path.sep in heuristic or os.path.lexists(heuristic):
> TypeError: argument of type 'NoneType' is not iterable

To test whether or not is the problem of docker, I tried same code:
> docker run -it --rm -v G:\Data\coiltest\analysis:/home/data neurodebian:stretch-non-free

It works.

So I guess it may be a bug of heudiconv. It would great if you can help me to solve this problem. I really want to use the whole python package to process my coming experimental data!

Cheers
Chuan-Peng

**Comment by mgxd** [comment]
Hi Chuan-Peng,

Looks like you are not passing in any arguments to the heudiconv script, at the bare minimum you'll need:

```
1a) -d /path/to/{subject}/dicoms/*.dcm and -s SUBJECT_ID
OR
1b) --files /path/to/files
AND
2) -f convertall
```
this will tell heudiconv where to find your DICOMs and how to convert them. There are some example slides [here](http://nipy.org/workshops/2017-03-boston/lectures/bids-heudiconv/#12) that may help.

**Comment by mgxd** [comment]
@hcp4715 feel free to reopen if you have additional questions

**Comment by hcp4715** [comment]
Hi, Mathias, @mgxd,
sorry for the delayed response.
I checked slides, and to be honest, they are not so straight for me.

For example, in the 12th slide, it said "Start out running heudiconv without any converter, just passing in DICOMs."   My understanding is that this code will only read the dicom file and don't do anything else, so I tried this:

> docker run --rm -it -v G:\Data\coiltest\heudiconv:/home/data:ro -v G:\Data\coiltest\heudiconv:/h
ome/output nipy/heudiconv:latest

but the error still occured:
![_20180316184603](https://user-images.githubusercontent.com/7300419/37536262-57bf0b76-294a-11e8-9195-11f092a6009f.png)
