### ISSUE TITLE
assertion failure in json_dumps_pretty

### ISSUE THREAD

**Issue by leej3** [nipy/heudiconv#182]
I have a SeriesDescription that is causing the following assertion to fail:
assert j_just_reloaded == j_tuned

js['SeriesDescription'] is fine (it contains underscores) but js['global']['const']['SeriesDescription'] has spaces:
"SeriesDescription": "Trace:Nov 13 2017 14-36-14 EST"

And is altered to:
 "SeriesDescription": "Trace:Nov 132017 14-36-14EST"

The regex doing this is:
js_ = re.sub('  *("?[-+.0-9e]+"?)[ \n]*', r' \1', js_)

**Comment by yarikoptic** [comment]
thanks @leej3 ! so my regex foo failed me there with this record.  I will try to fix it up now (may be would need to add some more unittests to not ruin what it was doing before ;) )

**Comment by leej3** [comment]
regex foo eh? more like black magic!
