### ISSUE TITLE
excessive conversions

### ISSUE THREAD

**Issue by mgxd** [nipy/heudiconv#188]
In cases where all DICOMs are lumped together in the same directory, the entire dataset is being converted multiple times, since we are looping across series https://github.com/nipy/heudiconv/blob/4eff1a663fb562dabd00fc3b470204c7f2097aaf/heudiconv/convert.py#L235 and yet passing in all DICOMs each time https://github.com/nipy/heudiconv/blob/4eff1a663fb562dabd00fc3b470204c7f2097aaf/heudiconv/convert.py#L393-L397 Introduced in #185, patch in progress.

**Comment by chpiero** [comment]
Is it possible to have an updated version of the docker container? What I see is 16 days ago while the fix is 4 days ago. Also on git hub there is an old version of the convert.py file

**Comment by chpiero** [comment]
Sorry but the fix doesn't work

**Comment by mgxd** [comment]
closed in #207
