### ISSUE TITLE
Heudiconv not detecting multiple runs of same kind of scan, only converting one of them. 

### ISSUE THREAD

**Issue by krsimon109** [nipy/heudiconv#190]
Hi, I am using heudiconv version 0.4 with the following heuristic (am not running from docker): 

for s in seqinfo:

	if 'number' in s.protocol_name:
	    info[task].append(s.series_id)

The command I am using is: 

heudiconv -d '{subject}/*.dcm' -s ${SUB} -f heuristic.py -c dcm2niix -b -o ${NIFTI_DIR}

If I have multiple series with 'number' in the protocol name, my heudiconv command is only converting one of the dicom series, and not the other with the same protocol name. I am told that it should convert both when this happens, but this is not happening. 

I have attached the dicom info file here. Let me know if other information is needed, thanks! 
[dicominfo.txt](https://github.com/nipy/heudiconv/files/1907857/dicominfo.txt)

**Comment by mgxd** [comment]
@krsimon109 could you share `heuristic.py`?

**Comment by krsimon109** [comment]
Attached as txt file

[heuristic.txt](https://github.com/nipy/heudiconv/files/1908399/heuristic.txt)

**Comment by mgxd** [comment]
@krsimon109 
It looks like you aren't specifying runs for your nback task

```python
task = create_key('sub-{subject}/func/sub-{subject}_task-nback_run-{item}_bold')
```

Could you make the change above to your heuristic and then retry the conversion (You will have to clear the hidden `.heudiconv` in your output folder first)?

**Comment by mgxd** [comment]
@krsimon109 were you able to multiple series?

**Comment by krsimon109** [comment]
@mgxd Yes! Sorry for the late confirmation. Thank you!
