### ISSUE TITLE
heudiconv demonstration video

### ISSUE THREAD

**Issue by jdkent** [nipy/heudiconv#193]
I made a video to help out with a monthly mri methods meeting, and since someone else (not from my university) found the video helpful, I was wondering if it would be useful to link the video somewhere in the documentation.

[my heudiconv example](https://www.youtube.com/watch?v=O1kZAuR7E00)

P.S. I apologize for the probable mispronunciations of your names

**Comment by yarikoptic** [comment]
Lovely! thank you @jdkent , we definitely should point to it (to close this issue).

- FYI, if you would like to prepare screencasts I would "promote" to use our "casting" helpers we use for datalad project (you are welcome to "fix" https://github.com/datalad/datalad/issues/1778 ) to 
  1. amuse your audience with your super-fast and consistent typing skills ;)
  2. have it "preprogrammed" for you so you could just follow the notes
  3. render it to asciiart etc
  
  See example eg at https://www.youtube.com/watch?v=sDP1jhRkKRo&t=2170s

- On Ubuntu you do not have to use dockerized version, and could either
  - use it natively (`apt-get install heudiconv` after `apt-get install neurodebian; apt-get update; heudiconv ...`)
  - use it via singularity (`apt-get install singularity-container; singularity pull docker://nipy/heudiconv`, `./heudiconv.simg ...`).

**Comment by jdkent** [comment]
Awesome, Thanks for the feedback. :) My only rationale for using docker on linux is that ideally the same steps could be used for windows or mac users, but I should have mentioned the other methods available to linux users. Forgive my ignorance, but what software exactly do you use for "casting" helpers? Is it a datalad feature that I can use?
