### ISSUE TITLE
Heuristic's `infotoids` is required with `--files`, but effectively isn't

### ISSUE THREAD

**Issue by mih** [nipy/heudiconv#197]
If I give `--files` I get a ValueError if the selected heuristic doesn't provide an `infotoids()` function. However, looking at the actual code path heudiconv is capable of overriding each of `subject`, `session`, `locator` via cmdline args (those are the bits reported by that funcion). So the test should rather be do I have this info, than crash if there is no such function.

**Comment by bpoldrack** [comment]
FTR: I built an heuristic (https://github.com/bpoldrack/heudiconv/blob/cbbs-imaging/heudiconv/heuristics/cbbs.py) and all it lacked to work with `--files` was indeed:

```python
def infotoids(seqinfos, outdir):
    return {'locator': None,
            'session': None,
            'subject': None}
```

Just confirming, that "looking at the code" wasn't somehow misleading.

**Comment by mgxd** [comment]
this was expanded in #293. `--files` doesn't require `heuristic.infotoids()` as long as one (and only one) `--subjects` is passed along as well
