### ISSUE TITLE
Remove old BIDS heuristic

### ISSUE THREAD

**Issue by chrisfilo** [nipy/heudiconv#20]
This is out of date I believe: https://github.com/nipy/heudiconv/blob/master/heuristics/bids_of_jan.py and has been superseded by https://github.com/nipy/heudiconv/blob/master/heuristics/bids_no_ses.py and https://github.com/nipy/heudiconv/blob/master/heuristics/bids_with_ses.py. Any objections?

**Comment by satra** [comment]
+1 for removal - @hanke and i used to joke about bids of the day (botd) !

**Comment by chrisfilo** [comment]
I hope things will remain much more stable since 1.0.0.
