### ISSUE TITLE
Is heudiconv supposed to copy the source files into the target directory?

### ISSUE THREAD

**Issue by tedstrauss** [nipy/heudiconv#211]
Going through the sample heuristics, I don't see what part triggers the copying of source files to the target file hierarchy. Am able to execute heuristics that create metadata files, but source files are not being copied.

**Comment by yarikoptic** [comment]
`infotodict` returned entries carry a field which states what to keep `('nii.gz',)` for just niftis, and `('nii.gz', 'dicom')` for both
