### ISSUE TITLE
0.5.1 release?

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#219]
I think we should kick out the new release, since there were a number of fixes added since 0.5.  I hope we didn't break much - tested locally using the utils/test-compare-two-versions.sh on a sample phantom dataset -- seems to be Ok'ish, so I guess we could state it to be a bugfix release ;-)

What do you think @satra , @mgxd ? anything you would like to add to the release?

TODOs
- [ ] Changelog

**Comment by mgxd** [comment]
we're long overdue for a release so I'm okay with this - I do want to prioritize #116 for next release though

**Comment by mgxd** [comment]
I can generate the changelog (let's get #225 / #224 in first) and then release is all yours ;)
