### ISSUE TITLE
SyntaxError: unqualified exec [Centos 7 - Python 2.7.5]

### ISSUE THREAD

**Issue by dorianps** [nipy/heudiconv#222]
Trying to install for the first time, getting the error below. A couple of other issues here mention this error, but the solution was for Ubuntu only. I also checked online and looks like this bug is fixed in python 2.7.9. The issue is that upgrading python can be problematic in linux, and I am not sure how heudiconv would work if installed on a specific python version whyle the standard `python` call will use the old version. Any idea how to make this work?

```
[root@mri dorian]# umask 0022
[root@mri dorian]# PREFIX_PATH=/APPS/
[root@mri dorian]# pip install --install-option="--prefix=$PREFIX_PATH" heudiconv[all]
/usr/lib/python2.7/site-packages/pip/_internal/commands/install.py:199: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting heudiconv[all]
  Using cached https://files.pythonhosted.org/packages/93/1b/3f866ddbf6af150ec94117ae5ddebf1c5584468d991345692fddf6224809/heudiconv-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-70IlXr/heudiconv/setup.py", line 22
        exec(infofile.read(), globals(), ldict)
    SyntaxError: unqualified exec is not allowed in function 'main' it contains a nested function with free variables

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-70IlXr/heudiconv/
```

**Comment by yarikoptic** [comment]
if it is just a matter of getting a newer python environment, I would recommend to try `conda` distribution (anaconda or miniconda).
But ideally, I would recommend to install http://singularity.lbl.gov , and then you could get a complete environment via `singularity pull shub://ReproNim/reproin`, which is our https://github.com/repronim/reproin bundle of heudiconv

**Comment by yarikoptic** [comment]
BUT having said that, we could workaround this ugly bug in elderly pythons with smth like
```
-        exec(infofile.read(), globals(), ldict)
+        eval(compile(infofile.read(), '<string>', 'exec'), globals(), ldict)
```
but I wonder if we should

**Comment by dorianps** [comment]
So far, I've installed python 2.7.15 side by side with 2.7.5, although pip is still insisting in using the old version. Will need to tell it to use the new one when installing heudiconv, but I am not sure after all that heudiconv will call the right python. Will need to give it a try.

Understanding how to manage Conda has been on my to do list for a while. Maybe this is the right occasion to do it. But I still think that a fix in `heudiconv` would be the best option for users. Dealing with python versions and conda is not easy for new users.

Thanks @yarikoptic

**Comment by yarikoptic** [comment]
side-by-side python installation generally is a recipe for a disaster, unless may be just using virtualenv to provide some kind of encapsulation around the environment.  conda is one of those ways.

Did you try aforementioned patch (if you just git clone this repository, do the change, and then do you `pip install ` but pointing to that directory)?

**Comment by dorianps** [comment]
Thanks @yarikoptic , the workaround seem to complete well, although I had a bunch of other problems for updating some basic packages which I did manually (see below).

Now that `heudiconv` is installed, how can I try if it's installed properly. The slides and youtube video only show the docker example.


```
1000  git clone https://github.com/nipy/heudiconv.git
 1001  cd heudiconv/
 1002  ls
 1003  gedit setup.py
 1004  xauth add $(xauth -f /home/dorian/.Xauthority list|tail -1)
 1005  gedit setup.py
 1006  cd ..
 1008  PREFIX_PATH=/APPS/
 1009  umask 0022
 1010  PREFIX_PATH=/APPS/
 1011  pip install --install-option="--prefix=$PREFIX_PATH" ./heudiconv/
 1012  heudiconv
 1013  pip update six
 1014  pip install six upgrade
 1015  python
 1016  pip install six --upgrade
 1017  pip install numpy --upgrade
 1018  pip install --install-option="--prefix=$PREFIX_PATH" ./heudiconv/
 1019  pip install numpy --upgrade
 1020  pip install numpy --ignore-installed --upgrade
 1021  pip install --install-option="--prefix=$PREFIX_PATH" ./heudiconv/
 1022  yum install lapack-devel blas-devel
 1023  pip install --install-option="--prefix=$PREFIX_PATH" ./heudiconv/
 1024  pip install scipy
 1025  pip install --install-option="--prefix=$PREFIX_PATH" ./heudiconv/
 1026  yum install python-devel
 1027* pip install
 1028  pip install pyparsing --ignore-installed --upgrade
 1029  pip install --install-option="--prefix=$PREFIX_PATH" ./heudiconv/
```

At the end seems all ok:

```
  Running setup.py install for nibabel ... done
  Running setup.py install for pydicom ... done
  Running setup.py install for decorator ... done
  Running setup.py install for networkx ... done
  Running setup.py install for python-dateutil ... done
  Running setup.py install for traits ... done
  Running setup.py install for future ... done
  Running setup.py install for isodate ... done
  Running setup.py install for rdflib ... done
  Running setup.py install for prov ... done
  Running setup.py install for click ... done
  Running setup.py install for py ... done
  Running setup.py install for attrs ... done
  Running setup.py install for more-itertools ... done
  Running setup.py install for atomicwrites ... done
  Running setup.py install for pluggy ... done
  Running setup.py install for pytest ... done
  Running setup.py install for pydotplus ... done
  Running setup.py install for pydot ... done
  Running setup.py install for packaging ... done
  Running setup.py install for nipype ... done
  Running setup.py install for pathlib ... done
  Running setup.py install for heudiconv ... done
Successfully installed atomicwrites attrs click decorator future heudiconv isodate more-itertools networkx nibabel nipype packaging pathlib pluggy prov py pydicom pydot pydotplus pytest python-dateutil rdflib traits
```

**Comment by dorianps** [comment]
Never mind my previous question. I reinstalled heudoconv in the default python folder and it works. It was my misunderstanding that heudiconv would be a separate application, instead it ended up installing on my /APPS folder all the required python packages including itself.

Thanks @yarikoptic .

**Comment by yarikoptic** [comment]
the problem is that it requires patched dcmstack, so requirements.txt points to git+git://github.com/mvdoc/dcmstack@bf/importsys   and setup.py can't point to git repos afaik.. and dcmstack wouldn't be needed if you use `--minmeta`...  we should revisit necessity to use it and having it updated.
FWIW on (Neuro)Debian we provide patched version so everything works out of the box

**Comment by dorianps** [comment]
Just to clarify, I used the version from user `moloney`, not `mvdoc`. Is this going to create any issue, shall I use mvdoc's fork instead?

Commands used to install:
```
git clone https://github.com/moloney/dcmstack.git
cd dcmstack/
python setup.py install
```

**Comment by yarikoptic** [comment]
actually not any longer!  Brendan seems have merged all the important patches, but let's see: https://github.com/nipy/heudiconv/pull/225
