### ISSUE TITLE
Heudiconv creates only convertall.py file

### ISSUE THREAD

**Issue by relyativist** [nipy/heudiconv#230]
I have an issue with running heudiconv:
docker run --rm -it -v /home/service/Documents/heudiconvTest:/data:ro \
-v /home/service/Documents/heudiconvTest/BIDS:/output nipy/heudiconv:latest
-d /data/{subject}/*/*.dcm -s 102
-f convertall -c none -o /output

...Then success

INFO: PROCESSING DONE: {'session':None, 'outdir': '/tmp/output/', 'subject': '102'}

BUT: In output there is a folder info but only with covertall.py, no tsv, and dicominfo file.
If you some simple mistake please mark it - Thanks!

**Comment by yarikoptic** [comment]
and is `/data/{subject}//.dcm` (not two differently formatted slashes also) a directory or the mighty dicom file or something (`*`?) is missing somewhere?

**Comment by yarkinvyacheslav** [comment]
@yarikoptic  thank you after a hours managed with this. btw is there any methods not to write heuridic.py every time? i would like to wrap my pipeline in docker with heudiconv

**Comment by yarikoptic** [comment]
Sorry, don't get the question... To not copy it under .heudiconv/ or to reuse the same heuristic for multiple studies?

**Comment by yarkinvyacheslav** [comment]
@yarikoptic  i mean - to use heuristic.py for multiple studies (with different metadata and studies (only func or resting state))?

**Comment by relyativist** [comment]
it's seems I badly explained the issue, I will try on example:
1) First i run docker hediconv with flag convertall-> get dicominfo.tsv and manually extract parameters from .tsv to heuristic.
2)Then i compose heursitic.py for 1 subject(because dcm comes every 1 week)
3) excellent: BIDS validated
My question : Is it possible to use heudiconv to  automatically (on 1 step) composing a heuristic depending on incoming dcm?

Hope, it cleared:)
