### ISSUE TITLE
trait error: the path does not exist

### ISSUE THREAD

**Issue by ilkayisik** [nipy/heudiconv#231]
I am working on a computer with limited permissions and I was having the same issue as mentioned in this pull request (https://github.com/nipy/heudiconv/pull/229) but with the suggestion of exporting the path this error is eliminated. 
However, I still have a trait error: 
```TraitError: The trait 'converted_files' of a Dcm2niixOutputSpec instance is an existing file name, but the path&nbsp; '/private/var/folders/yz/g_3xm0ms2f583j1d7bd6bz8xvxx8gp/T/tmpsPPOra/convert/func.nii.gz' does not exist.```
I guess I am getting this error because heudiconv is trying to create a folder in a location where I don't have permission to write. 
I added this line to convert.py ```convertnode.base_dir = "/Users/ilkay.isik/heudiconv/tmp"``` showing another path for this folder and then everything worked fine. 
Is this okay or can it create some future problems with compatibility/maintenance?

**Comment by mgxd** [comment]
@ilkayisik what version of nipype was this run with?

**Comment by ilkayisik** [comment]
Version: 1.0.4, Build: py27_0, Channel:conda-forge

**Comment by oesteban** [comment]
If I'm not wrong, I'd say we dealt with some permissions problems with Mac when the real path of folders was under `/private/`. Can't remember the solution though.

**Comment by djarecka** [comment]
I don't think this is a permission issue, rather the OSX mess with temporary files.

So I've just created [PR](https://github.com/nipy/nipype/pull/2639) that fixes all heudiconv tests on my OSX.

**Comment by ilkayisik** [comment]
I tried the change offered in the [PR](https://github.com/nipy/nipype/pull/2639) and it worked on my OSX too.

**Comment by djarecka** [comment]
@ilkayisik - thank you for testing it!

**Comment by mgxd** [comment]
this has now been merged into nipype's master branch, updating to latest nipype, e.g.
```
pip install -U https://github.com/nipy/nipype/archive/master.zip
```
should fix this issue
