### ISSUE TITLE
heuristics script within .heuristic folder

### ISSUE THREAD

**Issue by tjhendrickson** [nipy/heudiconv#232]
Hello,

I have noticed an issue with heudiconv. Let's say that I am testing a heuristics script on a single participant , so I re-run the script several times until I am satisfied with the output. Each time I would re-run the script after modification I have to remove the .heuristic folder because it seems that the heuristics script within .heuristic is used rather than the script specified with -f. Is this a feature or a bug? Can you point to where this occurs within the source code? I would like to make sure that when --overwrite is specified it will overwrite both the transparent and hidden (i.e. subject specific information within .heuristic) to be overwritten.

**Comment by mgxd** [comment]
@tjhendrickson what version of heudiconv are you using? This was recently changed.

the current logic is here:
https://github.com/nipy/heudiconv/blob/2ff09b1a1b77282c9a10a74799d280db1bc4f85b/heudiconv/convert.py#L116-L153

**Comment by tjhendrickson** [comment]
I'm piggy backing off of the nipy/heudiconv docker image, has that been updated to reflect the changes on github?

**Comment by mgxd** [comment]
@tjhendrickson yes

**Comment by tjhendrickson** [comment]
Great thanks!
