### ISSUE TITLE
automate heudiconv

### ISSUE THREAD

**Issue by relyativist** [nipy/heudiconv#233]
I will try to point an issue on example:

    First i run docker hediconv with flag convertall-> get dicominfo.tsv and manually extract parameters from .tsv to heuristic.
    2)Then i compose heursitic.py for 1 subject(because dcm comes every 1 week)
    excellent: BIDS validated
    My question : Is it possible to use heudiconv to automatically (on 1 step) composing a heuristic for depending on all incoming dcm?

**Comment by relyativist** [comment]
Can’ t believe that nobody faces the same problem...

**Comment by relyativist** [comment]
“...as soon as you have heuristic, you could use it for other subjects” - but if every subject have different Params in dicominfo.tsv, what I mean is there an “universal” heuristic py, not to compose it every time as dicom come in?

**Comment by yarikoptic** [comment]
you must not hardcode any subject specific information into your heuristic file, and as you can see from other heuristics, see e.g. https://github.com/nipy/heudiconv/blob/master/heudiconv/heuristics/uc_bids.py#L18 .

So if you provide converter `-c dcm2niix` if would at once use heuristic, create that dicominfo.tsv etc files, and proceed to conversion while possibly (depending on your heuristic) placing new files under new subject-specific locations.

**Comment by relyativist** [comment]
Good, could please point whole command for this “so if you provide converter -c dcm 2niix...”?

**Comment by yarikoptic** [comment]
actually I was wrong -- you do not even need `-c dcm2niix` any longer since it is the default now ;-) !
examples: can look at https://github.com/repronim/reproin#conversion

**Comment by mgxd** [comment]
@relyativist is this still an issue? If so, please re-open
