### ISSUE TITLE
DOC: we need instructions on how to map user id for docker invocation

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#241]
so that outputs do not end up being owned by root

I thought it was possible and "advised" but I can't see it reflected in our docs or the tutorial using docker

@satra @mgxd ?

**Comment by pvelasco** [comment]
You really don't need to map user id.  You just tell Docker which user id runs the container.  Even if the container doesn't know what username corresponds to that ID, it will assign ownership of the outputs to that user id.  Then, when you look at the output in the host computer, it is the host machine that knows what username corresponds to that user ID.

This it what we run:
```
userID=$UID:`id -g $UID`
docker run --user $userID --rm \
    --volume /BIDS:/data \
    --volume /CBI/UserData:/out nipy/heudiconv \
    -d /data/${dataDir}/*/*.dcm -f ${heuFile} -s ${subjectID} -c dcm2niix -b -o /out/${labDir} --overwrite
```
The output is owned by the user corresponding to `$UID` in the host machine.
