### ISSUE TITLE
anon-cmd bug/enhancement?

### ISSUE THREAD

**Issue by toddt** [nipy/heudiconv#243]
We're trying to combine several datasets into one large dataset, and have a mapping file to transform the original dataset IDs into a new ID:

exp1_sub1 -> combined_sub1
exp2_sub1 -> combined_sub2
exp2_sub2 -> combined_sub1 [because this subject showed up for multiple experiments]
...

I've written a python function that takes the original ID as input and returns the new ID, and was hoping that I could incorporate this into the heudiconv call like this:
heudiconv ... --anon-cmd='python lookupID.py'

But that doesn't appear to work. Should it?

As a temporary work around, I can use that same function to create symbolic links to my directories and do my anonymization by hand, I suppose. So far as I know, subject ID is not encoded in the saved dicom headers anywhere?

**Comment by mgxd** [comment]
@toddt could you try the following:

- make sure `lookupID.py` is executable by the desired user (chmod u+x loodupID.py)
- include a shebang at the top of the script (`#!/usr/bin/env python`)
- pass the absolute path for `lookupID.py` in your `--anon-cmd` call
