### ISSUE TITLE
DICOM_DIR_TEMPLATE Flexibility

### ISSUE THREAD

**Issue by tjhendrickson** [nipy/heudiconv#244]
Hello,

I have some strange data off of a Phillips that has dicom data within two separate directories. There are some dicom files with the following format: `DICOM/*.dcm` and others with the following format `DICOM/*/*.dcm`. Is there a way that `--dicom_dir_template` can find both sets of dicom files?

**Comment by yarikoptic** [comment]
Could you just try to point to the common "denominator", i.e. `DICOM/*`? non-dicom files should be ignored and I believe we recurse into subdirectories

**Comment by tjhendrickson** [comment]
@yarikoptic 

I tried your suggestion so my -d argument is as follows: %s/{subject}/{session}/*? Unfortunately I got several errors, and it appears that the reason is that there is not recursion into sub-directories. I think this would be a very helpful feature considering dcm2niix automatically does this. 

Here is the error output:

INFO: Running heudiconv version 0.5.2-dev
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.2.dev0', 'console_scripts', 'heudiconv')()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 125, in main
    process_args(args)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 252, in process_args
    args.subjs, grouping=args.grouping)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/parser.py", line 138, in get_study_sessions
    for session_, files_ in get_extracted_dicoms(files):
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/parser.py", line 84, in get_extracted_dicoms
    if not tarfile.is_tarfile(t):
  File "/opt/conda/envs/neuro/lib/python2.7/tarfile.py", line 2624, in is_tarfile
    t = open(name)
  File "/opt/conda/envs/neuro/lib/python2.7/tarfile.py", line 1675, in open
    return func(name, "r", fileobj, **kwargs)
  File "/opt/conda/envs/neuro/lib/python2.7/tarfile.py", line 1740, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/opt/conda/envs/neuro/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 21] Is a directory: '/tmp/01/00000001'

**Comment by mgxd** [comment]
you are right that it won't recurse into sub-dirs - one way to work around this would be to make a tarball of that subject's top level folder with all dicoms. Additionally, we could add support for multiple `--dicom_dir_template`

Eventually, it would be nice to drop python 2 support and port this to use [glob's recursive option](https://docs.python.org/3/library/glob.html#glob.glob)

**Comment by satra** [comment]
you can try this: `DICOM/**/*.dcm`

**Comment by satra** [comment]
also it wouldn't be too hard to implement this:

https://stackoverflow.com/questions/2186525/use-a-glob-to-find-files-recursively-in-python
 in `get_study_session` here: https://github.com/nipy/heudiconv/blob/master/heudiconv/parser.py#L137

with an additional flag `recurse_dicom_dir`

**Comment by tjhendrickson** [comment]
@satra and @mgxd if we can implement some way to do this that would be excellent!

**Comment by mgxd** [comment]
@tjhendrickson would you be interested in submitting a PR for this change?

**Comment by tjhendrickson** [comment]
I can do that
