### ISSUE TITLE
Usage of -o and -a flags is a bit confusing

### ISSUE THREAD

**Issue by toddt** [nipy/heudiconv#246]
I'd like to convert dicoms into a BIDS hierarchy, but anonymize the subjectIDs along the way.

When I do this, I provide parameters like this:
-o ./data/BIDS -a ./data/anonBIDS

The result is that all of the anonymized data goes into the anonBIDS directory, but that directory is missing all of the .heudiconv files, while the BIDS directory contains nothing *but* the .heudiconv files. 

Is this expected behavior? It seems not ideal. I think ideally I'd still retain the .heudiconv conversion info, but just with anonymized subject IDs.

**Comment by mgxd** [comment]
I think you'll want to set those two values to the same directory

https://github.com/nipy/heudiconv/blob/2ff09b1a1b77282c9a10a74799d280db1bc4f85b/heudiconv/convert.py#L102-L109

**Comment by toddt** [comment]
This does put the .heudiconv directory in the same output directory as the rest of the output, but the  problem with doing this (in the 0.5.2 dev version, at least) is that the subject IDs are not anonymized in the .heudiconv directory. So now I have a single output directory with a blend of original subject IDs and anonymized IDs, depending on where I look.

**Comment by mgxd** [comment]
@toddt sorry this got lost - should be a relatively easy fix
https://github.com/nipy/heudiconv/blob/2ff09b1a1b77282c9a10a74799d280db1bc4f85b/heudiconv/convert.py#L103
needs to be changed to use `anon_sid` instead of `sid`, would you care to try out that fix? And if it works, submit a PR?
