### ISSUE TITLE
AssertionError: Values differed when they should have not.

### ISSUE THREAD

**Issue by relyativist** [nipy/heudiconv#248]
Hello i try to run 4 subjects with anat data only, a i have error on 2nd subject, first one successfully converted, the n i tried to manually convert 3-rd and fourth with same heuristic and it completed successfully. Here is the logs with --dbg flag:

command:

docker run --rm -it -v /mnt/data/service/LoadTestds:/data -v /mnt/data/service/incoming:/output nipy/heudiconv:latest -d /data/DICOM/{subject}/*/*/*.dcm -f /data/code/heuristic.py -s P001 -c dcm2niix -b --overwrite -o /output --dbg

File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.2.dev0', 'console_scripts', 'heudiconv')()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 125, in main
    process_args(args)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 338, in process_args
    overwrite=args.overwrite,)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 141, in prep_conversion
    info = read_config(edit_file)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/utils.py", line 126, in read_config
    info = eval(fp.read())
  File "<string>", line 1
    defaultdict(<type 'list'>, {('sub-{subject}/anat/sub-{subject}_T1w', ('nii.gz',), None): ['4-SAG 3D T1 MPR_ex COR', '5-EPI40_1.2_30sl_TR3.T_ISV3.4', '6-3D-MP-RAGE TI 800  FA 20', '7-DTI_3MM_ISOT_WITH MAPS']})
                ^
SyntaxError: invalid syntax
> /opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/utils.py(126)read_config()
-> info = eval(fp.read())

**Comment by mgxd** [comment]
@relyativist could you try clearing the `.heudiconv` folder within your output directory? It seems there may have been an error saving some information.

**Comment by relyativist** [comment]
@mgxd Thanks for reply. Ive tried you suggestion - it dn't do the thing. Is there any any restrictions of syntaxis? here is part of dicominfo.tsv:

dim1 | dim2 | dim3 | dim4 | TR | TE | protocol_name
-- | -- | -- | -- | -- | -- | --
384 | 384 | 352 | 1 | 0.0135 | 5.5 | SAG 3D T1 MPR_ex COR_1MM_ISOT
64 | 64 | 3990 | 1 | 3.7 | 40 | EPI40_1.2_30sl_TR3.T_ISV3.4
512 | 512 | 340 | 1 | 0.012 | 5 | 3D-MP-RAGE TI 800 F

**Comment by relyativist** [comment]
Resolved: double spaces in dicominfo.tsv .header made an error.
