### ISSUE TITLE
Items in 's' for the heuristics file?

### ISSUE THREAD

**Issue by jpellman** [nipy/heudiconv#25]
I'm having a difficult time gleaning what must be done to have a functioning heuristics file, as this doesn't seem to be particularly well-documented at the moment.  

Specifically, when iterating over the 'seqinfo' list, I am uncertain what each index in the 's' list contains.  The code [here](https://github.com/nipy/heudiconv/blob/7e854e4022e888e486ae3209e4023ac6a0c265ed/bin/heudiconv#L166-L167), is illuminating, although I'm a bit unsure what 'total', 'series' and 'size' represent at a glance (with apologies if this turns out to be a slightly silly question).

**Comment by satra** [comment]
@jpellman - not a silly question. this should be added to the docs. but an example `s` is here:

```
[total_files_till_now, example_dcm_file, series_number, unspecified, unspecified, 
unspecified, dim1, dim2, dim3,  dim4, TR, TE, SeriesDescription, MotionCorrectedOrNot]

128     125000-1-1.dcm  1       -       -       
-       160     160     128     1       0.00315 1.37    AAHScout        False
```

**Comment by satra** [comment]
this has now been replaced by `namedtuple`, so fields can be accessed by name.
