### ISSUE TITLE
Missing code for converter specification in the tutorial slides

### ISSUE THREAD

**Issue by anthonyromyn** [nipy/heudiconv#253]
Hey all,

Not a big deal but I noticed a bit of missing code in slides 23 & 24 of the tutorial slides recommended in the readme (http://nipy.org/heudiconv/#1). The converter specification is missing after we specify our phantom_heuristic.py file. Took me a second to figure out that this was the cause of the errors I was getting, so it might happen to other learners, too. 

Great package, though!
Best,
Anthony

**Comment by yarikoptic** [comment]
unfortunately not clear which slides, and nobody took action in time to fix it when such knowledge was "hot". Feel free to reopen if remains the case but with a fixed up url etc
