### ISSUE TITLE
Heudiconv treating runs as separate sessions

### ISSUE THREAD

**Issue by amlarge** [nipy/heudiconv#262]
I've been having trouble getting heudiconv to treat all of my runs from a single session as a single session. 

Running heudiconv -d sourcedata/{subject}_1/dicoms/*/*.tgz -s 002 -o HDC -f convertall -c none
gives:

>  INFO: Need to process 24 study sessions 
> INFO: PROCESSING STARTS: {'session': 16, 'outdir': '/HDC/', 'subject': '002'}
> INFO: Processing 129 dicoms
> INFO: Analyzing 129 dicoms
> INFO: File /var/folders/_m/n_2231sj1fg13nxrmfmkr2gw0000gp/T/heudiconvDCM0SeEe1/./13300.SRC__AFI_B1map.json is missing any StudyInstanceUID
> WARNING: Ignoring /var/folders/_m/n_2231sj1fg13nxrmfmkr2gw0000gp/T/heudiconvDCM0SeEe1/./13300.SRC__AFI_B1map.json since not quite a "normal" DICOM: 'FileDataset' object has no attribute 'SeriesNumber'
> INFO: Generated sequence info with 1 entries
> INFO: PROCESSING DONE: {'session': 16, 'outdir': /HDC/', 'subject': '002'}
> INFO: PROCESSING STARTS: {'session': 3, 'outdir': '/HDC/', 'subject': '002'}
> INFO: Processing 6001 dicoms
> INFO: Analyzing 6001 dicoms
> INFO: File /var/folders/_m/n_2231sj1fg13nxrmfmkr2gw0000gp/T/heudiconvDCM0SeEe1/./00009.fMRI_-_task.json is missing any StudyInstanceUID
> WARNING: Ignoring /var/folders/_m/n_2231sj1fg13nxrmfmkr2gw0000gp/T/heudiconvDCM0SeEe1/./00009.fMRI_-_task.json since not quite a "normal" DICOM: 'FileDataset' object has no attribute 'SeriesNumber'
> INFO: Generated sequence info with 1 entries
> INFO: PROCESSING DONE: {'session': 3, 'outdir': '/HDC/', 'subject': '002'}
> INFO: PROCESSING STARTS: {'session': 4, 'outdir': '/HDC/', 'subject': '002'}
> INFO: Processing 6001 dicoms
> INFO: Analyzing 6001 dicoms
> INFO: File /var/folders/_m/n_2231sj1fg13nxrmfmkr2gw0000gp/T/heudiconvDCM0SeEe1/./00010.fMRI_-_task.json is missing any StudyInstanceUID
...etc

and spits txt,json,tsv outputs for each run separately

Running heudiconv -d sourcedata/{subject}_{session}/dicoms/*/*.tgz -s 002 -ss 1 -o HDC -f convertall -c none
gives 

> WARNING: We had session specified (1) but while analyzing files got a new value 0 (using it instead)
> WARNING: We had session specified (1) but while analyzing files got a new value 1 (using it instead)
> WARNING: We had session specified (1) but while analyzing files got a new value 2 (using it instead)
> WARNING: We had session specified (1) but while analyzing files got a new value 3 (using it instead)
> WARNING: We had session specified (1) but while analyzing files got a new value 4 (using it instead)

...etc

And if I run heudiconv with an actual heuristic file to convert to BIDS, it seems as if it's overwriting the previous data.

**Comment by mgxd** [comment]
hi @amlarge - what version of heudiconv are you running? Is this in a local or docker environment?

**Comment by amlarge** [comment]
I'm using 0.5.1. I have the same error with local and docker.

**Comment by mgxd** [comment]
Ok - some more thoughts/questions:
* It looks like you have some non-DICOMs in the tarball - this should be ignored (as the logs say it is)
* How many tarballs are being found with your `-d <path>`? It looks like heudiconv is finding multiple, and treating them as separate sessions (intended behavioral)

**Comment by amlarge** [comment]
Yes, there are sidecar files that heudiconv is skipping

In the dicoms directory, there are 23 folders, each with a tarball. There are 4 behavioral, 1 anatomical, 2 fieldmap.

**Comment by mgxd** [comment]
Okay, I see your problem. Currently, when heudiconv receives a tarball, it will process it as a contained session. In your case, each run is being treated as its own session, which results in wonky conversion results.

To fix this, I recommend untar-ing all your subject's scan-level tarballs and combining them into a single tarfile. Then passing in a single file per subject should do the trick.

**Comment by ariekahn** [comment]
I just spent a while debugging my script with the same issue, and the fact that different tarballs are treated as different sessions really isn't made clear in the documentation, had to dig into the API to figure out why it was failing. It's also particularly unexpected behavior when I'm manually passing in a session (e.g. `-d dicom/sub-{subject}/ses-{session}/*.tar.gz -ss 1`). There really should be mention of this in the description of the `-d` flag.
