### ISSUE TITLE
conflicting study identifiers in ABCD data

### ISSUE THREAD

**Issue by DVSneuro** [nipy/heudiconv#280]
Hi, I'm using heudiconv to convert some of the ABCD data into BIDS format, but it seems to only be working on data collected on the Siemens scanner. For the other scanners, I'm getting the error below. 

INFO: Running heudiconv version 0.5.2-dev
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 'NDARINVE367LYLC', 'outdir': '/output/', 'session': None}
INFO: Processing 49972 dicoms
INFO: Analyzing 49972 dicoms
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 125, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 338, in process_args
    overwrite=args.overwrite,)
  File "/src/heudiconv/heudiconv/convert.py", line 159, in prep_conversion
    grouping=None)
  File "/src/heudiconv/heudiconv/dicoms.py", line 88, in group_dicoms_into_seqinfos
    studyUID, file_studyUID
AssertionError: Conflicting study identifiers found [1.2.840.113619.6.374.258119085267376010175966987442804122141, 1.2.840.113619.6.374.54018679043989047307905145274801870417].

I've tried running dcm2niix on these dicoms outside of heudiconv, and that seems to work fine. 

Thanks for any advice!
David

**Comment by yarikoptic** [comment]
I guess that study (i.e. sessio)n was interrupted, subject was taken out, put back in and and some sequences reran?

you could try using grouping by accession -- `-g accession_number`, and eventually we should finish or redo #200

**Comment by yarikoptic** [comment]
by any chance -- do you have phantom runs on all the scanners using ABCD protocols/sequences which could potentially be shared publicly? would make it easier to implement all needed/desired support

**Comment by DVSneuro** [comment]
I don't, but I'll look into that. In theory, all of their data should be released in BIDS format, but that is not currently the case, at least from what I've seen.
https://www.biorxiv.org/content/early/2018/11/04/457739

**Comment by sjburwell** [comment]
Greetings,

I have a related issue to the above whereby heudiconv (docker implementation, 0.5.dev1) throws a conflicting study error (see below). For this participant/session, there was a system error and the console needed to be rebooted midway through the session. Thus, the scanning took place on the same day (and proximal in time, i.e., the same "session"), but the dicoms have different study identifiers. The accession_number for all dicoms is blank (i.e., ''), and when I tried using the above suggestion ("-g accession_number") it still seemed to be looking for "StudyInstanceUID." Does the accession number need to be a non-blank value? Any thoughts on whether I can 'trick' heudiconv into thinking this data comes from the same session?

Best,
Scott

Error::
Conflicting study identifiers found [1.3.12.2.1107.5.2.43.67010.30000015061717133439900000013, 1.3.12.2.1107.5.2.43.67010.30000015061722134788600000001]

**Comment by DVSneuro** [comment]
@yarikoptic Sorry for the slow follow up on this. The ABCD team didn't want to share the phantom data (they also didn't think it would be helpful since it apparently doesn't include the same sequences as the human data). Would it be possible for me to privately share some of the problematic data? I'm still still seeing the same issue with the latest version of HeuDiConv (0.5.4.dev1). Thanks again!

**Comment by yarikoptic** [comment]
@DVSneuro, sure, let's continue via email
