### ISSUE TITLE
Processing 0 sessions

### ISSUE THREAD

**Issue by Tahll** [nipy/heudiconv#296]
Dear all,
Iam trying to use heudiconv within docker for the first time. Unfortentuately, I only got the Info messages:

> "INFO: Running heudiconv version 0.5.4.dev1"
> " Need to process 0 study sessions"

Maybe I set the path to my dicoms wrongly. However, I have no idea why. Here is my folder structure and the command I use in docker. Please note since it is the first time I use heudiconv I oriented myself at the BIDS Tutorial Series: HeuDiConv Walkthrough (http://reproducibility.stanford.edu/bids-tutorial-series-part-2a/) and also use their example dataset

**My command to call heudiconv is:**
```
docker run --rm -it -v /Documents/Frei/python:/base nipy/heudiconv:latest \
-d /base/dicom/sub-{subject}/ses-{session}/SCANS/*/Dicom/*.dcm -o /base/BIDS/ -f convertall -s 01 -ss 001 -c none --overwrite
```

**My folder structure:**

```
Documents
       Frei
       ...
          python
          ...
                  BIDS
                  dicom
                       sub-01
                           ses-01
                                  SCANS
                                        3
                                            DICOM
                                                  files.dcm
                                        4
                                        ...
                           ses-005
                           ses-025
```

I am working on a windows 10 pc
I hope somebody can help

**Comment by mgxd** [comment]
hi @Tahll - it looks like your DICOM files are not being found. 

One problem could be your `-ss` is looking for `ses-001`, but its listed in your directory tree as `ses-01`?

You could also try to shell into the container and interactively check your paths with:
```shell
docker run --rm -it -v /Documents/Frei/python:/base --entrypoint=bash nipy/heudiconv:latest
```
