### ISSUE TITLE
pass additional arguments to dcm2niix

### ISSUE THREAD

**Issue by greydongilmore** [nipy/heudiconv#297]
### Summary

I am wondering if it's possible to pass additional arguments to dcm2niix? I am running a conversion of MRI and CT sequences. Some of the CT sequences have a Gantry tilt and I would like to pass ```-m y```  to dcm2niix.

### Platform details:

Choose one:
- [x] Local environment
- [ ] Container

- Heudiconv version: 0.5.2

**Comment by mgxd** [comment]
Hi Greydon,

There was a PR in limbo for this very functionality (#208) - I've merged it in now. Refer to [this comment](https://github.com/nipy/heudiconv/issues/206#issuecomment-388981312) on how to force stacking with this new option
