### ISSUE TITLE
Heudiconv Nonfunctional within Latest Docker Image

### ISSUE THREAD

**Issue by tjhendrickson** [nipy/heudiconv#299]
### Platform details:

Choose one:
- [ ] Local environment

- [x] Container

- Heudiconv version:

**Comment by tjhendrickson** [comment]
I use the nipy/heudiconv container within a singularity container to convert my data to BIDS. Here is my call:
singularity run -B /home/range2-raid1/timothy/BIDS/Data_READISCA_U01/:/output_dir -B /home/naxos2-raid14/ywpark-data/Data_READISCA_U01/DICOM:/dicom_dir -B /home/rosalind2-raid1/ywpark/Scripts_BIDS/test_heuristic.py:/heuristic.py /home/range2-raid1/timothy/singularity_images/tjhendrickson-BIDS_scripts-master-latest.simg --output_dir /output_dir --dicom_dir /dicom_dir --subj_id HM-01-009 --heuristic /heuristic.py

And the error message:
/src/heudiconv/heudiconv/dicoms.py:7: UserWarning: The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment
Please use with caution.  We would be grateful for your help in improving them
  from nibabel.nicom import csareader
INFO: Running heudiconv version 0.5.4.dev1
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 125, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 252, in process_args
    args.subjs, grouping=args.grouping)
  File "/src/heudiconv/heudiconv/parser.py", line 131, in get_study_sessions
    for sid in sids:
TypeError: 'NoneType' object is not iterable

I seem to recall that up until recently my container used a stable version of heudiconv (maybe 0.5.3?) Anyway is there a way to force heudiconv to use a particular version or how would I revert to a previous version? 

Thanks!

-Tim

**Comment by yarikoptic** [comment]
> Anyway is there a way to force heudiconv to use a particular version or how would I revert to a previous version?

looking at

/home/range2-raid1/timothy/singularity_images/tjhendrickson-BIDS_scripts-master-latest.simg 
and
INFO: Running heudiconv version 0.5.4.dev1

it seems to be you who built your own Singularity image and run master version... if you want singularity images with heudiconv, there is e.g. our reproin images of which we have a number of versions available from the singularity hub: https://www.singularity-hub.org/collections/588

but getting back to your error, I see only the `--dicom_dir /dicom_dir ` so it is not even a template... and `--subj_id HM-01-009` which is also not a cmdline argument heudiconv understands... did it ever work?  do you have some custom entry point script in your singularity image?

**Comment by tjhendrickson** [comment]
We don’t have to get to into the details of what I have done. I have a separate application within my image to act as a wrapper to heudiconv. I’ll look at the url you sent me so I can incorporate a previous version into my image.

Thanks!!

Tim

**Comment by yarikoptic** [comment]
Dear @tjhendrickson - did you figure out this issue, so it could be closed or is there something to address on our end?

**Comment by tjhendrickson** [comment]
Thanks for following up, yes I've figure it out. You can close it.

Best,

-Tim
