### ISSUE TITLE
Update heuristic for BIDS

### ISSUE THREAD

**Issue by hanke** [nipy/heudiconv#3]

**Comment by chrisfilo** [comment]
Yes yes yes! I'll look into this.

**Comment by hanke** [comment]
I am doing one for a local dataset right now. We should look into making a rather generic one.

**Comment by hanke** [comment]
I found that for an individual study it is best to go with the series description to decide what to put where in the heuristic (if the description is reliable). A default BIDS heuristic should not do that, however. Instead it seems feasible to guess the type of an image based on typical properties of a series:

t1 - short TE; t2 - long TE (both single volume); EPI - long TR, multiple volumes

**Comment by yarikoptic** [comment]
So what is the best example out so far? ;)

**Comment by satra** [comment]
the new bids examples actually generate a valid BIDS dataset. but i don't know if there is a set of dicoms available that we can use.

any chance the entire study forrest paradigm was acquired on a phantom?

**Comment by satra** [comment]
@yarikoptic - also in our case, keeping the raw dicoms are going to be important (and may be for some projects even the k-space data).

**Comment by hanke** [comment]
@satra sadly we don't have phantom scans for everything -- got a little sloppy at the end...

**Comment by yarikoptic** [comment]
@satra keeping original dicoms around is always a good idea ;)  I am slowly impressing that into minds here as well and will make sure that DICOMs for QA scans on the phantom are preserved

**Comment by chrisfilo** [comment]
I believe those are the relevant heuristics:
https://github.com/nipy/heudiconv/blob/master/heuristics/bids_no_ses.py
https://github.com/nipy/heudiconv/blob/master/heuristics/bids_with_ses.py
