### ISSUE TITLE
Issues w/ slurm

### ISSUE THREAD

**Issue by fhopp** [nipy/heudiconv#302]
Greetings, 

heudiconv version 0.5.3. 

I am trying to run a basic heudiconv on one subject for testing w/ slurm (running on two nodes, partition name = heudiconv) to create my heuristic. 

1) Command as follows: 

heudiconv -d /srv/lab/fmri/mft/dicom4bids/data/{subject}*/* -f /srv/lab/fmri/mft/dicom4bids/data/convertall.py -s sub01 -q heudiconv -o /srv/lab/fmri/mft/dicom4bids/data/output/

This yields: 
INFO: Running heudiconv version 0.5.3
INFO: Need to process 1 study sessions
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/fmri/bin/heudiconv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/fmri/lib/python3.5/site-packages/heudiconv/cli/run.py", line 125, in main
    process_args(args)
  File "/usr/local/anaconda3/envs/fmri/lib/python3.5/site-packages/heudiconv/cli/run.py", line 296, in process_args
    study_outdir,
UnboundLocalError: local variable 'study_outdir' referenced before assignment

2) Now, adding "-l unknown" to the above command executes, but does not create a .heudiconv folder: 
INFO: Running heudiconv version 0.5.3
INFO: Need to process 1 study sessions
WARNING: Skipping unknown locator dataset

3) Curiously, removing the -q flag and the -l flag executes the command properly and creates .heudiconv under /output:
INFO: Running heudiconv version 0.5.3
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': None, 'outdir': '/srv/lab/fmri/mft/dicom4bids/data/output/', 'subject': 'sub01'}
INFO: Processing 4976 dicoms
INFO: Analyzing 4976 dicoms
INFO: Generated sequence info with 10 entries
INFO: PROCESSING DONE: {'session': None, 'outdir': '/srv/lab/fmri/mft/dicom4bids/data/output/', 'subject': 'sub01'}

4) Anyone else experienced these issues? How come that adding -q breaks the locator inference? I still believe that a working scheduler integration for heudiconv will be extremely valuable w/ increasing data sets and I am happy to contribute. Perhaps a starting point would be to clarify what the -l flag actually requires. In the help menu for -l, it says: study path under outdir. If provided, it overloads the value provided by the heuristic. If --datalad is enabled, every directory within locator becomes a super-dataset thus establishing a hierarchy. Setting to "unknown" will skip that dataset. 

Thanks in advance!

**Comment by mgxd** [comment]
hi @fhopp - sorry for the late response. We had to make a few changes to get this working again - could you retry your conversion with the latest version of this repo?

**Comment by fhopp** [comment]
Hi @mgxd - also, sorry from my side for the late reply, I was only able to resume this work recently. 
Good news first, the tasks are now submitted to SLURM and I can see the jobs in the logs of the slurm nodes/deamons. However, I get a different error now that stops the script from executing. 

Note that I am running heudiconv in a virtual conda enviornment, which *might* be part of the problem? 
Here's my command, executed after activating the conda enviornment:

heudiconv -d /srv/lab/fmri/mft/dicom4bids/data/{subject}/* -f /srv/lab/fmri/mft/dicom4bids/data/convertall.py -s sub01_9994d sub02_0270y -q SLURM --queue-args="--partition=heudiconv" -o /srv/lab/fmri/mft/dicom4bids/data/output/

Which yields:

INFO: Running heudiconv version 0.5.4.dev1
INFO: Need to process 2 study sessions
Submitted batch job 127
Submitted batch job 128

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/fmri/lib/python3.5/site-packages/heudiconv/cli/run.py", line 8, in <module>
    from .. import __version__, __packagename__
ImportError: attempted relative import with no known parent package

After fiddling, it seems that none of the relative imports work. 
I tried to remove and change the shebang at the beginning of run.py to my conda env, but that didnt do the trick either. 

Any ideas? Happy to assist!

**Comment by fhopp** [comment]
After replacing the relative with the absolute imports it works:
from .. import __version__, __packagename__ 

from heudiconv import __version__,__packagename__ 

I am not deep enough into the file structure of heudiconv to manually adjust the relative paths, but I thought I'd let you know!

**Comment by mgxd** [comment]
@fhopp - yes, that has been a long time coming...

can you try out the PR above to see if that works for you

**Comment by yarikoptic** [comment]
well, "works" could have different meanings.  Here it seems to be "absolute imports do not cause crash".  In my experience failing relative imports point to some incorrect or conflicting installation(s) or invocations...

here
```
INFO: Running heudiconv version 0.5.4.dev1
INFO: Need to process 2 study sessions
Submitted batch job 127
Submitted batch job 128

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/fmri/lib/python3.5/site-packages/heudiconv/cli/run.py", line 8, in <module>
    from .. import __version__, __packagename__
ImportError: attempted relative import with no known parent package
```
smells like you are running that run.py directly?  shouldn't be... what is the output of `which heudiconv`? what does that script which it points to look like?  here is how it is in my case in a virtualenv:

```
$> which heudiconv
/home/yoh/picts/mris/heudiconv/venvs/dev/bin/heudiconv

$> cat `which heudiconv`
#!/home/yoh/picts/mris/heudiconv/venvs/dev/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'heudiconv','console_scripts','heudiconv'
__requires__ = 'heudiconv'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
    )
```

**Comment by fhopp** [comment]
Agree, it doesn't crash. For better comprehension, here's my output:

```
$ which heudiconv
/usr/local/anaconda3/envs/fmri/bin/heudiconv

$ cat `which heudiconv`
#!/usr/local/anaconda3/envs/fmri/bin/python

# -*- coding: utf-8 -*-
import re
import sys

from heudiconv.cli.run import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

**Comment by mgxd** [comment]
@yarikoptic yes, I think this was my original idea and implementation, but I was worried that the python/heudiconv executable was not guaranteed to be the same if submitting to another node - so I wanted to "pin" both used executables. But looking at the entrypoint file, looks like the shebang has that covered.
