### ISSUE TITLE
Generate participants.json to accompany .tsv where fields are described

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#318]
ATM we are generating `participants.tsv` with columns age, sex, group. bids-validator then whines
```
./participants.tsv
     Evidence: Columns: age, sex, group not defined, please define in: /participants.json
```
We should then create/define something like
```json
{
  "participant_id": {
    "Description": "participant id"
  },
  "age": {
    "Description": "Age in years (TODO - verify) as in the initial session, might not be correct for other sessions"
  },
  "sex": {
    "Description": "self-rated by participant, M for male/F for female (TODO: verify)"
  },
  "group": {
    "Description": "(TODO: adjust - by default everyone is in control group)"
  }

}
```

**Comment by satra** [comment]
and perhaps add some URIs for proper example and definition.

**Comment by fhopp** [comment]
Same applies to the _scans.tsv with variables: 

![image](https://user-images.githubusercontent.com/22058606/55674990-aa677880-5870-11e9-8c48-8d5dc2515e78.png)

@yarikoptic @satra if you can point me to the file/line where these need to be defined I can jump in and work on a potential fix.

**Comment by yarikoptic** [comment]
Just  `git grep _scans`  to find location in the code. Thank you in advance!
