### ISSUE TITLE
Re-create participants.tsv

### ISSUE THREAD

**Issue by araikes** [nipy/heudiconv#320]
### Summary
Simple question (I hope). I'm using the Dockerized version of heudiconv v 0.5.3. I'm am brute-forcing it to run on my longitudinal data on SLURM by passing the following commands:

```
for subject in ${particNumArr[*]}; do
		mkdir -p $basedir/slurm_logs/${subject}
		LOGS=$basedir/slurm_logs/${subject}

		sessions=($(ls $basedir/source/${subject}))

		for sesh in ${sessions[@]}; do
			sbatch \
			-o $LOGS/${sesh}_heudiconv_out.txt \
			-e $LOGS/${sesh}_heudiconv_error.txt \
			--job-name="${subject}"_heud \
			--wrap "docker run --rm -i \
			-v ${basedir}:/base \
			nipy/heudiconv:debian \
			-d /base/source/{subject}/{session}/*/*.dcm \
			-o /base/bids_nifti \
			-f /base/code/convertall.py \
			-s ${subject} \
			-ss ${sesh} \
			-c dcm2niix -b \
			--overwrite"
		done
done
```

This works just fine and does a great job of converting everything. I know that there's a `-q` option for the standalone version, but it does not work on the Dockerized version.

The "problem" (used loosely) I'm running into this is: The participants.tsv file isn't in alphabetic/numeric order. For instance sub-142 may come before sub-120 depending on job finishing speed.

Is there a way to regenerate the .tsv file after everything is run just to resort it into the right order?

Thanks,
Adam

### Platform details:

Choose one:
- [ ] Local environment

- [x ] Container

nipy/heudiconv:debian

- Heudiconv version: 

0.5.3

**Comment by yarikoptic** [comment]
open in editor, sort lines, save in the editor?
or if you have `sponge` installed
```
sort participants.tsv | sponge participants.tsv
```
?  or am i missing the point?

**Comment by araikes** [comment]
Yeah obviously I can do it in editor... Was hoping for something a bit more programmatic so that I can drop it in a script so others don't need to think about it.

**Comment by yarikoptic** [comment]
if you have no `sponge` around 
```
python -c 'lines=open("participants.tsv").readlines(); open("participants.tsv", "w").writelines(sorted(lines))'
```
might do it for you (unless you are on windows, which would whine about opened files)

**Comment by yarikoptic** [comment]
For the "proper" resolution - we might as well sort those while adding entries to `participants.tsv`

**Comment by araikes** [comment]
Sorry... Been out the last week. I'll give the python approach a shot and see if does it. I imagine that, overall, it doesn't really matter aside from the visual disorganization.
