### ISSUE TITLE
Executable?

### ISSUE THREAD

**Issue by kaihwang** [nipy/heudiconv#321]
This is a newbie question I apologize up front if I offended anyone. My system admin is not permitting us to install docker, and I also couldn't get singularity to work. I was able to do 
`pip install heudiconv` 
without error. From the document, it suggests that there is an executable "heudiconv" that I can call from the bash terminal:

`heudiconv -d '{subject}*.tar*' -s xx05 -f ~/myheuristics/convertall.py`

However, I couldn't find the file "heudiconv" anywhere in the github folder. My question is how exactly do I execute the heudiconv command? Thanks.

**Comment by kaihwang** [comment]
I also got a manifest error when trying to use singularity to pull form docker:

[kahwang@thalamege ~]$ singularity pull docker://nipy/heudiconv
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/nipy/heudiconv:latest
ERROR MANIFEST_UNKNOWN: manifest unknown
Cleaning up...
ERROR: pulling container failed!

**Comment by mgxd** [comment]
The `heudiconv` executable is really an entrypoint into a specific method of the `heudiconv.cli.run` script, and will be installed in your python's bin. what is your output when you type `heudiconv --version`? 

Also regarding the manifest error - we replace the `latest` tag in favor of `unstable` for our image on DockerHub. You should be able to pull it successfully with `singularity pull docker://nipy/heudiconv:unstable`

**Comment by kaihwang** [comment]
Thank you, I was able to find the executable and also successfully pull with singularity.  I am running 0.5.4

[kahwang@thalamege info]$ heudiconv --version
0.5.4.dev1

I am having difficulties reading some of our GE 7T dicoms (but not 3T), which I will post in a new thread.

**Comment by daeh** [comment]
I ran into this issue too (but with singularity). Would it make sense to have recommended docker/singularity pull commands on the github landing page?

**Comment by mgxd** [comment]
Hopefully this is much clearer now with our RTD - closing, but feel free to reopen
