### ISSUE TITLE
Add an option to disable dcmstack metadata dump

### ISSUE THREAD

**Issue by chrisfilo** [nipy/heudiconv#33]
Currently heudiconv will try to save all of the metadata from dicoms into the sidecar JSON file (in addition to the BIDS metadata extracted and normalized by dcm2niix). This can be good for preserving as much information as possible, but at the same time it can generate gigabytes of data in form of JSON files. It would be good if this could be turned off on the command line.

**Comment by chrisfilo** [comment]
It seems that the dcmstack dump is already embeded in the nifti file: https://github.com/nipy/heudiconv/blob/master/bin/heudiconv#L264 so this would not even make users lose any metadata. It would still be available in the nifti header. However since heudiconv uses nii.gz the metadata will be compressed saving a lot of space.

**Comment by satra** [comment]
somehow missed this. ok this is because for some reason pixel data is being included - i thought i had fixed this, but will address this shortly.

**Comment by mgxd** [comment]
@chrisfilo with #50 you can use the `--minmeta` flag

**Comment by chrisfilo** [comment]
Awesome! Thanks!
