### ISSUE TITLE
Negative slice timing 

### ISSUE THREAD

**Issue by sethim** [nipy/heudiconv#332]
Hi, 
I wonder if you can help with this. 

The json sidecar contains negative slice timings for my functional data. The slice at the bottom of the stack is allocated time zero (actual time 1.49 sec) and the subsequent images are all offset by the about 1.49 sec (eg. second slice that was acquired at time zero becomes -1.49). 

This issue is occurring only when heudiconv is calling dcm2niix and not when I generate the sidecar with dcm2niix directly. 

Cheers, 
Moksh 

### Platform details:

Choose one:
- [ ] Local environment

- [ ] Container

- Heudiconv version:

**Comment by mgxd** [comment]
Hi @sethim 

>This issue is occurring only when heudiconv is calling dcm2niix and not when I generate the sidecar with dcm2niix directly.

Are you using the same version of dcm2niix to compare? There was an issue regarding this in previous versions of dcm2niix - see https://github.com/rordenlab/dcm2niix/issues/271

**Comment by mgxd** [comment]
@sethim we have updated the version of dcm2niix in our docker container (#334) - could you try `0.5.4` and see if that fixes your problem?

**Comment by sethim** [comment]
@mgxd Thanks. Running the updated version has indeed fixed the negative slice timing issue. Cheers!
