### ISSUE TITLE
default command does not work with tcsh

### ISSUE THREAD

**Issue by kslays** [nipy/heudiconv#338]
### Summary
This command works fine in bash:
`singularity run -B /path/to/my/files/:/base heudiconv.simg -d /base/dicom/{subject}/* -o /base/nifti/ -f convertall -s mysubject080 -c none`

However, in tcsh, the following error is reported:
`singularity: No match.`

I also tried running it on tcsh with docker and got a similar error:
`docker: No match.`

Is this an issue with the {subject} notation, or something else? Regardless, perhaps the documentation should explicitly mention bash needs to be used, not tcsh.

### Platform details:

Choose one:
- [ ] Container
singularity 

- Heudiconv version: 0.5.4

**Comment by kslays** [comment]
I also tried it on zsh, which doesn't work either.

**Comment by yarikoptic** [comment]
Do you have singularity installed? Can you run singularity --help?

**Comment by kslays** [comment]
> Do you have singularity installed? Can you run singularity --help?

@yarikoptic, thanks for the reply. Yes, singularity and docker are both installed. `singularity --help` results in the help text being printed in the terminal in all three shells: bash, tcsh, and zsh. The command works fine from bash, but tcsh and zsh both result in the `No match.` error.

Do you think this is heudiconv error, or instead an error in the command syntax, perhaps with the curly braces?

**Comment by yarikoptic** [comment]
Quote your args and we will discover

```
singularity run -B /path/to/my/files/:/base heudiconv.simg -d '/base/dicom/{subject}/*' -o /base/nifti/ -f convertall -s mysubject080 -c none

```

**Comment by pguduguntla** [comment]
I tried it out on tcsh and zsh and quoting the arguments for the -d flag fixes the issue.

**Comment by kslays** [comment]
So it looks like this issue is just an error in documentation, so can be closed when the documentation suggests quoting the arguments.

Thank you @yarikoptic for solving the issue!

**Comment by yarikoptic** [comment]
good idea -- see https://github.com/nipy/heudiconv/pull/363 which should close this issue if merged ;)
