### ISSUE TITLE
silence up nipype unless in < INFO logging mode

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#34]
ATM it is too talkative to my liking -- making it easy to miss important warnings etc.
@satra - how in current heudiconv code to make nipype silent?  

I have tried 

0.  standard python way e.g.
```python
logging.getLogger('nipype').setLevel(logging.WARNING)
```

1. to modify custom config file
```shell
$> cat ~/.nipype/nipype.cfg       
[DEFAULT]
interface_level = WARNING
filemanip_level = WARNING
workflow_level = WARNING
```
but it just keeps bringing all the useful INFO ;)

**Comment by satra** [comment]
you can do this wherever nipype is being imported

```
from nipype import config, logging
config.set('logging', 'workflow_level', 'WARNING')
config.set('logging', 'interface_level', 'WARNING')
logging.update_logging(config)
```

**Comment by mgxd** [comment]
closing this - feel free to reopen
