### ISSUE TITLE
Error if EchoNumber tag missing with multi-echo sequence

### ISSUE THREAD

**Issue by nicholst** [nipy/heudiconv#347]
### Summary

While PR #345 successfully treats PD+T2 pairs as multi-echo, we now get runtime errors when such acquisitions are missing the `EchoNumber` tag:
```
*Runtime**Error**: was asked to copy X but destination already exists: Y
```
Using the `--overwrite` option eliminates the error but only leaves us with one echo.

Presently, multi echo support depends on `EchoNumber` tag, but given there are DICOM files in the wild that lack this tag we need a backup logic, presumably based on `EchoTime`.  I can see that this requires a modification to the logic of `save_converted_files` in [convert.py](https://github.com/nipy/heudiconv/blob/master/heudiconv/convert.py)... something like 

```
EchoNumberBackup = [x+1 for x in sorted(range(len(echo_times)), key=echo_times.__getitem__)]
```

and then [assignment of `echo_number`](https://github.com/nipy/heudiconv/blob/master/heudiconv/convert.py#L572) will need to check for empty value and use `EchoNumberBackup` when missing.  I can almost see what to do but it's just a bit beyond my very elementary Python.

### Platform details:

Choose one:
- [x] Local environment

Python 3.6.6

- Heudiconv version: 

v0.5.4 + PR #345 patch

**Comment by yarikoptic** [comment]
another related is #346 - "Provide flexible support for multi-volume sequences" ;-)

**Comment by tsalo** [comment]
I fixed this on my fork by converting `echo_times` into a list and using the file's EchoTime to index that list (plus one) to get the echo number if EchoNumber wasn't in `fileinfo`'s keys.

I.e.,
```python
# Get the EchoNumber from json file info.  If not present, use EchoTime
if 'EchoNumber' in fileinfo.keys():
    echo_number = fileinfo['EchoNumber']
else:
    echo_number = echo_times.index(fileinfo['EchoTime']) + 1
```

I'd be happy to open a PR, unless there are plans for a different fix.
