### ISSUE TITLE
Support for complex multi-echo fMRI

### ISSUE THREAD

**Issue by tsalo** [nipy/heudiconv#368]
### Summary

Functional phase data (from magnitude+phase reconstruction of fMRI data) is not currently supported as a multi-echo data type. I know that there are plans for a more robust form of support for multi-volume sequences in #346, but in the meantime I think that `_phase` needs to be added to the [list of supported multi-echo data types](https://github.com/nipy/heudiconv/blob/5cfb6f2835f76b8c9d6f19c45e8be0759535900f/heudiconv/convert.py#L583).

### Platform details:

Choose one:
- [X] Local environment: OSX Mojave, Python 3.6.2

- [ ] Container

- Heudiconv version: latest, as of 5cfb6f2

**Comment by yarikoptic** [comment]
Do you have some shareable (phantom, ideally lower res) sample dicoms?

**Comment by tsalo** [comment]
I do! It's phantom data, although not particularly low resolution.

[Here](https://drive.google.com/open?id=1MZvQ6HiyIqYZN_IiB8r-XnyhnK7jrj7d) is the link to the data on Google Drive.

The data have six echoes, a multi band factor of 4, and were acquired on a Siemens Prisma:
- 612_Estimation_task1_6ET_MB4_SBRef: The single-band reference image (unnecessary but shared anyway).
- 613_Estimation_task1_6ET_MB4: The magnitude data.
- 614_Estimation_task1_6ET_MB4: The phase data.

**Comment by yarikoptic** [comment]
any objections if I reshare them from http://datasets.datalad.org/?dir=/dicoms  (a new `salo/` subdataset there).  There is already http://datasets.datalad.org/?dir=/dicoms/velasco/MEEPI which we use for some rudimentary testing

**Comment by tsalo** [comment]
No objections. Thank you!

**Comment by tsalo** [comment]
@yarikoptic, should I wait for a larger refactor (e.g., the plans in #346) or would it be okay for me to open a pull request with my proposed change [here](https://github.com/nipy/heudiconv/blob/5cfb6f2835f76b8c9d6f19c45e8be0759535900f/heudiconv/convert.py#L583)?

**Comment by mgxd** [comment]
@tsalo I'd say go for it - the refactor won't come for a bit.

**Comment by yarikoptic** [comment]
> [Here](https://drive.google.com/open?id=1MZvQ6HiyIqYZN_IiB8r-XnyhnK7jrj7d) is the link to the data on Google Drive

sorry for the delay. I've requested access now
