### ISSUE TITLE
unable to get bval/bvec: converted but not copied to output

### ISSUE THREAD

**Issue by mgxd** [nipy/heudiconv#38]
I'm processing some Prisma data and noticed heudiconv isn't outputing bvals or bvecs. When I run the conversion using command-line dcm2niix, the bvals/bvecs were successfully made.

I thought this was a problem with nipype's dcm2nii.py interface - but even after making [these changes](https://github.com/nipy/nipype/compare/master...mgxd:fix/d2nx) I was still unable to produce them. Any ideas as to what is causing this?

For reference, here is dcm2niix's [stdout](http://pastebin.com/2W7rsHKu) for my diffusion scans

**Comment by satra** [comment]
this appears to work fine now.

**Comment by Shotgunosine** [comment]
I've got this error with dataset I'm working with now. I'll let you know if I figure out what's causing it.

**Comment by WillForan** [comment]
also hit an issue here on `0.8.0`

```
# in container
docker run --rm -it -v $(pwd):/in -v bids_out:/out nipy/heudiconv:latest \
   -b -o out \
   -c dcm2niix \
   -d '/in/{subject}*/*/*' \
   -f '/in/bids_heuristic.py' \
   -p \
   -s 11354

# or without
heudiconv \
   -b -o bids_out \
   -c dcm2niix \
   -d '{subject}*/*/*' \
   -f 'bids_heuristic.py' \
   -p \
   -s 11354

# but get bvec and bval with just dcm2niix
 dcm2niix -b y -z y -x n -t n -m n -f sub-11354_run-1_dwi -o d2n -s n -v n 11354/diff113_current_PA_1152x1152.16/
```

```
ls bids_out/sub-11354/dwi/
sub-11354_run-1_dwi.json  sub-11354_run-1_dwi.nii.gz  sub-11354_run-1_dwi_prov.ttl
```

```
 ls d2n/
sub-11354_run-1_dwi.bval  sub-11354_run-1_dwi.json
sub-11354_run-1_dwi.bvec  sub-11354_run-1_dwi.nii.gz
```

here's more as a gist:
https://gist.github.com/WillForan/d7dbcf83011d83b531ecb3f4519ab828

**Comment by yarikoptic** [comment]
I think I have ran into this issue as well!  Note that prior "lost bval/bvec" boiled down to need of fixing nipype: https://github.com/nipy/heudiconv/issues/13 ... yet to investigate in detail what is going on

**Comment by yarikoptic** [comment]
tested with nipype master (1.6.0-1-g47fe00b38, with that extra commit about mrtrix3, so unrelated) -- worked correctly! not sure what specific commit in nipype fixed up this issue yet.  as much as love nipype and nipypers, but for a single interface of dcm2niix, it is imho too large of a beast (goes back to #6), heh.  I guess we can resolve this issue by demanding nipype >= 1.6.0 , unless someone points to the fix more specifically.

**Comment by satra** [comment]
i think nipype at one point served a few more things including provenance. but it's true at this point it would be advantages to turn dcm2niix into a pydra task and switch to pydra with all the parallelization that's possible and make heudiconv much leaner.

**Comment by yarikoptic** [comment]
ok, manually bisected to https://github.com/nipy/nipype/pull/2936 which appears in the `git lg` (one line) with descriptive `rf+enh: dcm2niix` ;-)  it is `1.2.3~1^2` so we need at least that version
