### ISSUE TITLE
Incorrect echo times in multi-echo phase and single-band reference data

### ISSUE THREAD

**Issue by tsalo** [nipy/heudiconv#382]
### Summary

I have multi-echo, complex-valued EPI data with single-band reference images, and I ran it through the current version of heudiconv. The files are all generated and have the right names, but the json files for the functional phase data and both the magnitude and phase SBRefs have the wrong echo times and echo numbers. Each one has the first echo's TE for all echoes. It could be that the entire json files are also duplicated, but I don't know what other metadata should vary across echoes.

The multi-echo BOLD files look fine.

### Platform details:

Choose one:
- [ ] Local environment

- [X] Container: [adamkimbler/bidsify:latest](https://hub.docker.com/r/adamkimbler/bidsify)

- Heudiconv version: 202f9434819318055e5293486f6bdac489989c52

**Comment by tsalo** [comment]
Sorry about this. I just re-ran in the heudiconv Docker image and the metadata was all correct. It must be something I was doing in my workflow.

**Comment by yarikoptic** [comment]
thanks... although could still be some bug of non-deterministic execution (e.g. `dict` order somewhere)
