### ISSUE TITLE
Poor documentation of -d flag session handling

### ISSUE THREAD

**Issue by ariekahn** [nipy/heudiconv#383]
I just spent a while debugging my script with the same issue, and the fact that different tarballs are treated as different sessions really isn't made clear in the documentation, had to dig into the API to figure out why it was failing. It's also particularly unexpected behavior when I'm manually passing in a session (e.g. -d dicom/sub-{subject}/ses-{session}/*.tar.gz -ss 1). There really should be mention of this in the description of the -d flag.

See https://github.com/nipy/heudiconv/issues/262#issuecomment-429449925

**Comment by mgxd** [comment]
Hi @ariekahn - you are absolutely right that it is poorly documented. Would you care to submit a PR to make this behavior easily visible to future users?
