### ISSUE TITLE
KeyError: 'None'

### ISSUE THREAD

**Issue by heyeh** [nipy/heudiconv#391]
Dear experts,
I am trying to convert Dicom to BIDs for a group of subjects. It works well for most of the subjects. But for some subjects, it doesn't work for session 1 while work well for session 2 of the same subject. The error output is as below. I have tried just using dcm2nii on that dataset and it did work through.  I could not find any relevant issue on google. Could anyone help me with this?

docker run --rm -it -v ${ana_dir}:/base nipy/heudiconv:latest \
          -d /base/tempDCM/{subject}/sess_{session}/*.dcm \
          -o /base/Nifti/ \
          -f /base/templates/heuristic.py \
          -s ${sub_id} -ss ${sess} -c dcm2niix -b --overwrite \

INFO: Running heudiconv version 0.6.0.dev1
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 'C01065', 'outdir': '/base/Nifti/', 'session': '01'}
INFO: Processing 6055 dicoms
INFO: Analyzing 6055 dicoms
/src/heudiconv/heudiconv/dicoms.py:58: UserWarning: The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment
Please use with caution.  We would be grateful for your help in improving them
  import nibabel.nicom.dicomwrappers as dw
INFO: Generated sequence info with 16 entries
INFO: Doing conversion using dcm2niix
Traceback (most recent call last):
  File "/src/heudiconv/heudiconv/convert.py", line 71, in conversion_info
    files = filegroup[item]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 127, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 323, in process_args
    dcmconfig=args.dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 189, in prep_conversion
    cinfo = conversion_info(anon_sid, tdir, info, filegroup, ses)
  File "/src/heudiconv/heudiconv/convert.py", line 74, in conversion_info
    files = filegroup[(str if PY3 else unicode)(item)]
KeyError: 'None'

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container docker

- Heudiconv version:

**Comment by heyeh** [comment]
import os

def create_key(template, outtype=('nii.gz',), annotation_classes=None):
    if template is None or not template:
        raise ValueError('Template must be a valid format string')
    return template, outtype, annotation_classes


def infotodict(seqinfo):
    """Heuristic evaluator for determining which runs belong where

    allowed template fields - follow python string module:

    item: index within category
    subject: participant id
    seqitem: run number during scanning
    subindex: sub index within group
    """
    # anat
    t1 = create_key('sub-{subject}/{session}/anat/sub-{subject}_{session}_run-{item:01d}_T1w')
    t2 = create_key('sub-{subject}/{session}/anat/sub-{subject}_{session}_T2w')

    # func
    rest = create_key('sub-{subject}/{session}/func/sub-{subject}_{session}_task-rest_run-{item:01d}_bold')
    trailer = create_key('sub-{subject}/{session}/func/sub-{subject}_{session}_task-trailer_run-{item:01d}_bold')


    # dwi -- *** THIS IS NOT QUITE RIGHT YET BUT NOT IMPORTANT RIGHT NOW ***
    dwi80ap = create_key('sub-{subject}/{session}/dwi/sub-{subject}_{session}_acq-dir80ap_dwi')
    dwi80pab0 = create_key('sub-{subject}/{session}/dwi/sub-{subject}_{session}_acq-dir80pab0_run-{item:01d}_dwi')

    # sbref
    restsb = create_key('sub-{subject}/{session}/func/sub-{subject}_{session}_task-rest_run-{item:01d}_sbref')
    trailersb = create_key('sub-{subject}/{session}/func/sub-{subject}_{session}_task-trailer_run-{item:01d}_sbref')

    rest_fmap_ap = create_key('sub-{subject}/{session}/fmap/sub-{subject}_{session}_dir-AP_acq-rest_run-{item:01d}_epi')
    rest_fmap_pa = create_key('sub-{subject}/{session}/fmap/sub-{subject}_{session}_dir-PA_acq-rest_run-{item:01d}_epi')
    trailer_fmap_ap = create_key('sub-{subject}/{session}/fmap/sub-{subject}_{session}_dir-AP_acq-trailer_run-{item:01d}_epi')
    trailer_fmap_pa = create_key('sub-{subject}/{session}/fmap/sub-{subject}_{session}_dir-PA_acq-trailer_run-{item:01d}_epi')

    # for custom per-run FM handling
    current_fm_ap = None
    current_fm_pa = None

#    info = {t1: [], t1comp: [], t2: [],
    info = {t1: [], t2: [],
            rest: [], trailer: [], office: [], pixar: [], bang: [], dwi80ap: [], dwi80pab0: [],
            restsb: [], trailersb: [], officesb: [], pixarsb: [], bangsb: [],
            rest_fmap_ap: [], rest_fmap_pa: [], trailer_fmap_ap: [], trailer_fmap_pa: [], office_fmap_ap: [], office_fmap_pa: [],
            pixar_fmap_ap: [], pixar_fmap_pa: [], bang_fmap_ap: [], bang_fmap_pa: []
    }

    for idx, s in enumerate(seqinfo):

      is_sbref = 'SBRef' in s.series_description

      # ignore audiotest and scout
      if 'Scout' in s.series_description:
         pass
      elif 'Audiotest' in s.series_description:
         pass

      # t1
      elif 'tfl_mgh_multiecho' in s.series_description:
         if (s.dim3 == 704) and (s.dim4 ==1):
            if info[t1] is not None:
               info[t1]=[s.series_id]
      # t2
      elif 'T2w_SPC' in s.series_description:
         info[t2] = [s.series_id]

      # fieldmaps -- NEED TO IMPROVE LOGIC
      elif 'SpinEchoFieldMap' in s.series_description:
         if 'AP' in s.series_description:
           #info[fmap_ap].append(s.series_id)
           current_fm_ap = s.series_id
         else:
           #info[fmap_pa].append(s.series_id)
           current_fm_pa = s.series_id

      # diffusion
      elif 'DWI' in s.series_description:
         if 'B0_only' in s.series_description:
            info[dwi80pab0] = [ s.series_id ]
         else:
            info[dwi80ap] = [ s.series_id ]

      # func
      elif 'rfMRI_REST' in s.series_description:
         if is_sbref:
            info[restsb].append(s.series_id)
         else:
            info[rest].append(s.series_id)
            info[rest_fmap_ap].append(current_fm_ap)
            info[rest_fmap_pa].append(current_fm_pa)

      elif 'rfMRI_TRAILER' in s.series_description:
         if is_sbref:
            info[trailersb].append(s.series_id)
         else:
            info[trailer].append(s.series_id)
            info[trailer_fmap_ap].append(current_fm_ap)
            info[trailer_fmap_pa].append(current_fm_pa)

    return info

**Comment by yarikoptic** [comment]
My wild guess is that in your heuristic in one of the functions you forgot to return the actual value you intended to return

**Comment by heyeh** [comment]
Thanks for the reply.
