### ISSUE TITLE
Provide _sessions.tsv for multi-session datasets

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#397]
See https://bids-specification.readthedocs.io/en/stable/05-longitudinal-and-multi-site-studies.html

- Should as _scans.tsv files have `randstr`.
- Should also be a subject to optional dates annonimization (TODO https://github.com/nipy/heudiconv/issues/92)

**Comment by darrencl** [comment]
I think this issue is opened in #361

**Comment by yarikoptic** [comment]
Oh hoh, thank you! Closing as duplicate. I will follow up on that one later on.
