### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'annex_version'

### ISSUE THREAD

**Issue by tedstrauss** [nipy/heudiconv#411]
It seems that heudiconv 0.6.0 is not compatible with datalad 0.12.2:
```
$ heudiconv -f reproin --bids --datalad --files ../dcm_tar/pTIF0002_20200129_161954623.tar.gz -o . -s 00002 --minmeta 
INFO: Running heudiconv version 0.6.0 latest 0.6.0
INFO: Analyzing 41854 dicoms
INFO: Filtering out 0 dicoms based on their filename
/home/bic/tstrauss/env/datalad/lib/python3.6/site-packages/heudiconv/dicoms.py:58: UserWarning: The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment
Please use with caution.  We would be grateful for your help in improving them
  import nibabel.nicom.dicomwrappers as dw
INFO: Generated sequence info for 1 studies with 31 entries total
INFO: Processing sequence infos to deduce study/session
INFO: Study session for {'locator': 'IturiaMedina/Yaneva/pTIF_fingerprint', 'session': None, 'subject': '20.01.2914:57:26std1.3.12.2.1107.5.2.43.167017'}
INFO: Need to process 1 study sessions
INFO: Initiating <Dataset path=/scratch/box/git/pTIF0002>
Traceback (most recent call last):
  File "/home/bic/tstrauss/env/datalad/bin/heudiconv", line 8, in <module>
    sys.exit(main())
  File "/home/bic/tstrauss/env/datalad/lib/python3.6/site-packages/heudiconv/cli/run.py", line 128, in main
    process_args(args)
  File "/home/bic/tstrauss/env/datalad/lib/python3.6/site-packages/heudiconv/cli/run.py", line 328, in process_args
    args.bids_options)
  File "/home/bic/tstrauss/env/datalad/lib/python3.6/site-packages/heudiconv/external/dlad.py", line 30, in prepare_datalad
    bids=bids)
  File "/home/bic/tstrauss/env/datalad/lib/python3.6/site-packages/heudiconv/external/dlad.py", line 66, in add_to_datalad
    **create_kwargs
  File "/home/bic/tstrauss/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/bic/tstrauss/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py", line 480, in return_func
    results = list(results)
  File "/home/bic/tstrauss/env/datalad/lib/python3.6/site-packages/datalad/interface/utils.py", line 401, in generator_func
    wrapped(*_args, **_kwargs),
TypeError: __call__() got an unexpected keyword argument 'annex_version'
```
<details><summary>DataLad 0.12.2 WTF (configuration, datalad, dependencies, environment, extensions, git-annex, location, metadata_extractors, python, system)</summary>

# WTF
## datalad 
  - full_version: 0.12.2
  - version: 0.12.2
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:annex: 7.20190819+git2-g908476a9b-1~ndall+1
  - cmd:bundled-git: 2.20.1
  - cmd:git: 2.20.1
  - cmd:system-git: 2.17.1
  - cmd:system-ssh: 7.6p1
  - git: 3.0.7
  - gitdb: 2.0.6
  - humanize: 1.0.0
  - iso8601: 0.1.12
  - keyring: 21.1.0
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.2
  - requests: 2.22.0
  - wrapt: 1.11.2
## environment 
  - GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
  - LANG: en_CA.UTF-8
  - LC_ALL: en_CA.UTF-8
  - PATH: /home/bic/tstrauss/env/datalad/bin:/usr/local/go/bin:/home/bic/tstrauss/gems/bin:/home/bic/tstrauss/gems/bin:/etc/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/bin:/usr/local/bic/bin:/home/bic/tstrauss/.rvm/bin:/home/bic/tstrauss/go/bin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20190819+git2-g908476a9b-1~ndall+1
## location 
  - path: /scratch/box/git/pTIF0002
  - type: directory
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.6.8
## system 
  - distribution: Ubuntu/18.04/bionic
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 281
  - name: Linux
  - release: 4.18.0-14-lowlatency
  - type: posix
  - version: #15~18.04.1-Ubuntu SMP PREEMPT Mon Jan 14 12:02:55 UTC 2019
</details>

**Comment by yarikoptic** [comment]
I believe it was addressed by https://github.com/nipy/heudiconv/pull/415
