### ISSUE TITLE
Add a flag to support multiple sessions?

### ISSUE THREAD

**Issue by zhenghanQ** [nipy/heudiconv#43]
It would be great if heudiconv could automatically recognize multiple sessions of dicoms from the same subject ID and organize nifti files into separate session folders.

**Comment by yarikoptic** [comment]
FWIW although without a flag, in https://github.com/nipy/heudiconv/pull/32 (not sure now if we ever would be able to fix it up to be mergeable again since we did diverge from original heudiconv principle imho) we do support that.  We first sort/group all incoming dicoms into corresponding studies and their output directories (based on Study Description) and then use session indicator within a name of one of the sequences in the study to identify the session.

**Comment by CatherineMorganII** [comment]
hi

I'm trying to work out how to use the session flag? Currently we have dicom images where the session is encoded in the subject ID/name assigned to the images on the scanner, e.g. ADPRC_0057_F0, F0 is the session field, then the next session will be ADPRC_0057_F1.

I'm aiming to get to this BIDs converted structure:

/data/
sourcedata/
sub-ADPRC0057/
ses-F0/
anat/
...

I was going to code these folders myself but see that session is supported as option in heudiconv, but I can't work out how to pass the session info to heudiconv?

I've tried:

>>docker run --rm -it -v $input_data_dir:/data_current -v $python_heuristic_file:/data_current/heuristic_for_conversion.py nipy/heudiconv -d /data_current/{subject}{session}/* -s ADPRC0057 -f /data_current/heuristic_for_conversion.py -c dcm2niix -b --minmeta -o /data_current/output
>>INFO: Need to process 0 study sessions

any help gratefully received

Also I looked at the example heuristic for sessions:
 heudiconv/heuristics/bids_with_ses.py

which has this, 
 t1 = create_key('{session}/anat/sub-{subject}_T1w', outtype=and_dicom)

but looking at the bids spec doc shouldn't it be:
 t1 = create_key('{session}/anat/sub-{subject}_ses-{session}_T1w', outtype=and_dicom)

i.e. the session is in the file name too?

**Comment by yarikoptic** [comment]
Quick one:
- you could extract session within your heuristic. You could check dbic_bids heuristic how we do it (from sequence names)
- you found a bug I think, submit  a PR?

**Comment by yarikoptic** [comment]
overall -- we do support session specification in CLI (`-ss`) and heuristics (e.g. look at reproin) can deduce session from seqinfo (reproin uses a dedicated `_ses-?` in one/all of the sequence names e.g. scout). Overall, I think it is supported. Feel welcome to reopen if you feel there is more to be done
