### ISSUE TITLE
Make main workflow callable from Python

### ISSUE THREAD

**Issue by tsalo** [nipy/heudiconv#440]
### Summary

Currently, heudiconv's main workflow is included in the same function that parses the CLI arguments. With a little refactoring, we could separate these two a bit to allow users to call heudiconv from within Python. I think it would be fairly easy, and it would help users like me who prefer to call heudiconv within larger Python scripts.

This is somewhat related to [this NeuroStars post](https://neurostars.org/t/is-there-any-way-to-use-dcm2bids-or-neudiconv-with-python/4949) (specifically point 2).

**Comment by mgxd** [comment]
FWIW, we hack around this in the tests like so:
https://github.com/nipy/heudiconv/blob/a1a7cb594c5c0584868593c4516cccf4700689df/heudiconv/tests/test_regression.py#L8

although definitely onboard with separating the workflow into its own function / script.
