### ISSUE TITLE
Retain sub-second resolution in acq_time column of scans tsv files

### ISSUE THREAD

**Issue by tsalo** [nipy/heudiconv#447]
### Summary

I am working on a method to synchronize physio data from either BioPac or Labchart with BIDS-format scan data in order to convert the physio data to BIDS format (see https://github.com/physiopy/phys2bids/pull/219). This requires sub-second acquisition timing information from the scan data. At the moment, I use the `AcquisitionTime` field heudiconv retains in the json files, but I think that the scans.tsv file would be easier to access. The only unfortunate thing is that, in the conversion, sub-second timing information is discarded. See below:

https://github.com/nipy/heudiconv/blob/5681e0dce5250745c7c2f58866c5e86a93667fc4/heudiconv/bids.py#L407-L411

If that information could be retained, it would make it easier to synchronize the scans with externally-acquired data, including physio.

**Comment by yarikoptic** [comment]
indeed, I see no immediate reason why we did not store sub-second resolution.  Probably with multi-second TRs etc we simply did not care enough. heh heh
