### ISSUE TITLE
Point nipy.org/heudiconv to RTD

### ISSUE THREAD

**Issue by effigies** [nipy/heudiconv#448]
### Summary

My default for looking for Heudiconv documentation is https://nipy.org/heudiconv, which is currently a presentation from 2018. Might be some work, but it would be nice if presentations were moved under the main documentation structure, and the main Nipy.org site point to the [full docs](https://heudiconv.readthedocs.io/en/latest/).

**Comment by yarikoptic** [comment]
I am confused a bit -- where is the "source" of that url?
https://nipy.org/ lists now heudiconv, no hits for heudiconv while searching within https://github.com/nipy/nipy.github.com .

**Comment by effigies** [comment]
It's the `gh-pages` branch of heudiconv. Each `nipy` project, if it has GitHub pages enabled, will get those pages rendered on `nipy.org/<project>`.

**Comment by yarikoptic** [comment]
d'oh -- right, thanks!  I will submit a PR shortly

**Comment by effigies** [comment]
Thanks!
