### ISSUE TITLE
Issue caused by filelock of heudicov 0.8.0 

### ISSUE THREAD

**Issue by hcp4715** [nipy/heudiconv#457]
### Summary
The new version of heudiconv will lock all the files, which caused a problem: it can’t be modified by BIDSonym. which means that I need to change the permission of the T1 file and then run BIDSonym or crop the T1 data.

I tried to disable this function but can't  find  a solution in the tutorial, which is still based on 0.5.4
Just had a brief chat with @PeerHerholz, we thought it's better to open a new issue on this.

Here is the code I used:
```
singularity run --cleanenv \
-B /home/Data/Nipy:/base \
/home/docker_images/heudiconv-0.8.0.simg \
-d /base/Dicom/sub-{subject}/ses-{session}/*/* \
-o /base/BIDS/ \
-f /base/heuristic/heuristic_d1.py \
-s 001 \
-ss d1 \
-c dcm2niix \
-b --overwrite --minmeta
```
### Platform details:

Choose one:
- [x] Local environment
Ubuntu 20.04

- [x] Container
singularity

- Heudiconv version: 
0.8.0

This question has been posted on neurostar: https://neurostars.org/t/file-lock-of-heudicov-0-8-0-and-bidsonym/6801

**Comment by yarikoptic** [comment]
what exactly do you mean by "lock all the files" (we do have some locking but that should not anyhow interfere with external processes)?  Or do you mean it makes those files "read-only"?
copy/pasted output of an error would have been useful

**Comment by yarikoptic** [comment]
we do seems to make those files readonly indeed, but I would take it as a feature I guess, which seems had been there for a while:
```
15940b72 (Matteo Visconti di Oleggio Castello 2018-02-08 14:18:44 -0500 496)         if outname and op.exists(outname):
1467d072 (Mathias Goncalves                   2017-10-20 18:22:58 -0400 497)             set_readonly(outname)
```
modifying raw files inplace makes them non raw really, and I guess that is what we tried to avoid - any side effects.  If someone (a tool) wants to modify those files **inplace** -- it better takes care about permissions.  It could also just remove them before writing a "replacement" in place.  I believe in some defacing scripts we even moved that original file under `sourcedata/` (and not shared publicly) to retain the original source file (while also retaining its RO attribute).
Overall, I consider it a feature and a good practice to adhere to by default.  Someone might want to add an option to disable it explicitly.  If external tool is to modify that file -- just chmod it explicitly first or tune that tool to do that.

**Comment by hcp4715** [comment]
Hi, @yarikoptic ,
Thanks for your quick response.

> Or do you mean it makes those files "read-only"?

Yes, that's what meant.

I have a special situation other than deface: my T1 data have a FOV of 300 * 300, which need to be cropped to 256 * 256 before using fmriprep.

I agree make files RO is a good practice, great suggestion to move the original file under `sourcedata/`

**Comment by yarikoptic** [comment]
FWIW filed https://github.com/PeerHerholz/BIDSonym/issues/23
