### ISSUE TITLE
Participants.tsv will null values

### ISSUE THREAD

**Issue by JoshuaUrrutia** [nipy/heudiconv#499]
### Summary

In participants.tsv age and sex have null values (empty cells) instead of a 'n/a', which causes bids validation to fail.

I'm not sure these N/A replacements catch all the edge cases:
https://github.com/nipy/heudiconv/blob/master/heudiconv/bids.py#L285

I would've expected age to be fixed by this commit:
https://github.com/nipy/heudiconv/commit/7a7ef5c5f9852ef2b479aafcd5e09e462a08193c#diff-9f5ed69cb0b31e87bd735166c54cbd41b50710d545dc0e48d4d42f21269271c2

But I believe the n/a replacement for sex has been around awhile, and is in the version I'm using (0.9.0), but sex is still missing from participants.tsv.

ex:
```
participant_id	age	sex	group
sub-111			        control
```
Yarik, you can checkout the UIC sub-travhuman data for an example.

I sorted this out on my own with pandas and numpy:
```
import pandas as pd
import numpy as np
participants_df = pd.read_csv('participants.tsv', sep='\t')
participants_df = participants_df.replace(np.nan, 'n/a')
participants_df.to_csv('participants.tsv', sep="\t")
```
but it's probably worth doing within heudiconv. 

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container

Docker container: nipy/heudiconv:0.9.0

- Heudiconv version: 0.9.0

Thanks,
Joshua

**Comment by yarikoptic** [comment]
v0.9.0-14-g7a7ef5c fixed it for sex but we still have `age.lstrip('0').rstrip('Y') if age else 'N/A'` for age... so PR is coming shortly to fix it all up and improve a bit more
