### ISSUE TITLE
Add support for conversion to NDAR

### ISSUE THREAD

**Issue by satra** [nipy/heudiconv#5]

**Comment by yarikoptic** [comment]
what would that actually entail since NDA (formerly NDAR) doesn't care about file system layout... just preparing scans meta-data to popular some columns of the image03? ;)

**Comment by satra** [comment]
this is now fixed with `heudiconv -> bids` and then `bids -> nda` - @mgxd is preparing a dataset for submission due next week.

**Comment by chrisfilo** [comment]
This is the BIDS2NDA converter: https://github.com/INCF/BIDS2NDA
