### ISSUE TITLE
Error when dicom dir name contains parenthesis

### ISSUE THREAD

**Issue by hbraunDSP** [nipy/heudiconv#505]
### Summary

Heudiconv is failing on my new heuristic file, and I'm pretty sure it's because one of my test dicoms has parentheses in the name.  The relevant section of heudiconv's output is below:

```
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixrza0aeyq/convert".
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b n -z y -x n -t n -m n -f MR-SE027-mIP_Images(SW)_SE027_7T_heudiconv379 -o /home/udall-raid3/DBS_testing/data/organize_7T/test_output_20210419201540747786/SLEEP128_V2/SLEEP128_V2/ses-SLEEP128_V2_20191120_7T/Data_Nifti -s n -v n /tmp/dcm2niixrza0aeyq/convert
INFO: stderr 2021-04-19T20:17:47.372999:/bin/sh: -c: line 0: syntax error near unexpected token `('
INFO: stderr 2021-04-19T20:17:47.372999:/bin/sh: -c: line 0: `dcm2niix -b n -z y -x n -t n -m n -f MR-SE027-mIP_Images(SW)_SE027_7T_heudiconv379 -o /home/udall-raid3/DBS_testing/data/organize_7T/test_output_20210419201540747786/SLEEP128_V2/SLEEP128_V2/ses-SLEEP128_V2_20191120_7T/Data_Nifti -s n -v n /tmp/dcm2niixrza0aeyq/convert'
INFO: [Node] Finished "convert".
Traceback (most recent call last):
  File "/home/naxos2-raid9/hbraun/.conda/envs/dbsdev/bin/heudiconv", line 10, in <module>
    sys.exit(main())
  File "/home/naxos2-raid9/hbraun/.conda/envs/dbsdev/lib/python3.6/site-packages/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/home/naxos2-raid9/hbraun/.conda/envs/dbsdev/lib/python3.6/site-packages/heudiconv/main.py", line 351, in workflow
    grouping=grouping,)
  File "/home/naxos2-raid9/hbraun/.conda/envs/dbsdev/lib/python3.6/site-packages/heudiconv/convert.py", line 216, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/home/naxos2-raid9/hbraun/.conda/envs/dbsdev/lib/python3.6/site-packages/heudiconv/convert.py", line 501, in convert
    add_taskname_to_infofile(bids_outfiles)
  File "/home/naxos2-raid9/hbraun/.conda/envs/dbsdev/lib/python3.6/site-packages/heudiconv/convert.py", line 798, in add_taskname_to_infofile
    meta_info = load_json(infofile)
  File "/home/naxos2-raid9/hbraun/.conda/envs/dbsdev/lib/python3.6/site-packages/heudiconv/utils.py", line 177, in load_json
    with open(filename, 'r') as fp:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

If I modify my heuristic file to ignore any dirs with "(" in the name, the problem goes away.  I think the solution is to enclose the input file in quotes in the call to dcm2niix, like so:
`dcm2niix -b n -z y -x n -t n -m n -f "MR-SE027-mIP_Images(SW)_SE027_7T_heudiconv379" -o /home/udall-raid3/DBS_testing/data/organize_7T/test_output_20210419201540747786/SLEEP128_V2/SLEEP128_V2/ses-SLEEP128_V2_20191120_7T/Data_Nifti -s n -v n /tmp/dcm2niixrza0aeyq/convert`

This isn't a serious issue for me as I have no strong need to keep the parentheses; I'm just letting you know.
### Platform details:

Choose one:
- [x] Local environment

- [ ] Container

CentOS Linux release 7.9.2009 (Core), Python 3.6.8 :: Anaconda custom (64-bit)

- Heudiconv version:  0.9.0

**Comment by yarikoptic** [comment]
oh, smells like nipype issue. What version of nipype you have? attn @satra

**Comment by hbraunDSP** [comment]
This happened with nipype v1.4.0

**Comment by yarikoptic** [comment]
FTR: in reproin 0.9.0 container we have 1.6.0 and upstream seems to have 1.5.1 as the most recent (well, Sep 2020).  If you could check with some more recent one, would be appreciated so we avoid chasing a possibly already mediated issue.

**Comment by hbraunDSP** [comment]
I ran with nipype 1.6.0 and the images with parentheses were processed OK.  It looks like this has already been solved.

**Comment by yarikoptic** [comment]
Great, thanks!
