### ISSUE TITLE
Multiple nifti files after conversion of one protocol 

### ISSUE THREAD

**Issue by jli-bwh** [nipy/heudiconv#510]
### Summary

After running heudiconv using modified convert.py with dcm2niix on one T1 protocol, I am getting 4 different nifiti files with the following namings: 

sub-01_T1w_heudiconv422_e1.nii.gz  sub-01_T1w_heudiconv422_e3.nii.gz
sub-01_T1w_heudiconv422_e2.nii.gz  sub-01_T1w_heudiconv422_e4.nii.gz

Each file is slightly different in contrast and intensity but overall look the same. Any idea on why different nifti files are given from one dicom series and which one should I use?

### Platform details:

Choose one:
- [x] Container: Singularity

- Heudiconv version: 0.9.0

**Comment by yarikoptic** [comment]
well, most likely different preprocessing done on scanner.  I do not think it is anything for us to fix up (in particular for a "modified convert.py" ;))

**Comment by jli-bwh** [comment]
Thanks for the quick reply! Sorry for the confusion about 'modified convert.py'. I meant to say I modified the heuristics file with the following infotodict function based on the tsv file generated from heudiconv:

def infotodict(seqinfo):
    t1w = create_key('sub-{subject}/anat/sub-{subject}_T1w')
and 
     if (s.dim1 == 256) and (s.dim2 == 256) and (s.dim3 == 704) and ('T1' in s.series_description):
          info[t1w] = [s.series_id] 

You might be right that the files could be from different preprocessing done on scanner. Could the extention name heudiconv422_e1 to heudiconv422_e4 mean anything here? Also I didn't see four diferent preprocessing protocols in the tsv files so I was curious why they only come up after dcm2niix conversion. Thanks for your help!

**Comment by yarikoptic** [comment]
may be run with --bids and see what is different (if anything) among fields in sidecar .json files.  Also could try to run dcm2niix -b y directly on that set of dicoms to see what you would get.  Hard to say anything else useful from the information provided

**Comment by jli-bwh** [comment]
Thanks for the suggestions! Just tried running dcm2niix -b y directoly on that set of dicoms and it's also giving out four different nifti files with e1 to e4 extensions. Seems to be that multiple preprocessing were done at the scanner that we didn't know about. Thanks a lot!

**Comment by yarikoptic** [comment]
well, looking at 
https://github.com/rordenlab/dcm2niix//blob/HEAD/console/nii_dicom_batch.cpp#L2660
could it be a multiecho image?

**Comment by jli-bwh** [comment]
You are right! this is a multiecho image and I just found this thread from dcm2niix about supporting multiecho imaging issue
https://github.com/rordenlab/dcm2niix/issues/101 

This is our first time dealing with multiecho image. Would you have any advice on which image we should use out of the four or if there is any way we could combine them together?

**Comment by pvelasco** [comment]
> This is our first time dealing with multiecho image. Would you have any advice on which image we should use out of the four or if there is any way we could combine them together?

Yes, this is a ME-MPRAGE (or maybe a ME-GRE?).  You can take a look at the following reference, where they explain the advantages of ME-MPRAGE over standard MPRAGE (1 echo):
A. J. W. van der Kouwe, T. Benner, D. H. Salat, B. Fischl, Brain morphometry with multiecho MPRAGE, NeuroImage, 40, 559–569 (2008).

I'm surprised that the filenames you get are not BIDS-compliant (they should have "_echo-1", etc. instead of "_e1"). Perhaps @tsalo has an idea of why this fails? Maybe the echo times are not set correctly in the DICOM header? @jli-bwh , can you check the `'EchoTime'` in the four json files?

**Comment by jli-bwh** [comment]
This is indeed a ME-MPRAGE. Thanks for the reference on the advantages of ME-MPRAGE over MPRAGE! We didn't look closley at the protocol at first but good to know that we actually did it in a better way. Now we just need to look for ways to combine different echos and see if it's possible. 

The echo time for the four different echoes are the following:
"EchoTime": 0.00169
"EchoTime": 0.00355
"EchoTime": 0.00541
"EchoTime": 0.00727

Thank you for all your help!

**Comment by pvelasco** [comment]
> Now we just need to look for ways to combine different echos and see if it's possible.

I found in [NeuroStars](https://neurostars.org/t/memprage-rms-not-echoes-for-recon-all-with-fmriprep/4778) that people in the FreeSurfer mailing list suggest computing the RMS.  You can do that using, for example, `fslmaths`.
Then, if you want to use your combined image for fMRIPrep, you might have to remove the individual echoes out of the way.

If you don't need to use fMRIPrep, I think you can process all four echoes using FreeSurfer, and you can get a better cortical segmentation.

> The echo time for the four different echoes are the following.

In principle, `heudiconv` should have handled the different echoes correctly and you should have ended up with BIDS-compliant filenames.  If you are allowed to share the DICOMs for that run (if they are anonymized), you can post them somewhere in Google Drive, DropBox, etc. and I can take a look at it.

**Comment by pvelasco** [comment]
> If you are allowed to share the DICOMs for that run (if they are anonymized), you can post them somewhere in Google Drive, DropBox, etc. and I can take a look at it.

Never mind, I found an old dataset I collected on a phantom. I'll test it using it.

**Comment by pvelasco** [comment]
Hi @jli-bwh ,

I managed to convert the data successfully using the following heuristic (these are the contents of the whole file):

```(python)
import os

def create_key(subdir, file_suffix, outtype=('nii.gz'),
               annotation_classes=None, prefix=''):
    if not subdir:
        raise ValueError('subdir must be a valid format string')
    template = os.path.join(
        prefix,
        "{bids_subject_session_dir}",
        subdir,
        "{bids_subject_session_prefix}_%s" % file_suffix
    )
    return template, outtype, annotation_classes


def infotodict(seqinfo):
    t1 = create_key('anat','acq-{acq}_run-{item:02d}_T1w')
    info = {t1: [], }
    for s in seqinfo:
        if s.sequence_name.startswith('tfl_me3d'):
            info[t1].append({'item': s.series_id, 'acq': 'highres'})
        else:
            pass
    return info
```

I guess in your case, you can substitute the `if s.sequence...` line with:
```
if (s.dim1 == 256) and (s.dim2 == 256) and (s.dim3 == 704) and ('T1' in s.series_description)
```

Please let me know if this worked.

**Comment by jli-bwh** [comment]
Thank you Pablo for looking into this and suggesting the heuristic! Sorry for the late reply. I just tried the heuristic on the multi-echo t1 scan and heudiconv did run successfully to convert the scans into separate echoes. I would say the only problem is that there is 'heudiconv513' or 'heudiconv###' in the naming but I don't think that matters too much. For example, converted results have this kind of formats:

'sub-2001_ses-01_acq-highres_run-01_T1w_heudiconv513_e1.nii.gz'
'sub-2001_ses-01_acq-highres_run-01_T1w_heudiconv513_e2.nii.gz'
'sub-2001_ses-01_acq-highres_run-01_T1w_heudiconv513_e3.nii.gz'
'sub-2001_ses-01_acq-highres_run-01_T1w_heudiconv513_e4.nii.gz'

Thank you very much for your help!

**Comment by pvelasco** [comment]
Hi @jli-bwh,

If your data is shareable, you can put it somewhere and send me an email (first_name dot last_name at nyu dot edu) with the link. I will take a look to see what's going on...
