### ISSUE TITLE
dicom_dir_template with subject and session.

### ISSUE THREAD

**Issue by tsalo** [nipy/heudiconv#52]
In order to search using both subject and session, would it be possible to change the way dicom_dir_template is set up and formatted?

E.g., instead of 
```shell
heudiconv -d /scratch/tsalo006/DICOM/%s_S1/*/* \
	-s sub-05 -f /scratch/tsalo006/heuristics.py -c dcm2niix \
	-o ./ -ss 1
```
 we could have
```shell
heudiconv -d /scratch/tsalo006/DICOM/{s}_S{ss}/*/* \
	-s sub-05 -f /scratch/tsalo006/heuristics.py -c dcm2niix \
	-o ./ -ss 1
```

In `heudiconv`, instead of 
```python
if sid:
    sdir = dicom_dir_template % sid
    # and see what matches
    fl = sorted(glob(sdir))
```

there'd be
```python
if sid:
    # if ss isn't in the template it's just ignored
    sdir = dicom_dir_template.format(s=sid, ss=ses)
    # and see what matches
    fl = sorted(glob(sdir))
```

**Comment by satra** [comment]
@tsalo - this sounds good, perhaps we can use `{participant}` and `{session}` in the template and make things as clear as possible. 

would you like to send a PR?

**Comment by tsalo** [comment]
Sounds good. Opened #54 with these changes.

**Comment by tsalo** [comment]
Since the PR was merged I think I can close this.
