### ISSUE TITLE
Some bidsification outputs are missing

### ISSUE THREAD

**Issue by m-petersen** [nipy/heudiconv#524]
### Summary

I aim for bids conversion of T1w images for a longitudinal structural analysis using heudiconv. For most sessions of the subjects conversion is successful. However, in some cases outputs are missing, although the correct output directory (sub-xyz/ses-0/anat) is created, the DCM I want to convert is mentioned in .heudiconv/info/dicominfo.tsv (
dim1 | dim2 | dim3 | dim4 | TR | TE | protocol_name
560 | 560 | 406 | 1 | 0.00835830020904541 | 3.801 | CS sag T1W_3D_TFE nativ
) and the conversion is mentioned in the outputs (no error messages). 

 ```
INFO: PROCESSING STARTS: {'subject': 'GWHH100', 'outdir': '/bids/', 'session': '09'}
INFO: Processing 3477 dicoms
INFO: Reloading existing filegroup.json because /bids/.heudiconv/GWHH100/ses-09/info/GWHH100_ses-09.edit.txt exist
INFO: Converting /bids/sub-GWHH100/ses-09/anat/sub-GWHH100_ses-09_T1w (406 DICOMs) -> /bids/sub-GWHH100/ses-09/anat . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixdoi1q1dx/convert".
```

Until now I haven't found any differences between the files of successful and non-successful conversion examples.

The heudiconv command I use is

```
      CMD="
      heudiconv \
      -d /dcm/{subject}/ses-{session}.tar.gz\
      --subjects $1 \
      --ses $SESSION \
      --bids notop \
      -f /code/pipelines/bidsify/$HEURISTIC\
      -c dcm2niix \
      --minmeta \
      --overwrite\
      --grouping accession_number \
      -o /bids"
      singularity run --cleanenv --userns \
      --home $PWD \
      -B $CODE_DIR:/code \
      -B $BIDS_DIR:/bids \
      -B $DCM_DIR:/dcm \
      -B $TMP_DIR:/tmp \
      $ENV_DIR/heudiconv-0.9.0 \
      $CMD
```

Grateful for any input.

Cheers,
Marvin

### Platform details:

Choose one:
- [ ] Local environment

- [ x] Container
heudiconv-0.9.0

The admittedly messy log files (I parallelize command execution using GNU parallel with --ungroup to get immediate outputs)
[1476444-bidsify-0-15092021_err.txt](https://github.com/nipy/heudiconv/files/7170179/1476444-bidsify-0-15092021_err.txt)
[1476444-bidsify-0-15092021_out.txt](https://github.com/nipy/heudiconv/files/7170181/1476444-bidsify-0-15092021_out.txt)

**Comment by yarikoptic** [comment]
errors are there:
```
lena:/tmp
$> grep Error 1476444-bidsify-0-15092021_err.txt
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/tmp/heudiconvDCMxmeoakyt/ses-01/1.3.46.670589.11.71363.5.0.7928.2019102308124720859/1.3.46.670589.11.71363.5.0.7928.2019102308165414019.dcm' <class 'str'> was specified.
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/tmp/heudiconvDCMt_n9n8u8/ses-08/1.3.46.670589.11.71363.5.0.7692.2020070710151891616/1.3.46.670589.11.71363.5.0.7692.2020070710192554991.dcm' <class 'str'> was specified.
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/tmp/heudiconvDCMdy5ijnl9/ses-08/1.3.46.670589.11.71363.5.0.6484.2020072108034646220/1.3.46.670589.11.71363.5.0.6484.2020072108075511606.dcm' <class 'str'> was specified.
    raise TraitError(
traits.trait_errors.TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/tmp/heudiconvDCMceb0gbp7/ses-09/1.3.46.670589.11.71363.5.0.7892.2020042911342857707/1.3.46.670589.11.71363.5.0.7892.2020042911382597735.dcm' <class 'str'> was specified.
```

[search](https://github.com/nipy/heudiconv/search?q=Each+element+of+the+%27source_names%27+trait+of+a+Dcm2niixInputSpec+instance+must+be+a+pathlike+object+or+string+representing+an+existing+file%2C+but+a+value) on that error seems to bring no hits here among issues -- "congratulations", seems to be a new one. Most likely some race condition somewhere unless you will find that  for e.g. `1.3.46.670589.11.71363.5.0.7892.2020042911342857707` in original tarball that file (`1.3.46.670589.11.71363.5.0.7892.2020042911382597735.dcm`) is missing although may be present in some DICOMDIR or smth like that?

**Comment by m-petersen** [comment]
Hi Yaroslav,

apologies. Blame my tired eyes ;)

```
tar -tvf ses-09.tar.gz | grep 1.3.46.6705
89.11.71363.5.0.7892.2020042911382597735.dcm
-rwxr-xr-x fatx405/hpc_ag_thomalla  631092 2021-09-02 20:37 ses-09/1.3.46.670589.11.71363.5.0.7892.2020042911342857707/1.3.46.670589.11.71363.5.0.7892.2020042911382597735.dcm
```

The dcm file exists in the tarball. I'll rerun incomplete subjects individually to look whether race condition could be the culprit.

**Comment by m-petersen** [comment]
Once again, thanks for your help. Running subjects individually yields the expected bidsification.

**Comment by yarikoptic** [comment]
at least you have a workaround.  ATM I have no clear idea on what could be racing with what given that  eare talking about random temp directories... it is all odd.  the only thing I would have checked -- size under that `/tmp` across all those hosts where jobs were running/failed (didn't check if log has that info --  we might want to add a hostname into logs!)
