### ISSUE TITLE
How to define a custom grouping in heuristic file?

### ISSUE THREAD

**Issue by BlackHoleExelion** [nipy/heudiconv#531]
When using ```--grouping custom```, I got an error saying ```RuntimeError: Custom grouping is not defined in heuristic```. But there is not much info in both heudiconv doc and tutorials about how to define a custom grouping. Could you please show me how to do it? Thanks!

**Comment by yarikoptic** [comment]
sorry about such a long delay with following up on this issue. If still of interest -- we have minimal documentation now for that aspect at 
https://heudiconv.readthedocs.io/en/latest/heuristics.html?highlight=grouping#grouping-string-or-grouping-files-dcmfilter-seqinfo
