### ISSUE TITLE
Updated Docker/Singularity

### ISSUE THREAD

**Issue by araikes** [nipy/heudiconv#538]
### Summary

Is there an v 0.10.0 Docker image? Trying to run this on our HPC and it looks like DockerHub is only updated to 0.9.0.

Thanks

### Platform details:

Choose one:
- [ ] Local environment

- [x ] Container

- Heudiconv version:

**Comment by yarikoptic** [comment]
eh, with docker hub stopping providing free builds from github repos, we fell out of date.  I guess I need to build one and push manually for now. Later we should automate that.

**Comment by jbdenniso** [comment]
Sorry to bug but I'm hoping for an update or maybe a link to some documentation for building a docker/singularity image from what is in the github repo. Specifically there's some changes for multi-echo images I'd like to take advantage of.
Best

**Comment by crcox** [comment]
I second @jbdenniso, the Docker container does not process my multi-echo data properly, but the version I install from Pip does.

**Comment by yarikoptic** [comment]
Dear everyone -- sorry for the delays... I was hoping to kick out 0.11.0 with #544 included but , well, haven't gone there yet.  I guess we would need to build/push it manually for now... will try to do now...

**Comment by yarikoptic** [comment]
ok, now there is `0.10.0`, `latest` (the same as 0.10.0) and `master` builds on docker hub manually built/pushed. #557 and work therein would be for automating it all again (or we would just cash out to pay dockerhub for that...)
