### ISSUE TITLE
input variable is set instead of list in convert.py file, update_multiecho_name function

### ISSUE THREAD

**Issue by vinferrer** [nipy/heudiconv#548]
### Summary

Hello there,
I notice a posible bug in heudiconv code, it affects to the `convert.py` file `update_multiecho_name`.
It seems like somehow the input variable `echo_times` can be a `set` instead of a `list` therefore the line:
https://github.com/nipy/heudiconv/blob/cb2fd912b8310d7022e9358a84c3b589fe3c07e8/heudiconv/convert.py#L350
fails because the method `index` exists for list object not for sets.

Solution:
`echo_times= list(echo_times)`

### Platform details:

Choose one:
- [x] Local environment

- [ ] Container

python 3.9, centOS
- Heudiconv version: 

0.10.0

**Comment by tsalo** [comment]
#461 should have fixed this (also reported in #460). Can you try it with the current version from GitHub?

**Comment by vinferrer** [comment]
Hello @tsalo, good to see you. It seems that the version from our cluster wasn't update so I installed the github version in a conda enviroment and everything seems to work. Let's close this. 
Thank you in any case.
Cheers,

**Comment by tsalo** [comment]
👋 Nice seeing you too.

I think it might be time for a new release, because this bug will probably affect everyone using heudiconv on multi-echo or complex-valued data. @yarikoptic do you think a 0.10.1 release would be worth doing?
