### ISSUE TITLE
Add `auto` and building/pushing of docker image

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#557]
Dear @jwodder -- need your help on this. We need to `auto`mate this poor soul since releasing is pain.  I can even go through already merged PRs since last release and label/adjust titles them as needed.  Please do the rest.

Also we need to automate building/pushing docker images to properly address https://github.com/nipy/heudiconv/issues/538 . Those are to be done at release time as well after successful releasing. `Dockerfile` is in the root of the repo and produced by  http://github.com/nipy/heudiconv/blob/HEAD/utils/gen-docker-image.sh script which I might need to adjust before next release.

**Comment by jwodder** [comment]
@yarikoptic What exactly does releasing entail, beyond just building & uploading to PyPI?

**Comment by yarikoptic** [comment]
d'oh -- in the best traditions of stone age tech it required boost of `__version__` in http://github.com/nipy/heudiconv/blob/HEAD/heudiconv/info.py . I think it would be great to also switch to use versioneer or your helper to automate -- I would really love to see `git describe` based versions.

**Comment by yarikoptic** [comment]
oh -- and there is http://github.com/nipy/heudiconv/blob/HEAD/utils/prep_release which calls (well -- called after moving to `auto`) `utils/link_issues_CHANGELOG` and does some other dances to embed new version in docs . If hard to accomplish -- I am ok to make those invocations more generic in the docs etc.
