### ISSUE TITLE
reproin: do come up with a way to annotate/convert derived data

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#574]
in some cases we can figure out what `_acq` or `_proc` entity to add (e.g. for motion correction) but it would be hard to impossible to assemble the knowledge about all preprocessings scanner could do to place them into BIDS entities... so, for reproin we should provide configuration way to say that such and such derived sequence should gain some specific BIDS entities and then we would not ignore but do convert them.

**Comment by neurorepro** [comment]
@yarikoptic I am currently relooking at #503 and implementing it as described there in reproin (ordered list of processing steps separated by "x" as discussed). Should i keep something else in mind when working on this PR ?

**Comment by yarikoptic** [comment]
I will consider this a duplicate of #503. 
- May be https://github.com/nipy/heudiconv/issues/266 could be of useful info as well with some wisdoms pointed to
