### ISSUE TITLE
question about using a dicom private tag in heuristic file

### ISSUE THREAD

**Issue by kcho** [nipy/heudiconv#580]
### Summary

Hi,

I'm working with Siemens XA30 data, and I'm trying to use the information contained in the private dicom header in re-arranging output names. Is there a way to extract private tag information and use this in my `heuristic` file?

I can extract the information that I need using `pydicom` with the following commands

```
from pydicom import dcmread
ds = dcmread('dicom.dcm')
ds[0x52009230][0][0x002111fe][0][0x00211175].value
```

Thanks for the great tool.

### Platform details:

Choose one:
- [x] Local environment

CentOS 3.10.0-862.14.4.el7.x86_64
python 3.7.3

- [ ] Container

- Heudiconv version: 

0.11.3

**Comment by yarikoptic** [comment]
there is https://github.com/nipy/heudiconv/pull/333 which I "resisted".  I guess it would have provided you with a remedy, right?

**Comment by kcho** [comment]
Thanks!
