### ISSUE TITLE
Addressing conversion of sequences acquired in two stages (still BIDS single session) 

### ISSUE THREAD

**Issue by neurorepro** [nipy/heudiconv#587]
According to [BIDS specifications](https://bids-specification.readthedocs.io/en/stable/99-appendices/14-glossary.html#session-entities) a session is a logical grouping of modalities, and in particular:
* if a subject has to leave the scanner room and then be re-positioned on the scanner bed, **the set of MRI acquisitions will still be considered as a session**
* in situations where different data types are obtained over several visits (for example fMRI on one day followed by DWI the day after) **those can be grouped in one session**

However when using `heudiconv` on an "interrupted session" only one set of sequences will be converted.

Is there any suggestion on how to best approach this situation ?

PS: working on it now but asking just in case a clear idea is already there

**Comment by neurorepro** [comment]
Solve with `--grouping all`, but didn't see in the help page ;)

**Comment by yarikoptic** [comment]
yes, `--grouping` was introduced specifically for that purpose. Glad you found it -- means that our docs aren't entirely hopeless ;)
