### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

### ISSUE THREAD

**Issue by megq** [nipy/heudiconv#598]
### Summary

Hello, I've run this same script to convert DICOMS to bids format a bunch of times for participants within this study, but this one appears to be erroring and I'm not sure why. They have all the correct files and I can't seem to find the issue.

I looked back at previous issues with similar errors and that fix didn't work for me unfortunately.

Thank you!

INFO: Running heudiconv version 0.5.4
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 's4111', 'outdir': '/out/bids/', 'session': None}
INFO: Processing 1304 dicoms
INFO: Reloading existing filegroup.json because /out/bids/.heudiconv/s4111/info/s4111.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Populating template files under /out/bids/
Traceback (most recent call last):
File "/opt/miniconda-latest/bin/heudiconv", line 11, in
load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
File "/src/heudiconv/heudiconv/cli/run.py", line 127, in main
process_args(args)
File "/src/heudiconv/heudiconv/cli/run.py", line 323, in process_args
dcmconfig=args.dcmconfig,)
File "/src/heudiconv/heudiconv/convert.py", line 212, in prep_conversion
getattr(heuristic, 'DEFAULT_FIELDS', {}))
File "/src/heudiconv/heudiconv/bids.py", line 77, in populate_bids_templates
populate_aggregated_jsons(path)
File "/src/heudiconv/heudiconv/bids.py", line 109, in populate_aggregated_jsons
json_ = load_json(fpath)
File "/src/heudiconv/heudiconv/utils.py", line 176, in load_json
data = json.load(fp)
File "/opt/miniconda-latest/lib/python3.6/json/init.py", line 296, in load
return loads(fp.read(),
File "/opt/miniconda-latest/lib/python3.6/codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
chmod: cannot access '/data/projects/STUDIES/SEAT/fMRI/bids/sub-s4111': No such file or directory

### Platform details:

Choose one:
- [ ] Local environment

- [x ] Container

singularity
singularity pull docker://nipy/heudiconv:0.5.4

- Heudiconv version: 

version 0.5.4

**Comment by yarikoptic** [comment]
> version 0.5.4

we have made earth a little more round since back those old times ;) e.g. in 0.6.0 we had 

  - Do not crash and store original .json file is "JSON pretification" fails
    ([#342][])

Please upgrade and feel welcome to reopen if issue persists.  If persists, run with `--dbg` option on, and then you should be able to enter `up` until you end up at `populate_aggregated_jsons` and then `p fpath` to see which path we are talking about, and please share that file if there is no sensitive information in it.

**Comment by LexHayes** [comment]
Hi,

I am having this same issue.
I am running heudiconv through docker - version 0.11.4
I have used the --dbg option and entered 'p fpath' at  'populate_aggregated_jsons' however this returned the error '*** NameError: name 'fpath' is not defined'

As above I have been running heudiconv with no issues for a while now so can not understand why this error is now present.

Thanks in advance!

**Comment by LexHayes** [comment]
Hi, 

Thanks for your reply!

The traceback is the same; 
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/src/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/src/heudiconv/heudiconv/main.py", line 393, in workflow
    grouping=grouping,)
  File "/src/heudiconv/heudiconv/convert.py", line 239, in prep_conversion
    getattr(heuristic, 'DEFAULT_FIELDS', {}))
  File "/src/heudiconv/heudiconv/bids.py", line 156, in populate_bids_templates
    populate_aggregated_jsons(path)
  File "/src/heudiconv/heudiconv/bids.py", line 189, in populate_aggregated_jsons
    json_ = load_json(fpath, retry=100)
  File "/src/heudiconv/heudiconv/utils.py", line 187, in load_json
    data = json.load(fp)
  File "/opt/miniconda-latest/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/opt/miniconda-latest/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte

I don't get a 'cannot access' error It does just seem to be related to the aggregated jsons

**Comment by yarikoptic** [comment]
ok, flood troubleshooting questions ;)

what is the content of  /output/sub-NK2026/ses-1/perf/sub-NK2026_ses-1_acq-pcasl_run-1_asl.json ?  

I thought that may be an empty .json would produce that error but not:

```
❯ touch /tmp/empty.json
❯ docker run -v /tmp:/tmp -it --rm --entrypoint /opt/miniconda-latest/bin/python nipy/heudiconv:latest -c 'from heudiconv.utils import load_json; print(load_json("/tmp/empty.json"))'
221025-18:42:57,279 nipype.utils WARNING:
	 A newer version (1.8.4) of nipy/nipype is available. You are using 1.8.0
WARNING: A newer version (1.8.4) of nipy/nipype is available. You are using 1.8.0
ERROR: /tmp/empty.json is not a valid json file
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/src/heudiconv/heudiconv/utils.py", line 187, in load_json
    data = json.load(fp)
  File "/opt/miniconda-latest/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/miniconda-latest/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/miniconda-latest/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/miniconda-latest/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
so looks different.  Would you mind showing output of `find -iname *.json -ls`?

BTW what is your host os?

**Comment by LexHayes** [comment]
Hi Thank you!

The contents of /output/sub-NK2026/ses-1/perf/sub-NK2026_ses-1_acq-pcasl_run-1_asl.json contains all the imaging parameters as expected.

I had previously, successfully ran heudiconv on other subjects and I have just tried again on these same participants and was faced with this same issue.

This is the outcome of find -iname *.json -ls
196025      256 -rwxrwxrwx    1 ah2816           staff               46892 25 Oct 17:45 ./ses-1/anat/sub-NK2026_ses-1_run-1_T1w.json
196028      256 -rwxrwxrwx    1 ah2816           staff               46481 25 Oct 17:46 ./ses-1/anat/sub-NK2026_ses-1_run-1_T2w.json
196030      256 -rwxrwxrwx    1 ah2816           staff                2712 25 Oct 17:46 ./ses-1/fmap/sub-NK2026_ses-1_run-1_magnitude1.json
196031      256 -rwxrwxrwx    1 ah2816           staff                2758 25 Oct 17:46 ./ses-1/fmap/sub-NK2026_ses-1_run-1_magnitude2.json
196032      256 -rwxrwxrwx    1 ah2816           staff                2824 25 Oct 17:46 ./ses-1/fmap/sub-NK2026_ses-1_run-2_magnitude1.json
196033      256 -rwxrwxrwx    1 ah2816           staff                2797 25 Oct 17:46 ./ses-1/fmap/sub-NK2026_ses-1_run-2_magnitude2.json
196034      256 -rwxrwxrwx    1 ah2816           staff               20517 25 Oct 17:46 ./ses-1/fmap/sub-NK2026_ses-1_run-1_phasediff.json
197329      256 -rwxrwxrwx    1 ah2816           staff               20624 25 Oct 17:46 ./ses-1/fmap/sub-NK2026_ses-1_run-2_phasediff.json
197331      256 -rwxrwxrwx    1 ah2816           staff               32157 25 Oct 17:46 ./ses-1/func/sub-NK2026_ses-1_task-cue_run-1_bold.json
197339      256 -rwxrwxrwx    1 ah2816           staff               27043 25 Oct 17:47 ./ses-1/func/sub-NK2026_ses-1_task-evo_run-1_bold.json
197340      256 -rwxrwxrwx    1 ah2816           staff               29687 25 Oct 17:47 ./ses-1/func/sub-NK2026_ses-1_task-mid_run-1_bold.json
197806      256 -rwxrwxrwx    1 ah2816           staff               31966 25 Oct 17:48 ./ses-1/func/sub-NK2026_ses-1_task-rest_run-1_bold.json
197808      256 -rwxrwxrwx    1 ah2816           staff                5729 25 Oct 17:48 ./ses-1/perf/sub-NK2026_ses-1_acq-pcasl_dir-pa_run-1_m0scan.json
197809      256 -rwxrwxrwx    1 ah2816           staff               10617 25 Oct 17:48 ./ses-1/perf/sub-NK2026_ses-1_acq-pcasl_run-1_asl.json
201870      256 -rwxrwxrwx    1 ah2816           staff                4096 26 Oct 13:28 ./ses-1/perf/._sub-NK2026_ses-1_acq-pcasl_run-1_asl.json

My host OS is Mac OS Moterey,.

THank You!

**Comment by yarikoptic** [comment]
> The contents of /output/sub-NK2026/ses-1/perf/sub-NK2026_ses-1_acq-pcasl_run-1_asl.json contains all the imaging parameters as expected.

well, the question is rather either it is json which could be opened... Try doing smth like

```
find -iname *.json | while read j; do docker run -v $PWD:/output -it --rm --entrypoint /opt/miniconda-latest/bin/python nipy/heudiconv:latest -c "from heudiconv.utils import load_json; print('$j', len(load_json('/output/$j')))"
```

(didn't try -- you might need to fix up) and tell me if it pukes on any of those jsons.
