### ISSUE TITLE
Missing echo-1 bold image from heudiconv output on multi-echo scan 

### ISSUE THREAD

**Issue by orizaff** [nipy/heudiconv#604]
### Summary

I’ve recently been running into an issue where, upon running heudiconv on a recent subject with multi-echo scans, the bold.nii.gz image for the first echo winds up missing from the output. (Sorry for the cross-post, I posted this on Neurostars the other day.)

Each subject has 6 fMRI runs, with different permutations of multiband acceleration and acquired echos. In the run with multiband 6 and multi-echo 4 for several of our recent subjects, the first of the four bold images (one for each echo) is missing. Typically, for this echo, the expected output would include mb6me4_echo-1_bold.json and mb6me4_echo-1_bold.nii.gz files, as it outputs for each of the other echos in this run (i.e. 2, 3, and 4). In this case, the initial _bold image (both for .json and .nii.gz) is missing.

The dicoms appear to have the same files as other subjects which have successfully generated this bold image. All contain identical structure and number of files for the multiband 6 multi-echo 4 run. I have also run dcm2niix directly and it generated all expected files without issue on a subject that had the missing bold image. Attached is a log of heudiconv's output from a subject where the issue occurred. Any suggestions for solutions or next steps are appreciated. I can provide the heuristics.py code, dicom info, and an example subject’s scans.tsv file (or any other code/info that might elucidate or recreate the issue) upon request!

### Platform details:

Choose one:
- [x] Local environment

- [ ] Container

Linux Mint 20, Python 3.8.5
- Heudiconv version: 0.10.0, dcm2niix version: 1.0.20181125

[log_heudiconv.txt](https://github.com/nipy/heudiconv/files/9842741/log_heudiconv.txt)

**Comment by orizaff** [comment]
Hello, we upgraded to Heudiconv version 0.11.4 and the issue went away. Apologies if this caused any confusion!

**Comment by yarikoptic** [comment]
Thanks for checking and coming back to close!
