### ISSUE TITLE
Gets unnecessary +dDATE added to a version corresponding to a clean release

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#606]
```shell
smaug:~
$> docker run -it --rm --entrypoint bash -v /tmp/mount:/mnt:ro -v /tmp/mount/rw:/mnt/rw:rw nipy/heudiconv:v0.11.5 -c 'python -c "import heudiconv;print(heudiconv.__version__)"'
0.11.5+d20221103
```

I guess done by https://github.com/jwodder/versioningit . Not sure if it is a bug in versioningit or matter of some configuration, but ideally no `+d` would be added to a clean release version.

**Comment by jwodder** [comment]
@yarikoptic This is because the `Dockerfile` is not copied into the Docker image, resulting in the source in `/src/heudiconv` being dirty.

**Comment by yarikoptic** [comment]
could you please propose PR with a fix?

**Comment by yarikoptic** [comment]
all good in that it now includes the next commit and not a date:

```
$> docker run -it --rm --entrypoint bash -v /tmp/mount:/mnt:ro -v /tmp/mount/rw:/mnt/rw:rw nipy/heudiconv:master -c 'python -c "import heudiconv;print(heudiconv.__version__)"'
0.11.5.post2+g4ac084b
```
