### ISSUE TITLE
provide CONTRIBUTING.md (or .rst)

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#636]
Came up in https://github.com/nipy/heudiconv/pull/614#issuecomment-1426402640 the fact that we grew code organically without any developers/contributors guidance. Time to fix that , define docstrings style (numpy) , some "recommended" max line length (120?) and then other aspects. Might be worth taking https://github.com/datalad/datalad/blob/maint/CONTRIBUTING.md and stripping/tuning for this one.

**Comment by TheChymera** [comment]
Done in PR above.
