### ISSUE TITLE
Installation of dcm2niix from PyPi does not support use in container with arbitrary UID

### ISSUE THREAD

**Issue by jennydaman** [nipy/heudiconv#648]
### Use Case

We want to run heudiconv's image from Docker Hub using [Apptainer (Singularity)](https://apptainer.org/).

### The Problem

https://github.com/nipy/heudiconv/blob/94911c7d1605c076f6f62c3943dc8a5ad74ba8c6/heudiconv/info.py#L25

Here it is specified that `dcm2niix` is to be installed from PyPi. However, the Python package `dcm2niix` is not the actual `dcm2niix` binary itself, instead it is a Python wrapper script which runs `dcm2niix`, downloading the binary if necessary.

The source code for the Python wrapper `dcm2niix` can be inspected by running

```shell
docker run --entrypoint cat nipy/heudiconv:0.12.0 '/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcm2niix/__init__.py'
```

<details>
<summary>Source code of dcm2niix Python wrapper</summary>

```python
"""Thin wrapper around dcm2niix binary"""
__author__ = "Casper da Costa-Luis <https://github.com/casperdcl>"
__date__ = "2022"
# version detector. Precedence: installed dist, git, 'UNKNOWN'
try:
    from ._dist_ver import __version__
except ImportError:  # pragma: nocover
    try:
        from setuptools_scm import get_version

        __version__ = get_version(root="../..", relative_to=__file__)
    except (ImportError, LookupError):
        __version__ = "UNKNOWN"
__all__ = ['bin', 'bin_path', 'main']

import os
import platform
from pathlib import Path

system = platform.system()
bin_name = "dcm2niix" + (".exe" if system == 'Windows' else "")
# 1: builtin
bin_path = Path(__file__).resolve().parent / bin_name

if not bin_path.is_file():
    p = Path(os.getenv('DCM2NIIX', ''))  # 2: env PATH
    if p.is_file():
        bin_path = p
    else:  # 3: download
        from miutil.fdio import extractall
        from miutil.web import urlopen_cached
        tag = {'Linux': "lnx", 'Darwin': "mac", 'Windows': "win"}[system]
        url = f"https://github.com/rordenlab/dcm2niix/releases/latest/download/dcm2niix_{tag}.zip"
        if system == 'Darwin':
            raise NotImplementedError(f"Please download & install {url} first")
        with urlopen_cached(url, bin_path.parent) as fd:
            extractall(fd, bin_path.parent)
            assert bin_path.is_file()

bin = str(bin_path)


def main(args=None):
    if args is None:
        import sys
        args = sys.argv[1:]
    from subprocess import run
    run([bin] + args)
```

</details>

As a consequence, the container images for heudiconv do not work unless the user is root.

### How to reproduce

Try either command:

```shell
docker run --rm -u 1000 --entrypoint sh nipy/heudiconv:0.12.0 dcm2niix
singularity exec docker://nipy/heudiconv:0.12.0 dcm2niix
```

### Actual Output

```
Traceback (most recent call last):
  File "/opt/miniconda-py39_4.12.0/bin/dcm2niix", line 5, in <module>
    from dcm2niix import main
  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcm2niix/__init__.py", line 36, in <module>
    with urlopen_cached(url, bin_path.parent) as fd:
  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/miutil/web.py", line 99, in urlopen_cached
    with fout.open("wb") as raw:
  File "/opt/miniconda-py39_4.12.0/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/opt/miniconda-py39_4.12.0/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
PermissionError: [Errno 13] Permission denied: '/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcm2niix/dcm2niix_lnx.zip'
```

### Expected output

```
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) (JP-LS:CharLS) GCC5.5.0 x86-64 (64-bit Linux)
usage: dcm2niix [options] <in_folder>

-- snip --
```

### Suggested Fix

The `dcm2niix` binary should be downloaded directly as a `RUN` instruction in `Dockerfile`, instead of happening implicitly at runtime. See https://github.com/rordenlab/dcm2niix#install

For the over-achiever, at my lab we're running `dcm2niix` on a multi-architecture cluster. We compile `dcm2niix` from source inside an Alpine container using automated, cross-platform, multi-stage builds. If interested, our solution can be found here: https://github.com/FNNDSC/pl-dcm2niix/blob/main/Dockerfile

**Comment by jennydaman** [comment]
This is a regression in v0.12.0 from v0.11.6

**Comment by dkp** [comment]
I have run into the same problem with the -u flag in the docker command.  It worked fine in v0.11.6, but now I get permission errors from dcm2niix.  I hope you can implement the fix.

**Comment by yarikoptic** [comment]
eh, I guess I was overly too enthusiastic since I believed for me on Linux `pip install dcm2niix` actually installed/built `dcm2niix` binary seems to me so I was hopeful that whls provide actual binaries not just download instructions. I guess the best would be to just revert #628 . Proposing https://github.com/nipy/heudiconv/pull/651 to quickly fix it.
