### ISSUE TITLE
heudiconv failure with false report of successful conversion

### ISSUE THREAD

**Issue by andycon** [nipy/heudiconv#657]
### Summary

When running the following command:

```
heudiconv -c dcm2niix --bids \
    -o /home/zhark/BIDS -g accession_number -f reproin -l \  Duchaine/Duchaine/1087_RO1pilot --files \
/inbox/DICOM/2023/04/02/A005734 -ss 02
```

I get the following error message before it finishes, which is somewhat not good --- BUT if I run reproin study-show after that, it reports that the accession/session is done! and converted as if there wasn't an error, which is more not good --- AND because it pukes before updating git/datalad, most of the files DO get written into the target folders (including into .heudiconv and sourcedata), while they DO NOT get tracked in git..

So, here is the output for the error (to be solved with some future effort..)
```
....
INFO: Adding "IntendedFor" to the fieldmaps in /home/zhark/BIDS/Duchaine/Duchaine/1087_RO1pilot/sub-sid002645/ses-02.
Traceback (most recent call last):
  File "/usr/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv==0.11.6', 'console_scripts', 'heudiconv')())
  File "/usr/lib/python3/dist-packages/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/usr/lib/python3/dist-packages/heudiconv/main.py", line 379, in workflow
    prep_conversion(sid,
  File "/usr/lib/python3/dist-packages/heudiconv/convert.py", line 209, in prep_conversion
    convert(cinfo,
  File "/usr/lib/python3/dist-packages/heudiconv/convert.py", line 587, in convert
    populate_intended_for(session_path, **populate_intended_for_opts)
  File "/usr/lib/python3/dist-packages/heudiconv/bids.py", line 912, in populate_intended_for
    selected_fmaps[json_file] = select_fmap_from_compatible_groups(
  File "/usr/lib/python3/dist-packages/heudiconv/bids.py", line 830, in select_fmap_from_compatible_groups
    json_acq_time = datetime.strptime(
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2023-04-02T11:47:09' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

Here is the tail end of
~/proj/reproin/bin/reproin study-show Duchaine/Duchaine/1087_RO1pilot:

```
# /inbox/DICOM/2023/03/27/A005717 done  sid002637 session=day1  !!! was converted into sid002637/ses-02
# /inbox/DICOM/2023/04/01/A005732 done  sid002645 session=day1  !!! was converted into sid002645/ses-01
# /inbox/DICOM/2023/04/02/A005734 done  sid002645 session=day1  !!! was converted into sid002645/ses-02
```

And here is git status report:

```
zhark@rolando:/home/zhark/BIDS/Duchaine/Duchaine/1087_RO1pilot$ git status
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.heudiconv/sid002645/ses-02/
	sourcedata/sub-sid002645/ses-02/
	sub-sid002645/ses-02/
```

nothing added to commit but untracked files present (use "git add" to track)

So we should try to fix reproin (?) so that study-show does not falsely report successful conversion when such a break happens.

RE the time format error: It looks like python _strptime.py doesn't appreciate "000000" for milisecs?
It looks like because the Acquisition time for this run just happened to be exactly on the second 11:47:9.000000, some parser made it into  2023-04-02T11:47:09 instead of 2023-04-02T11:47:09.0

or something...

func/sub-sid002645_ses-02_task-voice_run-03_bold.json:  "AcquisitionTime": "11:47:9.000000",

FROM Yarik:

wow -- congrats, you were lucky enough to hit such an unlucky time point
and detect a bug.  My bet it is due to a bug in a very ugly and ad-hoc
https://github.com/dbic/heudiconv/blob/HEAD/heudiconv/utils.py#L190

but there is a check that we save/load for identical value so not sure
yet if it is the one exactly to blame here.  Would need to look into it.

Please file a heudiconv issue, may be with above note from myself

**Comment by yarikoptic** [comment]
population of IntendedFor field is done after the conversion, so you can end up with converted data (thus reproin would confirm that), just IntendedFor would not be populated and the results were not `datalad save`d/committed.

I modified original report and added a few `s to make pasted output verbatim.

**Comment by yarikoptic** [comment]
looking at the actual error

```
ValueError: time data '2023-04-02T11:47:09' does not match format '%Y-%m-%dT%H:%M:%S.%f'
```

and similar'ish (different place/format) recent report in https://neurostars.org/t/heudiconv-time-format-error/25806 I think we should just adjust all of the strptimes to make `.f` optional!
