### ISSUE TITLE
BIDSVersion in data_description.json file

### ISSUE THREAD

**Issue by pbbaba** [nipy/heudiconv#698]
### Summary
I ran heudiconv converter on my local machine to convert the dataset (DICOM to BIDS). The files were converted to the BIDS format. The requried files were also generated. However when I checked the `dataset_description.json` file, the BIDSVersion value in it is `1.4.1`. The current BIDS version is `1.8.0`. 

Is the current heudiconv version (v0.13.1) compatible with BIDS v1.8.0? If not, is heudiconv going to be developed/updated to make it comply with the latest version of BIDS?

NOTE:
Heudiconv version:
Used the latest version of heudiconv. For installation I used `docker pull nipy/heudiconv:latest` command.

**Comment by pbbaba** [comment]
The docker image that has been pushed to the docker hub doesn't have the change reflected. It still makes an entry of 1.4.1 for BIDVersion.

**Comment by yarikoptic** [comment]
that change was not released so the `:latest` would not have it.  The `:master` which is built from master branch should have it. Which docker image did you use?

**Comment by pbbaba** [comment]
I am using the latest version of the docker image. Please see below the image for details
<img width="1205" alt="Screenshot 2023-09-18 at 2 03 00 PM" src="https://github.com/nipy/heudiconv/assets/139997204/6af5bba5-4f23-4c5c-9d5e-31e3255088a3">

**Comment by yarikoptic** [comment]
so it would be the "latest release" and not have that fix yet. Can you try `nipy/heudiconv:master`?

**Comment by pbbaba** [comment]
Yes. I tried `nipy/heudiconv:master`. I got the following error:

Error response from daemon: Head "https://registry-1.docker.io/v2/nipy/heudiconv/manifests/master": Get "https://auth.docker.io/token?scope=repository%3Anipy%2Fheudiconv%3Apull&service=registry.docker.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

The command I used was - `docker pull nipy/heudiconv:master`

**Comment by yarikoptic** [comment]
sad...  try again?

```shell
smaug:~
$> docker pull nipy/heudiconv:master
master: Pulling from nipy/heudiconv
5dea071bb978: Pull complete 
0c5049af550a: Pull complete 
fb213c315f5f: Pull complete 
8f6e625328e9: Pull complete 
2eee707202b0: Pull complete 
7d20dbbad1c5: Pull complete 
dd931be9c0e0: Pull complete 
7cad294d7fb0: Pull complete 
78414458892d: Pull complete 
e21d0db99f29: Pull complete 
Digest: sha256:236fff22770960fab471a7b2cbde47129d8c4e5bcfff6761bd52fa1ea6721736
Status: Downloaded newer image for nipy/heudiconv:master
docker.io/nipy/heudiconv:master

$> docker images | grep nipy/heudiconv.*master
nipy/heudiconv                                   master                      fb5a9180247d   8 days ago      1.28GB

```

**Comment by pbbaba** [comment]
It worked now!
Also the BIDSVersion in the dataset_description is updated with the recent version. 
Quick question - Going forward, should I be using the `master` tag or the `latest` tag?

**Comment by yarikoptic** [comment]
Ideally, you should use a specific version so there is consistent operation. "Thanks" due to mislabeled PR we now have `1.0.0` (for better or for worse) of heudiconv released and docker image built. So use `nipy/heudiconv:1.0.0`
