### ISSUE TITLE
TST: updates to dcm2niix

### ISSUE THREAD

**Issue by satra** [nipy/heudiconv#70]
https://github.com/rordenlab/dcm2niix/issues/122#issuecomment-320650090

**Comment by yarikoptic** [comment]
Hi @satra -- did you have a chance to check it out?  I thought to update dcm2niix in neurodebian to include that "snapshot", but not sure on either that change in output has any effect for us

**Comment by satra** [comment]
i haven't yet. @mgxd - could you please test this out?

**Comment by yarikoptic** [comment]
@hjmjohnson wanted to add something to the discussion? ;)

**Comment by hjmjohnson** [comment]
Sorry, no.  that was a mistake.  I meant to close an issue on another project, and pressed the button in the wrong browser windows.  

Very sorry,
Hans

**Comment by mgxd** [comment]
After some quick checks, new dcm2niix seems fine - this should be closed once #111 is updated
