### ISSUE TITLE
Change in behaviour of -s flag

### ISSUE THREAD

**Issue by leej3** [nipy/heudiconv#71]
Just documenting a change in behavior. Not sure if this was intended. Previously if the dicom contained a subject identifier different from the desired output subject identifier one could pass the latter as part of the heudiconv call. This no longer works as {subject} now needs to be included in the dicom template:

$ singularity exec --bind $PWD:/data nipy_heudiconv-2017-05-27-2471285b9681.img heudiconv -d /data/dicoms/*-03686103-20151022-11160-DICOM.tar -s 001 -ss 01 -f /data/anal/heudiconv_files/heuristics/convertall.py -b -o /data/bids_v_01_generic -c none

INFO: Processing 1 dicoms
INFO: Generated sequence info with 20 entries

$ singularity exec --bind $PWD:/data nipy_heudiconv_latest-2017-08-07-6b7e1ec1c6f4.img heudiconv -d /data/dicoms/*-03686103-20151022-11160-DICOM.tar -s 001 -ss 01 -f /data/anal/heudiconv_files/heuristics/convertall.py -b -o /data/bids_v_03_generic -c none

Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2079, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2071, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 1835, in _main
    grouping=grouping)
  File "/usr/local/bin/heudiconv", line 1422, in get_study_sessions
    "subject id.  Got %r" % dicom_dir_template)
ValueError: dicom dir template must have {subject} as a placeholder for a subject id.  Got '/data/dicoms/*-03686103-20151022-11160-DICOM.tar'

**Comment by satra** [comment]
@leej3 - i think we can relax this requirement as it really is not necessary.

**Comment by leej3** [comment]
Ok, had mentioned it to @yarikoptic so just wanted to document it. Thanks

**Comment by satra** [comment]
@mgxd  and @yarikoptic - any reason why this if is necessary?

https://github.com/nipy/heudiconv/blob/master/bin/heudiconv#L1419

i can imagine pointing to a collection of dicoms that doesn't have a subject identifier or a session identifier.

**Comment by yarikoptic** [comment]
I guess I had an idea of making it clear(er):

```shell
positional arguments:
  files                 files (tarballs, dicoms) or directories containing
                        files to process. Specify one of the
                        --dicom_dir_template or files not both

optional arguments:
...
  -d DICOM_DIR_TEMPLATE, --dicom_dir_template DICOM_DIR_TEMPLATE
                        location of dicomdir that can be indexed with subject
                        id {subject} and session {session}. Tarballs (can be
                        compressed) are supported in addition to directory.
                        All matching tarballs for a subject are extracted and
                        their content processed in a single pass

```
so it is either just those files (could be multiple, so -d doesn't quite scale) via positional argument (hence no template needed) OR a template, into which you place subject (template which has no subject field to fill in made little sense since then it should be just sorted into sessions).

**Comment by mgxd** [comment]
as @yarikoptic pointed out, this is a good use for the `--files` flag
