### ISSUE TITLE
No module named convertall

### ISSUE THREAD

**Issue by UNCfMRIworkshop** [nipy/heudiconv#74]
Hi, I am trying to use heudiconv to convert a batch of dicoms to bids format. When I attempt to run it through docker I get an error saying:

Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2079, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2071, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 1830, in _main
    heuristic = load_heuristic(os.path.realpath(args.heuristic_file))
  File "/usr/local/bin/heudiconv", line 1396, in load_heuristic
    mod = __import__(fname.split('.')[0])
ImportError: No module named convertall

This is the command I used:

docker run --rm -it -v $PWD:/data nipy/heudiconv -d /data/{subject}/YAROSLAV_DBIC-TEST1/*/*/*IMA -s PHANTOM1_3  -f /convertall.py -c none -o /data/output

I have previously gotten it to work without this error (a couple months ago). 
I have tried pulling the latest version and still no luck.

Thanks,
Grace

**Comment by paola-o** [comment]
I use this without the docker container, but if it works in the same way, I think you might have to specify where your convertall.py script is located  (on github, it's under the /heudiconv/heuristics/ directory)

Hope that helps!

**Comment by yonestar** [comment]
Hi, I am having the same issue as the original post.  Am using through docker.  I have correctly specified the location of the covertall.py script (it is in the PWD).

`yoni 36$ docker run --rm -it -v $PWD:/data nipy/heudiconv -d /data -s 32 -f convertall.py -c none -o /data/output
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2079, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2071, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 1830, in _main
    heuristic = load_heuristic(os.path.realpath(args.heuristic_file))
  File "/usr/local/bin/heudiconv", line 1396, in load_heuristic
    mod = __import__(fname.split('.')[0])
ImportError: No module named convertall`

**Comment by satra** [comment]
the convertall.py heuristic is located at this location inside the container:

`/heuristics/convertall.py`

**Comment by paola-o** [comment]
This might be helpful to members of this thread:

In order to navigate through the contents of a container (using an interactive shell within the container) you can run 
singularity shell nipy_heudiconv-2017-08-07-efe104c02e70.img 

I'm assuming this works similarly on docker.

**Comment by tjhendrickson** [comment]
Hello,

I am also having this problem. 

Satra - you indicate that the convertall module is within the following directory inside the container: /heuristics/convertall.py, however when I run the following: docker run -it --rm -v $PWD:/data docker.io/nipy/heudiconv -d /home/bfs-raid2/dicom-data/stage/TO_BE_ZIPPED/PN-{subject}*/* -s 50818 -f /heuristics/convertall.py -c none -o /data/output 

I get the following error: 
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.4', 'console_scripts', 'heudiconv')()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 99, in main
    process_args(args)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 204, in process_args
    heuristic = load_heuristic(op.realpath(args.heuristic_file))
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/utils.py", line 265, in load_heuristic
    mod = __import__(fname.split('.')[0])
ImportError: No module named convertall

**Comment by mgxd** [comment]
@tjhendrickson since then, the Dockerfile has been updated:

all heuristics found on this repo are available, including convertall.py

the new path within the container is `/src/heudiconv/heuristics/`

**Comment by DVSneuro** [comment]
Hi, I'm getting the same error when I follow along with the tutorial below. Has the path changed in the container again? Thanks.

http://nipy.org/workshops/2017-03-boston/lectures/bids-heudiconv/#14

`docker run --rm -it -v /Users/DVS/testingground:/data:ro -v /Users/DVS/testingground/output:/output nipy/heudiconv:latest -d /data/{subject}/YAROSLAV_DBIC-TEST1/*/*/*IMA -s PHANTOM1_3 -f /src/heudiconv/heuristics/convertall.py -c none -o /output`

INFO: Running heudiconv version 0.5.dev1
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.dev1', 'console_scripts', 'heudiconv')()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 120, in main
    process_args(args)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 240, in process_args
    heuristic = load_heuristic(args.heuristic)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/utils.py", line 280, in load_heuristic
    mod = __import__(fname.split('.')[0])
ImportError: No module named convertall

**Comment by mgxd** [comment]
@DVSneuro sorry about that, there has been a large amount of shuffling lately to get things in proper order. Heudiconv now has some of these heuristics built in, making it easier to use. You can change your `-f` flag to simply:
```
-f convertall
```

**Comment by DVSneuro** [comment]
@mgxd Thanks! That did the trick. And thanks for maintaining this package! We'll be using it to convert DICOMS to BIDS at our center.

**Comment by yarikoptic** [comment]
@DVSneuro For new sequences/studies you might consider precrafted specification/heuristic , see https://github.com/repronim/reproin

**Comment by DVSneuro** [comment]
Thanks, @yarikoptic ! We'll definitely check that out for our new study. I'll be sure to suggest it to my colleagues.

**Comment by swatirane** [comment]
Hi I am trying to use heudiconv on a Linux machine with Philips DICOM files. I  used the command:

docker run --rm -it -v /var/local/scratch/srleven/MIDP:/data:ro -v /var/local/scratch/srleven/MIDP:/output nipy/heudiconv:latest -d /data/{subject}/DICOM/DICOM/IM* -s MIDP_001 -f /data/bin/srl_heuristic.py -c none -o /output

My heuristic file is:
import os

def create_key(template, outtype=('nii.gz',), annotation_classes=None):
    if template is None or not template:
        raise ValueError('Template must be a valid format string')
    return template, outtype, annotation_classes


def infotodict(seqinfo):
    """Heuristic evaluator for determining which runs belong where
    allowed template fields - follow python string module:
    item: index within category
    subject: participant id
    seqitem: run number during scanning
    subindex: sub index within group
    """

    T1 = create_key('anat/sub-{subject}_T1')
    BOLD1 = create_key('func/sub-{subject}_BOLD1')
    BOLD2 = create_key('func/sub-{subject}_BOLD2')
    BOLD3 = create_key('func/sub-{subject}_BOLD3')

    info = {T1:[], BOLD1:[], BOLD2:[], BOLD3:[]}

    for s in seqinfo:
        """
        The namedtuple `s` contains the following fields:
        * total_files_till_now
        * example_dcm_file
        * series_id
        * dcm_dir_name
        * unspecified2
        * unspecified3
        * dim1
        * dim2
        * dim3
        * dim4
        * TR
        * TE
        * protocol_name
        * is_motion_corrected
        * is_derived
        * patient_id
        * study_description
        * referring_physician_name
        * series_description
        * image_type
        """
        if (s.dim4 == 1):
            info[T1].append(s.series_id)
        if (s.dim3 == 3.5):
            info[BOLD1].append(s.series_id)
        if (s.dim3 == 2):
            info[BOLD2].append(s.series_id)
        if (s.dim3 == 1):
            info[BOLD3].append(s.series_id)
    return info



But I keep getting:
INFO: Running heudiconv version 0.6.0.dev1
INFO: Ned to process 0 study sessions.

Can you tell me what I am missing?

Thanks!
SRL
