### ISSUE TITLE
error in tutorial slides

### ISSUE THREAD

**Issue by yonestar** [nipy/heudiconv#75]
Hi,

In the tutorial slides posted here http://nipy.org/workshops/2017-03-boston/lectures/bids-heudiconv/#4 on slide #4 the git clone command should be updated to read:
`git clone http://datasets.datalad.org/dicoms/dartmouth-phantoms/PHANTOM1_3/.git`

The current command does not work (I believe the data was moved)

thanks

**Comment by yarikoptic** [comment]
Thank you! Confirming that since then the test directory was dissolved and that dataset got a proper place as you pointed out

**Comment by mgxd** [comment]
@yarikoptic could you point me to the new location? I'm updating the slides now

**Comment by yarikoptic** [comment]
@mgxd, @yonestar pointed to the correct corrected one: ```git clone http://datasets.datalad.org/dicoms/dartmouth-phantoms/PHANTOM1_3/.git```

**Comment by mgxd** [comment]
lol ... guess i misread - thanks!!

**Comment by yonestar** [comment]
also small note that would be good to add to tutorial:  after convertall script runs, its output is in `output/.heudiconv`  -- this does not show up with `ls` command, requires `ls -a` to see the dir

**Comment by paola-o** [comment]
Very helpful @yonestar! I've spent hours looking for the output. Any way this could be modified so the output of convertall is not hidden?

**Comment by wanirepo** [comment]
Hi,

I also found a potential error in the example slide. It's on slide #30 phantom_heuristic.py. 

The error message is like this:
`Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2079, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2071, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 1934, in _main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 1281, in convert_dicoms
    info = heuristic.infotodict(seqinfo_list)
  File "/data/phantom_heuristic.py", line 16, in infotodict
    info[dwi].append(s.series_number) # append if multiple series meet criteria
AttributeError: 'SeqInfo' object has no attribute 'series_number'
`

And when I looked into seqinfo, there was a similar one, series_id. After I replaced s.series_number with s.series_id, the final code worked. It would be good to have an updated example slides soon! :)

Thanks for the great tool.

Thanks,
Wani

**Comment by mgxd** [comment]
Thank you all for the suggestions, the documentation has been updated - if there are any parts that you feel could be improved or are not clear enough, let us know!

**Comment by wanirepo** [comment]
One question: 

In your docker example slide, you used `{item:01d}` to give different numbers to different number of runs (e.g., run1, run2, etc.). And item is defined using this line: `info[rest].append({'item': s.series_id, 'rec': 'corrected'})`

And when I see what's in series_id, series_id is string with "SeriesNumber + ProtocolName" (e.g., '25-r2_460tr_xxx') which is defined as `series_id = '-'.join(map(str, series_id))`. In our data, SeriesNumber is not necessarily the run number. 

Even in this case, I wonder `{item:01d}` will provide the right run numbers. I have had difficult time to figure this out, and hasn't been successful to get run1, run2, etc. as the func file names. 

Could you give me some guidance on that? Given that I'm not a python master, I might miss something.  Any inputs on this would be appreciated!

Thanks,
Wani

**Comment by tjhendrickson** [comment]
When I attempt to perform the git command on slide 4: git clone http://datasets.datalad.org/dicoms/dartmouth-phantoms/PHANTOM1_3/.git/, I get the following error message: fatal: could not create work tree dir 'PHANTOM1_3'.: Permission denied

**Comment by yarikoptic** [comment]
@tjhendrickson make sure you have permission to create a new directory where you are ATM

**Comment by tjhendrickson** [comment]
Hmm I am little confused by this, perhaps this is driven by my lack of
knowledge with Docker. On my local machine I certainly have permission to
create new directories, however, once I move within the Docker container
(as the tutorial suggests) determining directory permissions are out of my
control.

What am I missing here?

-Tim

Timothy Hendrickson
Department of Psychiatry
University of Minnesota
Bioinformatics and Computational Biology M.S. Candidate
Office: 612-624-6441
Mobile: 507-259-3434 (texts okay)

On Tue, Jan 2, 2018 at 9:54 PM, Yaroslav Halchenko <notifications@github.com

**Comment by ddwagner** [comment]
Looks like this is the issue to point out problems with the docs and slides. 

Following the tutorial in the slides produces output that fails the bids validator seemingly due to the lack of subject-specific directories. Appears to be related to issue #89 . Following satra's recommendation by modifying the heuristic file to explicitly include the subject as a directory  (e.g., t1w = create_key('sub-{subject}/anat/sub-{subject}_T1w')) fixes the issue for the tutorial data (PHANTOM1_3) and for our own datasets. Assuming I'm not missing a reason why heudiconv doesn't do sort files into subject directories automatically; it would be helpful to new users if the slides and heudiconv readme.md were updated. Possibly also the heuristics in the repository as well so as not to breed confusion when people poke through them!

Thanks
