### ISSUE TITLE
How to run heudiconv

### ISSUE THREAD

**Issue by kevnmr** [nipy/heudiconv#78]
Hi

Sorry for being a newbie. So my dir structure is. Project/Subject/Session/Scans/Images(.dcm)

I tried:

heudiconv -d ~/Desktop/Drive\ Images/DiabC/{subject}/*/*/*.dcm -s $sub -f /usr/local/share/heudiconv/heuristics/convertall.py -c
 dcm2niix -o ~/Documents/Data/

Got error:

Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2120, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2112, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 1876, in _main
    grouping=grouping)
  File "/usr/local/bin/heudiconv", line 1457, in get_study_sessions
    assert sids
AssertionError

Am i doing this right? Thank you.

Kevin

**Comment by mgxd** [comment]
Hi @kevnmr

the `-d` flag is the template that points to the dicoms, substituting the `{subject}` field with what is provided in the `-s` flag. There may be two things going on in your case

1) The `-d` template is incorrect - if it follows the directory structure you listed, it should look like
    ```
    ~/Desktop/Drive\ Images/DiabC/{subject}/*/*/*.dcm
    ```
     if you want to grab dicoms across sessions/scans. If you want a specific session,
     ```
    ~/Desktop/Drive\ Images/DiabC/{subject}/{session}/*/*.dcm
    ```
    will work, but you'll have to provide an additional argument `-ss`

2) Ensure that the `-s` flag is correct (have you defined `$sub` and if you substitute the name in the template, is the directory found?

**Comment by xaviergp** [comment]
I think I have a similar problem.

My dicoms are here:
/Users/xavierguell/Desktop/SRT_creatingheuristic/data/subj001/dicom

I do this:
docker run --rm -it -v /Users/xavierguell/Desktop/SRT_creatingheuristic/data:/data --entrypoint=bash nipy/heudiconv

Then this:
heudiconv -d /data/{subject}/dicom/*.dcm -s subj001 -f /heuristics/convertall.py -c none -o /data/output

And I get this error:
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2197, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2189, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 2052, in _main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 1364, in convert_dicoms
    grouping=None,  # no groupping
  File "/usr/local/bin/heudiconv", line 425, in group_dicoms_into_seqinfos
    assert studyUID == file_studyUID
AssertionError

**Comment by mgxd** [comment]
@xaviergp separate error - I believe this one is probably happening because it is finding two or more different sessions in the -d dicom_template you provided.

**Comment by xaviergp** [comment]
thanks @mgxd !
There were two sessions in my dicom folder, and the problem was solved by using heudiconv -d /data/{subject}/dicom/910230-*.dcm instead of heudiconv -d /data/{subject}/dicom/*.dcm
"910230-" identifies only one of the two sessions in my dicom folder

**Comment by mgxd** [comment]
@kevnmr are you still running into issues?

**Comment by mgxd** [comment]
closing this for now - if you are still running into issues please reopen!
