### ISSUE TITLE
Add RRID somewhere on docs

### ISSUE THREAD

**Issue by asmacdo** [nipy/heudiconv#795]
### Summary

 RRID:SCR_017427 (taken from JOSS paper https://joss.theoj.org/papers/10.21105/joss.05839)

 This should be in the README and docs

**Comment by asmacdo** [comment]
do a badge like datalad

**Comment by yarikoptic** [comment]
yeap -- badge to README.md like in datalad `[![RRID](https://img.shields.io/badge/RRID-SCR__003931-blue)](https://identifiers.org/RRID:SCR_003931)`

and then to docs as well
