### ISSUE TITLE
Add ability to change subject folder name

### ISSUE THREAD

**Issue by chrisfilo** [nipy/heudiconv#8]
BIDS require "sub-{subject_id}" name instead of "{subject_id}"

**Comment by hanke** [comment]
You can already use the --anon-cmd option to achieve that. The subject folder will be whatever is returned by this command.

**Comment by hanke** [comment]
Especially in the case of a bids dataset people may have DICOMs with some imaging center subject ID that should not be made public to prevent undesired cross-referencing of individuals across studies.

**Comment by satra** [comment]
> that should not be made public to prevent undesired cross-referencing of individuals across studies.

perhaps it's important to note that this would be direct cross referencing. we can always do image based cross-referencing with public/private data.

**Comment by hanke** [comment]
Sure thing. But I am more concerned about subject IDs that go like: first four characters of the lastname, and the year of birth ;-)

**Comment by mgxd** [comment]
#50 adds the sub- prefix as well as other bids friendly features if `-b` bids flag is used

**Comment by tjhendrickson** [comment]
Hello,

It is unclear to me how the --anon-cmd works. Can someone provide an example?

Thanks!

**Comment by mgxd** [comment]
@tjhendrickson `--anon-cmd` allows a call to any executable in your path - ex.

```
heudiconv . . . --anon-cmd md5sum
```
will rename your subject id to its md5 hash. I don't believe this supports multi-space commands yet - ex.
```
heudiconv . . . --anon-cmd "python randomizer.py"
```
Having rarely used this input, feel free to open an issue if you encounter any problems
