### ISSUE TITLE
Siemens Csa headers

### ISSUE THREAD

**Issue by kasbohm** [nipy/heudiconv#80]
Hi, running heudiconv on Siemens (Avanto/Skyra/Prisma) data, I get:
`Ignoring xxxx.IMA since not quite a «normal» DICOM: Dataset does not have attribute ‘ProtocolName’.`

I guess this is caused by the attribute not being present at the normal location (0018 1030) in our Siemens DICOMS, but exists as tProtocolName in the private Csa header. Did I miss a switch when calling heudiconv, or does some logic need to be added? nibabel.nicom.csareader? 

Cheers!

**Comment by neurolabusc** [comment]
I updated dcm2niix so if ProtocolName is not in the DICOM header it use the ProtocolName in the CSA header for the BIDS sidecar. This is a hail mary, and only influences the BIDS sidecar: the protocol name will still be empty with regards to the output filename (e.g. `-f %p`). Whether this helps you depends on whether heudiconv uses dcmstack or dcm2niix to determine the protocol name.

**Comment by satra** [comment]
@neurolabusc - thanks. at this point we would probably have to make this change on our side inside our grouping function. but eventually we should consider where the metadata get extracted.

**Comment by satra** [comment]
@mgxd - can you add this as part of your refactor?
