### ISSUE TITLE
'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by wanirepo** [nipy/heudiconv#81]
Today I did "docker pull" and it now produces a new type of error. It would be greatly appreciated if you could help. 

Error message is like this:

> $ docker run --rm -it -v $PWD:/data nipy/heudiconv -d /data/{subject}/*/*IMA -s WCWsession1 -f /data/WCW_heuristic_1.py -c dcm2niix -b -o /data/output
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': None, 'outdir': '/data/output/', 'subject': 'WCWsession1'}
INFO: Processing 2834 dicoms
INFO: Reloading existing filegroup.json because /data/output/.heudiconv/WCWsession1/info/WCWsession1.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Converting /data/output/run001 (224 DICOMs) -> /data/output . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: Executing node convert in dir: /tmp/heudiconvdcm9ccTKA/convert
INFO: Running: dcm2niix -b y -z i -x n -t n -m n -f output -o /tmp/heudiconvdcm9ccTKA/convert -s n -v n /tmp/heudiconvdcm9ccTKA/convert/20170612_WCW.MR.COCOAN_FMRI_MBEPI.0015.0001.2017.06.12.16.07.00.956995.128218061.IMA
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2120, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2112, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 1975, in _main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 1351, in convert_dicoms
    outdir=tdir)
  File "/usr/local/bin/heudiconv", line 929, in convert
    save_scans_key(item, outname_bids_files)
  File "/usr/local/bin/heudiconv", line 1062, in save_scans_key
    subj_, ses_ = _find_subj_ses(f_name)
  File "/usr/local/bin/heudiconv", line 1035, in _find_subj_ses
    res = regex.search(f_name).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'

The heuristic code I used is as follows:

import os
def create_key(template, outtype=('nii.gz',), annotation_classes=None):
    if template is None or not template:
        raise ValueError('Template must be a valid format string')
    return template, outtype, annotation_classes
    
def infotodict(seqinfo):
    """Heuristic evaluator for determining which runs belong where
    allowed template fields - follow python string module:
    item: index within category
    subject: participant id
    seqitem: run number during scanning
    subindex: sub index within group
    """
    t1 = create_key('anat/sub-{subject}_T1')
    task = create_key('func/sub-{subject}_run-{item:02d}_task-{type}_bold')
    info = {t1: [], task: []} 
    
    for s in seqinfo:
        if (s.dim3 == 224) and (s.dim4 == 1):
            info[t1] = [s.series_id] # assign if a single series meets criteria
        elif (s.dim4 == 870) and ('r1_2.7iso_ap_64ch_mb8' in s.protocol_name):
            info[task].append({'item': s.series_id, 'type': 'painsound'})
        elif (s.dim4 == 870) and ('r2_ap_64ch_mb8' in s.protocol_name): 
            info[task].append({'item': s.series_id, 'type': 'painsound'})                
    return info

**Comment by satra** [comment]
does the following work:

```
docker run --rm -it -v $PWD:/data nipy/heudiconv -d /data/{subject}/*/*IMA -s WCWsession1 -f /heuristics/convertall.py -c dcm2niix -b -o /data/output
```

this will help us isolate whether the issue is in the data, heudiconv, or in the heuristic.

**Comment by wanirepo** [comment]
Yep exactly same error!

> INFO: Processing 2834 dicoms
INFO: Reloading existing filegroup.json because /data/output/.heudiconv/subj1/info/subj1.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Converting /data/output/run001 (224 DICOMs) -> /data/output . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: Executing node convert in dir: /tmp/heudiconvdcmwUieOR/convert
INFO: Running: dcm2niix -b y -z i -x n -t n -m n -f output -o /tmp/heudiconvdcmwUieOR/convert -s n -v n /tmp/heudiconvdcmwUieOR/convert/20170612_WCW.MR.COCOAN_FMRI_MBEPI.0015.0001.2017.06.12.16.07.00.956995.128218061.IMA
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2120, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2112, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 1975, in _main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 1351, in convert_dicoms
    outdir=tdir)
  File "/usr/local/bin/heudiconv", line 929, in convert
    save_scans_key(item, outname_bids_files)
  File "/usr/local/bin/heudiconv", line 1062, in save_scans_key
    subj_, ses_ = _find_subj_ses(f_name)
  File "/usr/local/bin/heudiconv", line 1035, in _find_subj_ses
    res = regex.search(f_name).groupdict()
AttributeError: 'NoneType' object has no attribute 'groupdict'

**Comment by satra** [comment]
@yarikoptic - this may be for you to take a quick look at. 

@wanirepo - if you have a chance to collect limited data on a phantom and share publicly that would be very helpful to iron such issues.

**Comment by yarikoptic** [comment]
I see... that function operates under assumption that in BIDS mode we have a legit BIDS dataset (ie file paths to the files are under corresponding directories etc), which is not necessarily the fact... I guess I will make it skip extraction of events if it doesn't detect such "fullfilled" BIDS layout... hold on there!

**Comment by yarikoptic** [comment]
#82 might workaround for it... didn't test yet

**Comment by wanirepo** [comment]
Thanks for your quick response and fix! I've been using docker, and I guess I might not be able to test #82 with docker yet, right?

**Comment by wanirepo** [comment]
Okay, I added "--ses" option to remove "None" for the session (e.g., --ses 1), and it seems to work now, but another problem -- converting only one run, and stop. I will move to that issue and keep asking questions. Thanks!
