### ISSUE TITLE
problem parsing specific set of files

### ISSUE THREAD

**Issue by poldrack** [nipy/heudiconv#85]
I am having trouble parsing a specific set of files, which I think may be happening due to the presence of spaces rather than underscores in the series_description:

SeqInfo(total_files_till_now=211, example_dcm_file='EM2311_A.MR.RIC_Modified_Protocols_TIM_Protocols.2.10.20141005.105003.rjrf9w.dcm', series_id='2-MPRAGE T1 AX 0.8 mm TI-766', unspecified1='DICOM', unspecified2='-', unspecified3='-', dim1=320, dim2=220, dim3=208, dim4=1, TR=2.2, TE=2.83, protocol_name='MPRAGE T1 AX 0.8 mm TI-766', is_motion_corrected=False, is_derived=False, patient_id='EM2311', study_description='MRI106', referring_physician_name='EM2311', series_description='MPRAGE T1 AX 0.8 mm TI-766', sequence_name='*tfl3d1', image_type=('ORIGINAL', 'PRIMARY', 'M', 'ND'), accession_number='', patient_age='050Y', patient_sex='F')

the heuristic seems to run properly, but then this occurs when the file is being parsed:

INFO: Converting /Users/poldrack/data_unsynced/GOBS/GOBS_bids/EM2311/anat/sub-EM2311_run-1_T1w (208 DICOMs) -> /Users/poldrack/data_unsynced/GOBS/GOBS_bids/EM2311/anat . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: Executing node convert in dir: /tmp/heudiconvdcmbLYWNS/convert
INFO: Running: dcm2niix -b n -z i -x n -t n -m n -f anat -o /tmp/heudiconvdcmbLYWNS/convert -s n -v n /tmp/heudiconvdcmbLYWNS/convert/EM2311_A.MR.RIC_Modified_Protocols_TIM_Protocols.2.10.20141005.105003.rjrf9w.dcm
INFO: Executing node embedder in dir: /tmp/heudiconvdcmbLYWNS/embedder
INFO: Post-treating /Users/poldrack/data_unsynced/GOBS/GOBS_bids/EM2311/anat/sub-EM2311_run-1_T1w.json file
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2120, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2112, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 1975, in _main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 1351, in convert_dicoms
    outdir=tdir)
  File "/usr/local/bin/heudiconv", line 958, in convert
    treat_infofile(scaninfo)
  File "/usr/local/bin/heudiconv", line 1227, in treat_infofile
    j_pretty = json_dumps_pretty(j_slim, indent=2, sort_keys=True)
  File "/usr/local/bin/heudiconv", line 236, in json_dumps_pretty
    assert(j == j_)
AssertionError

**Comment by poldrack** [comment]
my guess is that this has to do with there being a dash in the series description, but I'm not sure how to verify that...

**Comment by satra** [comment]
@poldrack - this is where it gets a little problematic to debug - any chance you can share privately the dicom repo? or have an equivalent collection on a phantom?

**Comment by satra** [comment]
@poldrack - give docker hub a few minutes to build the new image. it should then work on your data.
