### ISSUE TITLE
ensure this works when a dicom field is missing

### ISSUE THREAD

**Issue by satra** [nipy/heudiconv#93]
https://github.com/nipy/heudiconv/blob/257d80c491768d96896c38c1bd85afb1a33e8630/bin/heudiconv#L987

reported by @poldrack

**Comment by bcschiffler** [comment]
Also interested in a solution to this. Could it maybe be fixed via the following code?

```
if mw.dcm_data.get("PerformingPhysicianName"):
    row = [acq_time, mw.dcm_data.PerformingPhysicianName, randstr] 
else:
    row = [acq_time, 'n/a', randstr] 
```

or by explicitly catching the AttributeError which should appear when that field is missing (as in #61):

```
try:
    perfphys = mw.dcm_data.PerformingPhysicianName
except AttributeError:
    perfphys = 'n/a'
row = [acq_time, perfphys, randstr]
```

**Comment by satra** [comment]
@bcschiffler - that would work. could you please send a PR?

**Comment by bcschiffler** [comment]
@satra Sure, have done that!
