### ISSUE TITLE
TR, TE ValueError

### ISSUE THREAD

**Issue by bkraft4257** [nipy/heudiconv#98]
I am using heudiconv to convert my own DICOM files created from a Siemens scanner.  I have encountered problems with some of the series that Siemens creates where the TR and TE values are strings and not floats.  This results in a ValueError. 

(python2) flip ➜  synergy heudiconv -d '{subject}/{session}/data/dicom/20170914/*/*.DCM' --minmeta -b -c none -f convertall.py  -o ./output -s syn054 -ss 1

INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': '1', 'outdir': '/Users/bkraft/projects/hugenschmidt/synergy/output/', 'subject': 'syn054'}
INFO: Processing 1527 dicoms
INFO: Analyzing 1527 dicoms

Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2168, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2160, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 2023, in _main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 1335, in convert_dicoms
    grouping=None,  # no groupping
  File "/usr/local/bin/heudiconv", line 476, in group_dicoms_into_seqinfos
    TR = float(dcminfo.RepetitionTime) / 1000.
ValueError: could not convert string to float:

I modified the code on line 476 and 480 in heudiconv.py from 

     except AttributeError:

to 

    except (AttributeError, ValueError):

This resolved the error and allowed heudiconv to complete. 

I apologize for not issuing a pull request. I am still learning how to use GitHub and the process of collaborating on open source projects. 

Bob

**Comment by mgxd** [comment]
Hi Bob, thanks for the heads up - just curious, what is the value of `dcm.RepetitionTime` for your scan?

**Comment by bkraft4257** [comment]
I  read the DICOM header with pydicom.  The TR and TE are just empty strings. 

>>> ds = dicom.read_file("000001.DCM")

(0018, 0023) MR Acquisition Type                 CS: '2D'
(0018, 0024) Sequence Name                       SH: 'tfi2d1_113'
(0018, 0025) Angio Flag                          CS: 'N'
(0018, 0050) Slice Thickness                     DS: '8'
(0018, 0080) Repetition Time                     DS: ''
(0018, 0081) Echo Time                           DS: ''
(0018, 0082) Inversion Time                      DS: '145'
(0018, 0083) Number of Averages                  DS: '1'
(0018, 0084) Imaging Frequency                   DS: '123.221397'
