### ISSUE TITLE
Handle AttributeError exception of line 484: image_type = tuple(dcminfo.ImageType)

### ISSUE THREAD

**Issue by yinglilu** [nipy/heudiconv#99]
Hi heudiconv team,

Is it possible to add try-except of line 484: image_type = tuple(dcminfo.ImageType)?

We have some DICOM files missing the imageType tag, which choke the heudiconv:
'image_type = tuple(dcminfo.ImageType)
  File "/opt/anaconda2/lib/python2.7/site-packages/dicom/dataset.py", line 256, in __getattr__
    "'{0:s}'.".format(name))
AttributeError: Dataset does not have attribute 'ImageType'.'

According the DICOM standard, MR images' imageType tag is a type 1 attribute, it would be great if add try-except though.

Regards,

YingLi

**Comment by mgxd** [comment]
@yinglilu 

thanks for reporting this, we should be making many fields optional. 

Would you want to try submitting the PR?

**Comment by mgxd** [comment]
closed with b1e17d1
